### PR TITLE
Town portal spell fixes

### LINKED ISSUE #6012: Town Portals cause CTD (might be HOTA related)
**Describe the bug**

Entering a town portal, crashes the game. This might or might not be HOTA related.

**Game logs**

[VCMI_Client_log.txt](https://github.com/user-attachments/files/21750979/VCMI_Client_log.txt)
[VCMI_Launcher_log.txt](https://github.com/user-attachments/files/21750978/VCMI_Launcher_log.txt)
[VCMI_Server_log.txt](https://github.com/user-attachments/files/21750977/VCMI_Server_log.txt)

**To Reproduce**

1. Go to 'town portal map object'
2. Click on 'enter it'
3. Crash
4. no error, just ctd (although im on android so maybe it just doesnt work like this here)

**Expected behavior**
window with town list should open without CTD

**Actual behavior**
Enter town portal and insta crash the moment the window appears.

**Did it work earlier?**
well, worked in stable builds

**Screenshots**
Image

**Version**

- OS: on Android, but could be an issue on other builds
- Version: august 10's newest build

**Additional context**
Dont think there is anything else

### LINKED ISSUE #6068: Crash when visiting town teleport gate in WoG mod
**Describe the bug**

Visiting the town teleport gate in the WoG mod causes a crash. For the exact reproduction steps, see the video.

https://github.com/user-attachments/assets/d456600c-fbe9-4bc8-af76-3d3da1020397

Android 1.7 develop

### LINKED ISSUE #6239: The game crashes when using a town portal with advanced/expert earth. If the hero doesn't have the book.
Image

Image

map [testTP.zip](https://github.com/user-attachments/files/23054392/testTP.zip)

- OS: [Windows]
- Version: [VCMI version 1.7.0.6407d9cac33ed7a01dcb4519e3e6819a107c0b76, last develop, msvs x64]

### LINKED ISSUE #6240: Town Gate: Assertion `hero->canCastThisSpell(spellID.toSpell())' failed.
**Describe the bug**
Looks like there's something wrong with Town Gate on the given saved game. One hero of green player goes to a town gate building and the game crashes.

**Game logs**
[2025.10.2 VCMI_Client_log.txt green crashes town gate.zip](https://github.com/user-attachments/files/23062101/2025.10.2.VCMI_Client_log.txt.green.crashes.town.gate.zip)

**To Reproduce**
Open the saved game and end the turn. Green will crash.

**Expected behavior**
Town Gate should work.

**Actual behavior**
Town Gate crashes the game.

**Did it work earlier?**
Don't know.

**Screenshots**
Image
Image

**Version**
- OS: Linux Mint 21.3 / Ubuntu 22.04 LTS
- Version: [VCMI 1.7.0.8a9b83bb14835835398a15397b22bd59fa86cd73] (feature branch nullkiller2 with latest develop merge in it)

### LINKED ISSUE #6253: Casting town portal with advanced or expert earth magic crashes the game on latest build
**Describe the bug**

Using the spell town portal with advanced or expert earth magic crashes the application.

**Game logs**

[VCMI_Client_log.txt](https://github.com/user-attachments/files/23163379/VCMI_Client_log.txt)

**To Reproduce**

1. Start any scenario
2. Grant yourself town portal and advanced/expert earth magic with cheat codes
    a. it works with basic earth magic
3. Cast town portal

**Expected behavior**

To see a popup with list of friendly towns I could teleport to.

**Actual behavior**

The application crashes.

**Did it work earlier?**

Worked on 1.6.8

**Version**

- OS: macOS 15.6.1 (24G90)
- Version: Latest build ([VCMI-branch-develop-6b4179a.dmg](https://builds.vcmi.download/branch/develop/macos-arm/VCMI-branch-develop-6b4179a.dmg))

**Additional context**

I realise the latest builds can have bugs. Just reporting in case it helps.

### PR DESCRIPTION
**Pull request by IvanSavenko**
- Add workaround for crash on attempt to use town portal map object from wog and hota
- Town portal spell will now correctly use configuration parameter for town selection instead of direct spell level check
- Do not attempt to preserve object count in string when string does not contains object count
- Correctly look up last bracket, to correctly handle object names that contain brackets

Fixed bugs:
- Fixes #6012
- Fixes #6068
- Fixes #6239
- Fixes #6253
- Fixes #6240

### CODE REVIEW

File: server/CGameHandler.cpp [hunk 1]
```diff
@@ -3881,8 +3881,14 @@ void CGameHandler::castSpell(const spells::Caster * caster, SpellID spellID, con
 	const CSpell * s = spellID.toSpell();
 	s->adventureCast(spellEnv.get(), p);
 
-	if(const auto * hero = caster->getHeroCaster())
-		useChargeBasedSpell(hero->id, spellID);
+	// FIXME: hack to avoid attempts to use charges when spell is casted externally
+	// For example, town gates map object in hota/wog
+	// Proper fix would be to instead spend charges similar to existing caster::spendMana call
```
Comment (SoundSSGood) [inline server/CGameHandler.cpp:3886]: I'm not sure what you meant. Does this mean it makes sense to separate mana-based spells from charge-based spells?

Comment (IvanSavenko) [reply server/CGameHandler.cpp:3886]: No.
What I mean, is that currently game attempts to spend charges even when spell was activated externally (via map object).

Mana spending is handled by overload of `caster::spendMana` , which substracts mana from hero for normal cast, and is no-op method in case of external caster like map object. As result, mana is not spent when hero uses adventure map object that emulates spell cast.

Spending charges probably needs similar approach. Either introduce additional `spendCharges` method that will be called at the same time as existing `spendMana` call, or (better IMO), replace current `spendMana` call with `spendSpellCost`, that will take mana OR charges (depending on how spell was cast), and remain no-op method for external caster

Comment (SoundSSGood) [reply server/CGameHandler.cpp:3886]: Got it.
In any case, I don't see any other way to determine whether a spell uses charges or not. So this workaround might become the main one.

And if I remember correctly, in Hota, the external town portal consumes the hero's mana.

Comment (SoundSSGood) [reply server/CGameHandler.cpp:3886]: > So this workaround might become the main one.

I mean inside `spendSpellCost`

**Comment by Laserlicht** [comment]
@IvanSavenko Just fyi: The regression (crash on template list) reported on discord is already fixed in: #6243 (because we use this list box also there).
