### PR TITLE
[1.7.2] Server discovery

### LINKED ISSUE #6752: connection screen doesn't close after connection failure
**Describe the bug**
I've attempted IPv6 connection in a LAN game between iOS and macOS. Connection failed, but the connection screen doesn't close, the only way to proceed is to kill or quit the process.

Same behavior if you try to connect to a non-existent server, e.g. enter random IPv4 address.

**Game logs**
nothing useful in the log

**To Reproduce**

1. go to new MP game
2. click Join
3. enter random address that doesn't have VCMI server running
4. "failed to connect" dialog appears which is ok

**Expected behavior**
you can close the connection screen

**Actual behavior**
stuck at the connection screen, see SS

**Did it work earlier?**
I think so

**Screenshots**

Image

**Version**

- OS: macOS, iOS
- Version: 42cbfd3e04201c3900ce0b4f98547d56fe2da17c

### PR DESCRIPTION
**Pull request by Laserlicht**
Discover running lobby server in LAN network. To make it easier as you doesn't need to know other device ip address.

Related #991

Fixes #6752

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
at least run clang-format over your changes

**Comment by Laserlicht** [comment]
> at least run clang-format over your changes

Which lines bother you? Then I can fix.

No experience in `clang-tidy`. After short test it outputs thousands of warnings and errors across complete codebase.

**Comment by kambala-decapitator** [comment]
formatting that doesn't follow VCMI styleguide bothers me: incorrect indentation, curly braces in incorrect places, etc.

clang-tidy has nothing to do with this, you need clang-format. The easiest way to use it is to make soft reset of all your changes, then run `git-clang-format`, stage new changes and commit.

**Comment by Laserlicht** [comment]
Ok. Thanks. Formatted.

**Comment by kambala-decapitator** [comment]
but you shouldn't have destroyed the second commit...

**Comment by Laserlicht** [comment]
> but you shouldn't have destroyed the second commit...

Wasn't worth the effort to keep IMO. ;)

**Comment by GeorgeK1ng** [comment]
Maybe show IP in same list as player names instead? Currently first step is to choose player names (not tested but seems like we can do hotseat+lan). And second step would be list of available servers? HD mod have it in similar way.

This is how it looks now
image

**Comment by IvanSavenko** [comment]
As far as UI goes - perhaps check vanilla H3? It actually has such UI from what I remember - start local TCP game, or whatever it is called

**Comment by Laserlicht** [comment]
Yes. I think entire ui for multiplayer would need rework. As it isn't self explaining yet.

But out of scope of this PR. And rather for 1.8 as code needs also some reconception here...

**Comment by Laserlicht** [comment]
And I also think ip list doesn't make sense. Don't think in a lan would be multiple servers.

And over Internet or vpn such discovery stuff isn't working.

**Comment by GeorgeK1ng** [comment]
What if we are running multiple servers in LAN? 

If needed, this can be used for generating "single-line" dialog instead 8.

AssetGenerator::CanvasPtr AssetGenerator::createMultiplayerImage() const
{
    auto locator = ImageLocator(ImagePath::builtin("muhotsea"), EImageBlitMode::OPAQUE);
    std::shared_ptr<IImage> src = ENGINE->renderHandler().loadImage(locator);

    auto out = ENGINE->renderHandler().createImage(Point(363, 196), CanvasScalingPolicy::IGNORE);
    Canvas canvas = out->getCanvas();

    canvas.draw(src, Point(0, 0), Rect(0, 0, 363, 104));
    canvas.draw(src, Point(0, 104), Rect(0, 315, 363, 92));

    return out;
}

**Comment by IvanSavenko** [comment]
H3 already has UI for this without throwing message boxes in your face 
зображення

**Comment by Laserlicht** [comment]
> H3 already has UI for this without throwing message boxes in your face

Nice. But still not think that there are more than one server in network nowadays. LAN parties are not common anymore.

**Comment by IvanSavenko** [comment]
> Nice. But still not think that there are more than one server in network nowadays. LAN parties are not common anymore.

True. But still don't see why we can't use H3 UI and are instead breaking UX by displaying popup when player does NOT expects them

**Comment by Laserlicht** [comment]
grafik

also added IP:
grafik

File: server/ServerDiscoveryListener.h [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+	void stop();
+
+private:
+	void listen();
+	void handle_receive(const boost::system::error_code & error, std::size_t bytes_recvd);
+	CVCMIServer & server;
+	unsigned short port;
+	std::unique_ptr<std::thread> thread;
+	std::atomic<bool> running;
+	boost::asio::io_context ioContext;
```
Comment (IvanSavenko) [inline server/ServerDiscoveryListener.h]: Why you need separate ioContext & thread? Server (and client) already has one, why not reuse it?

Also, our server right now is basically single-threaded, which removes need for any thread sync, which was a pain. Why go back to those times?

Check lib/network for examples on how we use asio, and potentially move this class to lib

File: client/network/ServerDiscovery.cpp [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+
+				std::string message = "VCMI_DISCOVERY";
+				boost::asio::ip::udp::endpoint broadcast_endpoint(boost::asio::ip::address_v4::broadcast(), 3030);
+				socket.send_to(boost::asio::buffer(message), broadcast_endpoint);
+
+				char recv_buf[1024];
+				boost::asio::ip::udp::endpoint sender_endpoint;
+				socket.non_blocking(true);
+				auto start = std::chrono::steady_clock::now();
+				while(std::chrono::steady_clock::now() - start < std::chrono::milliseconds(5000))
```
Comment (IvanSavenko) [inline client/network/ServerDiscovery.cpp]: This will do nothing for up to 5 seconds, potentially blocking other async actions

File: client/network/ServerDiscovery.cpp [hunk 3]
```diff
@@ -0,0 +1,95 @@
...
+				{
+					boost::system::error_code ec;
+					size_t len = socket.receive_from(boost::asio::buffer(recv_buf), sender_endpoint, 0, ec);
```
Comment (IvanSavenko) [inline client/network/ServerDiscovery.cpp]: Again - please use async API of boost::asio, see lib/network code

**Comment by Laserlicht** [comment]
- uses async now
- send broadcasts every seconds now and listening while window is opened (if host opens room later)
- moved everything in lib/network
- show also port number

File: client/mainmenu/CMainMenu.cpp [hunk 4]
```diff
@@ -644,6 +713,13 @@ CSimpleJoinScreen::CSimpleJoinScreen(bool host)
 
 	buttonCancel = std::make_shared<CButton>(Point(142, 142), AnimationPath::builtin("MUBCANC.DEF"), LIBRARY->generaltexth->zelp[561], std::bind(&CSimpleJoinScreen::leaveScreen, this), EShortcut::GLOBAL_CANCEL);
 	statusBar = CGStatusBar::create(std::make_shared<CPicture>(background->getSurface(), Rect(7, 186, 218, 18), 7, 186));
+
+	if(server.length())
```
Comment (IvanSavenko) [inline client/mainmenu/CMainMenu.cpp]:
```suggestion
	if(!server.empty())
```

File: client/mainmenu/CMainMenu.h [hunk 5]
```diff
@@ -98,11 +100,31 @@ class CMultiMode : public WindowBase
 	void joinTCP(EShortcut shortcut);
 
 	/// Get all configured player names. The first name would always be present and initialized to its default value.
-	std::vector<std::string> getPlayersNames();
+	static std::vector<std::string> getPlayersNames();
```
Comment (IvanSavenko) [inline client/mainmenu/CMainMenu.h:103]: Why was this changed?

File: lib/network/NetworkHandler.cpp [hunk 6]
```diff
@@ -96,4 +96,9 @@ void NetworkHandler::stop()
 	context->stop();
 }
 
+NetworkContext & NetworkHandler::getContext()
+{
+	return *context;
+}
+
```
Comment (IvanSavenko) [inline lib/network/NetworkHandler.cpp]: context is internal detail of asio implementation, no need to expose it.

Just add another method like "create network discovery class", similar to rest of network handler api

File: lib/network/NetworkDiscovery.h [hunk 7]
```diff
@@ -0,0 +1,59 @@
...
+	std::function<void(const DiscoveredServer &)> callback;
+	std::shared_ptr<boost::asio::ip::udp::socket> socket;
+	std::shared_ptr<boost::asio::steady_timer> sendTimer;
+	std::set<std::pair<std::string, uint16_t>> discoveredServers;
+};
+
+class DLL_LINKAGE ServerDiscoveryListener
+{
+public:
+	ServerDiscoveryListener(NetworkContext & context, std::function<bool()> isInLobby, std::function<uint16_t()> getPort, unsigned short port = 3030);
```
Comment (IvanSavenko) [inline lib/network/NetworkDiscovery.h]: Instead of callbacks better to use interface with implementation, like rest of our networking API

File: lib/network/NetworkDiscovery.cpp [hunk 8]
```diff
@@ -0,0 +1,203 @@
...
+		if(ec)
+		{
+			logGlobal->error("Discovery send error: %s", ec.message());
+			return;
+		}
+		
+		std::string message = "VCMI_DISCOVERY";
+		boost::asio::ip::udp::endpoint broadcastEndpoint(boost::asio::ip::address_v4::broadcast(), 3030);
+		socket->async_send_to(boost::asio::buffer(message), broadcastEndpoint,
+			[this, sendHandler](const boost::system::error_code& ec, std::size_t)
```
Comment (IvanSavenko) [inline lib/network/NetworkDiscovery.cpp]: What if `this` gets deleted while the callback is pending?
Rest of network API passes this as `self = shared_from_this()` into lambdas to avoid such problem

File: client/mainmenu/CMainMenu.h (hunk 5 above)
Comment (Laserlicht) [reply client/mainmenu/CMainMenu.h:103]: because of re-use in `JoinScreen` class

**Comment by smanolloff** [comment]
There seems to be a hard-coded port `3030` here, which causes a race condition when starting multiple VCMI instances simultaneously (causing port already in use error) -- I noticed this because for ML training I start many VCMI instances at once.
Maybe the idea was to use the `localPort` from [settings.json](https://github.com/vcmi/vcmi/blob/03041199ee4cdcb9c273fbe60b2839b311c76710/config/schemas/settings.json#L585)? 🙄

**Comment by Laserlicht** [comment]
Yes was hardcoded because it IMO doesn't make much sense do change discovery port.

But yes. When opening VCMI multiple times and open multiple times a host game this could happen. But IMO the better idea here is just to check if port can opened (or already in use). If not: Skip discovery server and write into log.
