### PR TITLE
fix infobox position while disabling

### LINKED ISSUE #2480: Disabling Battle queue during battle should reposition hero portrait display.
**Describe the bug**
During battle with battle queue enabled - hero portrait is shown at left/right side correctly.
image

But when we disable Battle queue by pressing Q button, hero portrait doesn't shift and window looks a little odd.
image

**To Reproduce**
1. Provoke any battle.
2. Press Q during battle
3. Observe glitch.

**Expected behavior**
Portrait should fit to battle window with and without battle queue.

**Version**
 - OS: [Windows]
 - Version: [VCMI 1.3]

### PR DESCRIPTION
**Pull request by Laserlicht**
fixes #2480

### CODE REVIEW

File: client/battle/BattleWindow.cpp [hunk 1]
```diff
@@ -130,19 +130,13 @@ void BattleWindow::createStickyHeroInfoWindows()
...
 	}
 	if(owner.attackingHeroInstance)
 	{
 		InfoAboutHero info;
 		info.initFromHero(owner.attackingHeroInstance, InfoAboutHero::EInfoLevel::INBATTLE);
-		Point position = (GH.screenDimensions().x >= 1000)
-				? Point(pos.x - 93, pos.y + 60)
-				: Point(pos.x + 1, pos.y + 195);
-		attackerHeroWindow = std::make_shared<HeroInfoBasicPanel>(info, &position);
+		attackerHeroWindow = std::make_shared<HeroInfoBasicPanel>(info, nullptr);
```
Comment (IvanSavenko) [inline client/battle/BattleWindow.cpp:139]: I think that 2nd parameter from `HeroInfoBasicPanel` constructor can be removed? Or still used somewhere else?

File: client/battle/BattleWindow.cpp [hunk 2]
```diff
@@ -295,25 +325,21 @@ void BattleWindow::updateStackInfoWindow(const CStack * stack)
...
 	else
 		defenderStackWindow = nullptr;
 	
 	if(stack && stack->unitSide() == BattleSide::ATTACKER)
 	{
-		Point position = (GH.screenDimensions().x >= 1000)
-				? Point(pos.x - 93, attackerHeroWindow ? attackerHeroWindow->pos.y + 210 : pos.y)
-				: Point(pos.x + 1, attackerHeroWindow ? attackerHeroWindow->pos.y : pos.y + 135);
-		attackerStackWindow = std::make_shared<StackInfoBasicPanel>(stack, &position);
+		attackerStackWindow = std::make_shared<StackInfoBasicPanel>(stack, nullptr);
```
Comment (IvanSavenko) [inline client/battle/BattleWindow.cpp:336]: Same 2nd parameter here, in `StackInfoBasicPanel`?

File: client/battle/BattleWindow.cpp (hunk 1 above)
Comment (Laserlicht) [reply client/battle/BattleWindow.cpp:139]: This one is used for the right click on hero (if the permanent view disabled).
