### PR TITLE
Fixes incorrect positioning of heroes on spawn/release from prison

### LINKED ISSUE #1192: Visiting hero incorrect placement
If a map is configured to have visiting hero in town it is incorrectly placed 1 tile to the right. This even can be outside of map
[Dragon's Nest (CHI).zip](https://github.com/vcmi/vcmi/files/10148155/Dragon.s.Nest.CHI.zip)

### LINKED ISSUE #1193: Prison hero is incorrectly placed
Hero from prison should appear on visitable offset, prisons type should be BLOCKVIS. Otherwise hero can spawn on the rock or outside the map. Also need to test one tile size prisons from HOTA

### PR DESCRIPTION
**Pull request by IvanSavenko**
Fixes #1193 - adjust position of hero after release from prison
Fixes #1192 - was caused by regression introduced in PR #1075

### CODE REVIEW

File: lib/mapObjects/CObjectHandler.cpp [hunk 1]
```diff
@@ -206,14 +208,23 @@ void CGObjectInstance::setType(si32 ID, si32 subID)
...
 	{
-		//adjust for the prison offset
-		pos = visitablePos();
+		auto newOffset = getVisitableOffset();
+		// FIXME: potentially unused code - setType is NOT called when releasing hero from prison
+		// instead, appearance update & pos adjustment occurs in GiveHero::applyGs
+
+		// adjust position since hero and prison may have different visitable offset
+		pos = pos - oldOffset + newOffset;
 	}
```
Comment (Nordsoft91) [inline lib/mapObjects/CObjectHandler.cpp:228]: this code never will be executed or I'm missing something?
(ID == PRISON) **&&** (ID == HERO)

**Comment by nullkiller** [comment]
Dragons Nest map fails anyway
