### PR TITLE
Fix walk and spellcast targeting

### LINKED ISSUE #6757: `ADJACENT_SPELLCASTER` always considers corpses blocked when casting a spell
**Describe the bug**
`ADJACENT_SPELLCASTER` always considers corpses blocked when casting the spell, so you cannot resurrect corpses with it. There are also some oddities with the cursor shadow - those are just graphical, you can still move anywhere fine.

**Game logs** & **To Reproduce**
No errors or warnings and instead of reproduction steps here is a video.

https://github.com/user-attachments/assets/604616a7-80a4-49aa-b4dd-927f0f8d494a

**Expected behavior** & **Actual behavior**
Timestamps in the video:
0:06 - working as intended
0:15 - how cursor shadow works on units without `ADJACENT_SPELLCASTER`
0:23 - how cursor shadow works on uniths with `ADJACENT_SPELLCASTER`
0:46 - `ADJACENT_SPELLCASTER` with a resurrection clone does not work on corpses. When I just give them `SPELLCASTER`, they'll resurrect.

**Did it work earlier?**
New bonus, so no.

**Version**

- OS: Win7 64bit
- Version: branch-beta-42cbfd3

### PR DESCRIPTION
**Pull request by Opuszek**
Fixes corpse targeting from issue 6757.
I will take a look at the visual problem as well. 
I also changed the action priority, so the default action will be casting a spell on a corpse, not walking on him (just like for an archangel.)

Edit: visual problems solved, fixed #6757.
What has been tested:
Spell can be casted on living units.
Spell can be casted on corpses (resurrection).
Cannot resurrect dead allied units standing on them (both if you want to move there or started a turn on a corpse).
Cannot resurrect dead allied units when an enemy or ally stands on them.
In case of an action not being selected the default action on a corpse it to cast the spell.
In case of a negative spell the default action on enemy it to attack them (spell can be casted when explicitly selected). I think this is desired.

### CODE REVIEW

**Comment by edeksumo** [comment]
Maybe this "issue" will be helpful for factory worms ability?

**Comment by Karyoplasma** [comment]
> Maybe this "issue" will be helpful for factory worms ability?

I was thinking about this, too. But we need some targeting option that specifically only targets corpses for that. I haven't tried fixing that ability yet tho, it was just "lying in bed, unable to sleep" thoughts.

**Comment by Opuszek** [comment]
I don´t think the factory worm ability is doable right now. We lack a bonus that would allow a unit to consume corpses and we lack a way to make bonus disappear after an attack.

**Comment by Karyoplasma** [comment]
Yeah "UNTIL_ATTACK" is wonky and works inconsistently with some bonuses. Maybe it works with additional strikes, maybe it doesn't, who knows?

**Comment by Opuszek** [comment]
You are right, I forgot that "UNTIL_ATTACK" exists.

File: client/battle/BattleFieldController.cpp [hunk 1]
```diff
@@ -368,28 +369,37 @@ BattleHexArray BattleFieldController::getHighlightedHexesForSpellRange()
...
 	{
-		BattleHex fromHex = owner.getBattle()->fromWhichHexAttack(stack, hoveredHex, selectAttackDirection(hoveredHex));
-		if(fromHex.isValid())
-		{
-			if(stack->doubleWide())
-				return {fromHex, stack->occupiedHex(fromHex)};
+		spells::Mode mode = owner.actionsController->getCurrentCastMode();
+		auto * spell = owner.actionsController->getCurrentSpell(hoveredHex);
+		auto * caster = owner.actionsController->getCurrentSpellcaster();
+			if(caster && spell)
```
Comment (IvanSavenko) [inline client/battle/BattleFieldController.cpp]: Formatting is off - move entire if block 1 tab to left

**Review by IvanSavenko — APPROVED** [review]

File: client/battle/BattleFieldController.cpp (hunk 1 above)
Comment (Opuszek) [reply client/battle/BattleFieldController.cpp]: Done
