### PR TITLE
[1.8.0] Show all mod names during downloading multiple mods

### LINKED ISSUE #7211: only 1 mod name is shown in progress bar when downloading
**Describe the bug**
When more than 1 mod is downloaded in a row (e.g. select 2 or more mods in the First Launch screen), then the progress bar shows only one of the mod's names.

**Game logs**
not needed

**To Reproduce**

1. select 2 or more mods in the First Launch screen
2. press Finish (or w/e text has that button)
3. look at the download progress bar

**Expected behavior**
- change displayed mod name to reflect what's currently being downloaded
- show progress in numbers, e.g. "X out of Y downloaded"

**Actual behavior**
only name of one of the mods is shown

**Did it work earlier?**
I don't think so

**Screenshots**

Image

**Version**

- OS: iOS
- Version: 1.7.3 beta @ e1e49200

### PR DESCRIPTION
**Pull request by GeorgeK1ng**
Fixes: https://github.com/vcmi/vcmi/issues/7211

### CODE REVIEW

File: launcher/modManager/cmodlistview_moc.cpp [hunk 1]
```diff
@@ -830,30 +830,48 @@ void CModListView::downloadFile(QString file, QUrl url, QString description, qin
...
 }
 
+void CModListView::onDownloadFileFinished(QString fileName)
+{
+	enqueuedDownloadFiles.removeAll(fileName);
+
+	if(activeDownloadFile == fileName)
+		activeDownloadFile = enqueuedDownloadFiles.empty() ? QString() : enqueuedDownloadFiles.front();
+}
+
```
Comment (IvanSavenko) [inline launcher/modManager/cmodlistview_moc.cpp:874]: Instead of this complex logic - why not make `onDownloadFileStarted` signal and pass new filename in it? In this way you won't have need to track file queue

Comment (GeorgeK1ng) [reply launcher/modManager/cmodlistview_moc.cpp:874]: I have tried to achieve it, but without success. My solution is more workaround, because it looks like all mods in queue are downloaded simultaneously. Which means, showed progress is not real one. Will investigate it more.

Comment (IvanSavenko) [reply launcher/modManager/cmodlistview_moc.cpp:874]: Then instead of faking we should show something like "Downloading N mods" instead of displaying single mod name

Comment (GeorgeK1ng) [reply launcher/modManager/cmodlistview_moc.cpp:874]: What about turning download mechanism into real queue?

Comment (IvanSavenko) [reply launcher/modManager/cmodlistview_moc.cpp:874]: Anything wrong with current approach? It definitely works and haven't seen any bug reports regarding it. Sure, we could make real download queue, but don't see how it would improve anything.

Comment (GeorgeK1ng) [reply launcher/modManager/cmodlistview_moc.cpp:874]: Turned downloads into real queue, now are multidownloads mod names correctly showed one by one without faking.

Tested in first launch and works as expected. Will test also multi mods updating little bit later today.

Comment (IvanSavenko) [reply launcher/modManager/cmodlistview_moc.cpp:874]: Postponing to 1.8 then. Don't want to accept changes for a minor issue that may have unexpected changes for everyone in beta.

Comment (GeorgeK1ng) [reply launcher/modManager/cmodlistview_moc.cpp:874]: Of course, this is more like enhancement.
