### PR TITLE
[Mapeditor] Fix crash when clicking on random artifacts

### LINKED ISSUE #6892: [Map Editor] Crash when clicking on random artifacts
**Describe the bug**
like this:

Image

**Version**

- OS: Windows
- Version: 1.7.2

### PR DESCRIPTION
**Pull request by MichalZr6**
- fixes #6892

### CODE REVIEW

File: mapeditor/inspector/inspector.cpp [hunk 1]
```diff
@@ -380,6 +380,10 @@ void Inspector::updateProperties(CGArtifact * o)
 
 	addProperty(QObject::tr("Message"), o->message, false);
 
+	// Random artifacts
+	if(o->ID > Obj::ARTIFACT)
+		return;
+
```
Comment (IvanSavenko) [inline mapeditor/inspector/inspector.cpp]: Please use whitelist or blacklist, not range check:
a) `if (o->ID == random artifact ID) return`
b) `if (o->ID != predefined artifact ID) return`

Comment (MichalZr6) [reply mapeditor/inspector/inspector.cpp]: Yes, initially I had it like that:
```cpp
if(o->ID == Obj::RANDOM_ART
	|| o->ID == Obj::RANDOM_TREASURE_ART
	|| o->ID == Obj::RANDOM_MINOR_ART
	|| o->ID == Obj::RANDOM_MAJOR_ART
	|| o->ID == Obj::RANDOM_RELIC_ART)
{
	return;
}
```
but wanted to shorten this a bit.
What about adding a helper:
```cpp
bool MapObjectID::isRandomArtifact(MapObjectID id) const;
```

It could be used for another range check that already exists in `Initializer`'s code:
```cpp
	else if(o->ID == Obj::ARTIFACT || (o->ID >= Obj::RANDOM_ART && o->ID <= Obj::RANDOM_RELIC_ART))
```

Comment (IvanSavenko) [reply mapeditor/inspector/inspector.cpp]: Sounds good

Comment (MichalZr6) [reply mapeditor/inspector/inspector.cpp]: Done
