### PR TITLE
fix displaying growth bonus from Statue of Legion

### LINKED ISSUE #1410: Statue of Legion growth display issue
should be +50 **%**, but even better is to display flat value, which would be (1+1) * 50% = 1 in this case

Screenshot 2023-01-11 at 04 49 57

### PR DESCRIPTION
**Pull request by kambala-decapitator**
fixes #1410

test map: [legion-statue.h3m.zip](https://github.com/vcmi/vcmi/files/10472174/legion-statue.h3m.zip)

Screenshot 2023-01-21 at 15 30 20

### CODE REVIEW

**Comment by dydzio0614** [comment]
Maybe it would be decent idea to handle special case for bonus stringifying so you can provide custom value parameter, and if bonus is of percent type, it will process the value rather than using percent as value?

**Comment by kambala-decapitator** [comment]
> Maybe it would be decent idea to handle special case in Description() for bonus stringifying so you can provide custom value parameter, and if bonus is of percent type, it will process the value and use that, rather than using percent as value?

to be honest I don't understand your proposal... could you open a separate issue for improvement?

**Comment by dydzio0614** [comment]
Maybe, but I dont see it as any sort of priority

**Review by dydzio0614 — APPROVED** [review]

**Comment by nullkiller** [comment]
In your example it does not count this external dwelling +2 when taking 50%?

**Comment by kambala-decapitator** [comment]
> In your example it does not count this external dwelling +2 when taking 50%?

yes, this is correct behavior. Also checked in oh3.

File: lib/mapObjects/CGTownInstance.cpp [hunk 1]
```diff
@@ -570,7 +570,13 @@ GrowthInfo CGTownInstance::getGrowthInfo(int level) const
 	//statue-of-legion-like bonus: % to base+castle
 	TConstBonusListPtr bonuses2 = getBonuses(Selector::type()(Bonus::CREATURE_GROWTH_PERCENT));
 	for(const auto & b : *bonuses2)
-		ret.entries.push_back(GrowthInfo::Entry(b->val * (base + castleBonus) / 100, b->Description()));
+	{
+		// TODO: needs a better way to create string instead of this hack
+		const auto bonusValue = b->val;
```
Comment (nullkiller) [inline lib/mapObjects/CGTownInstance.cpp:575]: I suggest to at least make a copy of bonus just in case. Modifing const reference of such a shared thing like a bonus might yield some parallelism issues

**Comment by kambala-decapitator** [comment]
> Maybe it would be decent idea to handle special case in Description() for bonus stringifying so you can provide custom value parameter, and if bonus is of percent type, it will process the value and use that, rather than using percent as value?

now I got it :)

File: lib/mapObjects/CGTownInstance.cpp (hunk 1 above)
Comment (nullkiller) [reply lib/mapObjects/CGTownInstance.cpp:575]: @dydzio0614 suggests to modify b->Description() to handle this case internally. What if we introduce just another overload Description(int bonusValue) which will ignore original bonus value?

Comment (nullkiller) [reply lib/mapObjects/CGTownInstance.cpp:575]: Or make a copy of bonus and modify value there so it is less reusable

Comment (kambala-decapitator) [reply lib/mapObjects/CGTownInstance.cpp]: implemented per @dydzio0614 suggestion

**Comment by dydzio0614** [comment]
I wonder if renaming argument to boost::optional<si32> flatValueHint and using it if bonus value type is PERCENT_TO_ALL or PERCENT_TO_BASE would be better - and in this case result would be flatValueHint * val / 100

**Comment by kambala-decapitator** [comment]
> I wonder if renaming new Description() argument to boost::optional flatValueHint and using it if bonus value type is PERCENT_TO_ALL or PERCENT_TO_BASE would be better - and in this case result would be flatValueHint * val / 100, without percent calculation by caller

caller still needs to provide proper value to `GrowthInfo::Entry` constructor, as `GrowthInfo::totalGrowth()` uses it. Does it make sense for `Bonus` to provide computed values? Anyway, IMO such refactoring task is for 1.2.

**Comment by DjWarmonger** [comment]
Shouldn't Status of Legion line be displayed **above** external dwellings? After all the Statue does not multiply the amount coming from dwellings, only base + castle growth.

While Grail does multiply the total amount generated by all other bonuses.

**Comment by kambala-decapitator** [comment]
should I also adjust strings order in this PR? This is how it looks in oh3:
Screenshot 2023-01-23 at 14 46 03 Screenshot 2023-01-23 at 14 46 06

**Comment by kambala-decapitator** [comment]
fixed order:
Screenshot 2023-01-24 at 19 42 47 Screenshot 2023-01-24 at 19 42 48

line break is there because original dwelling string has it

**Review by IvanSavenko — APPROVED** [review]
Perhaps we should either trim strings from excessive line endings?
Still, looks to be an improvement either way.
