### PR TITLE
Map editor town configuration improvements (buildings, spells, events)

### LINKED ISSUE #3631: Automatically check/uncheck previous/next building in Building Dialog in Map Editor
**Describe your proposal**
In Town Building Dialog,  in Map Editor,
- When you **check** the Magic Guild Level 3 as built, it should **check** also Magic Guild Level 1 and Magic Guild Level 2.
- When you **uncheck** the Magic Guild Level 3 as built, it should **uncheck** also Magic Guild Level 5 and Magic Guild Level 4.
- When you check the Magic Guild Level 3 as **buildable**, it should check also as buildable Magic Guild Level 1 and Magic Guild Level 2.
- When you uncheck the Magic Guild Level 3 as **buildable**, it should uncheck also as buildable Magic Guild Level 5 and Magic Guild Level 4.

**How to reproduce**

1. Open _Map Editor_
2. Add a town
3. Go on _Inspector_
4. Click on _Building..._

### PR DESCRIPTION
**Pull request by godric3**
~Started some time ago, I want to add town events before merging. PR created for visibility(and maybe better motivation to finish...)~
Improvements for town customization to have same possibilities as original editor. Unfortunately quite a lot of code duplication from map events and other town widgets as they have almost the same content
- [x]  auto update base/upgrade building fixes #3631 :
  - if building is built it have to be enabled
  - if building is built/enabled base building must be built/enabled
  - if building is disabled it cannot be build
  - if building is disabled/unbuilt upgrade building must be disabled/unbuilt
- [x]  build/demolish/enable/disable all building option
- [x] set town spells (possible and required) part of #4222
- [x] set town timed events part of #4222 
- [x] translations

image

image

image

### CODE REVIEW

File: lib/mapObjects/CGTownInstance.cpp [hunk 1]
```diff
@@ -1206,6 +1206,22 @@ void CGTownInstance::serializeJsonOptions(JsonSerializeFormat & handler)
...
+			eventsHandler.serializeStruct(temp);
+		}
+		else
+		{
+			auto eventsHandler = handler.enterArray("events");
+			std::vector<CCastleEvent> temp;
+			eventsHandler.serializeStruct(temp);
+			events.clear();
+			events.insert(events.begin(), temp.begin(), temp.end());
+		}
```
Comment (IvanSavenko) [inline lib/mapObjects/CGTownInstance.cpp:1223]: Completely untested, but will something like this work?

```suggestion
	{
		auto eventsHandler = handler.enterArray("customSize");
		eventsHandler.syncSize(events, JsonNode::JsonType::DATA_VECTOR);
		eventsHandler.serializeStruct(events);
	}
```

File: mapeditor/inspector/townevent.cpp [hunk 2]
```diff
@@ -0,0 +1,320 @@
...
+	auto resourcesMap = params.value("resources").toMap();
+	for (int i = 0; i < GameConstants::RESOURCE_QUANTITY; ++i)
+	{
+		auto name = QString::fromStdString(GameConstants::RESOURCE_NAMES[i]);
+		int val = resourcesMap.value(name).toInt();
+		ui->resourcesTable->setItem(i, 0, new QTableWidgetItem(name));
+
+		QSpinBox * edit = new QSpinBox(ui->resourcesTable);
+		edit->setMaximum(i == GameResID::GOLD ? 999999 : 999);
+		edit->setMinimum(i == GameResID::GOLD ? -999999 : -999);
```
Comment (IvanSavenko) [inline mapeditor/inspector/townevent.cpp:76]: Why limit to 999?

File: mapeditor/inspector/townevent.cpp [hunk 3]
```diff
@@ -0,0 +1,320 @@
...
+}
+
+void TownEvent::setRowColumnCheckState(QStandardItem * item, int column, Qt::CheckState checkState) {
+	auto sibling = item->model()->sibling(item->row(), column, item->index());
+	buildingsModel.itemFromIndex(sibling)->setCheckState(checkState);
+}
+
+void TownEvent::onItemChanged(QStandardItem * item)
+{
+	disconnect(&buildingsModel, &QStandardItemModel::itemChanged, this, &TownEvent::onItemChanged);
```
Comment (IvanSavenko) [inline mapeditor/inspector/townevent.cpp:294]: I think you might want to use QSignalBlocker class here instead

File: mapeditor/inspector/townspellswidget.cpp [hunk 4]
```diff
@@ -0,0 +1,172 @@
...
+
+void TownSpellsWidget::resetSpells()
+{
+	town.possibleSpells.clear();
+	town.obligatorySpells.clear();
+	for (auto spell : VLC->spellh->objects)
+	{
+		if (!spell->isSpecial() && !spell->isCreatureAbility())
+			town.possibleSpells.push_back(spell->id);
+	}
```
Comment (IvanSavenko) [inline mapeditor/inspector/townspellswidget.cpp:57]:
```suggestion
	for (auto spellID : VLC->spellh->getDefaultAllowed())
		town.possibleSpells.push_back(spellID);
```

File: mapeditor/inspector/townspellswidget.cpp [hunk 5]
```diff
@@ -0,0 +1,172 @@
...
+}
+
+void TownSpellsWidget::initSpellLists()
+{
+	QListWidget * possibleSpellLists[] = { ui->possibleSpellList1, ui->possibleSpellList2, ui->possibleSpellList3, ui->possibleSpellList4, ui->possibleSpellList5 };
+	QListWidget * requiredSpellLists[] = { ui->requiredSpellList1, ui->requiredSpellList2, ui->requiredSpellList3, ui->requiredSpellList4, ui->requiredSpellList5 };
+	auto spells = VLC->spellh->objects;
```
Comment (IvanSavenko) [inline mapeditor/inspector/townspellswidget.cpp:64]: `VLC->spellh->getDefaultAllowed()` is preferred to direct access to `objects` field.

And to convert SpellID to Spell you can use (preferred) `spellID.toEntity(VLC)` or `spellID.toSpell()` (if you need info not present in entity)

File: lib/mapObjects/CGTownInstance.cpp (hunk 1 above)
Comment (godric3) [reply lib/mapObjects/CGTownInstance.cpp:1223]:
```
 no instance of overloaded function matches the argument list
argument types are: (std::list<CCastleEvent, std::allocator<CCastleEvent>>) 
object type is: JsonArraySerializer
 ```
 
 events are list, and serializeStruct expect vector

File: mapeditor/inspector/townevent.cpp (hunk 2 above)
Comment (godric3) [reply mapeditor/inspector/townevent.cpp:76]: couldn't find any RESOURCE_LIMIT const so I used some numbers that other rewards widget is using

File: lib/mapObjects/CGTownInstance.cpp (hunk 1 above)
Comment (IvanSavenko) [reply lib/mapObjects/CGTownInstance.cpp:1223]: Personally I would change list to vector.
Performance hit likely would be negligible (or even would have an improvement)

File: mapeditor/inspector/townevent.cpp (hunk 3 above)
Comment (godric3) [reply mapeditor/inspector/townevent.cpp:294]: tried and works, but have side effect of not updating checkboxes until user hovers over them or move mouse outside of buildings treeview, so I guess I will live it as is. A little bit uglier code for better user experience

**Review by IvanSavenko — APPROVED** [review]
Looks OK for me.
@kambala-decapitator anything to add?

**Comment by kambala-decapitator** [comment]
will have a look today or tomorrow

File: mapeditor/inspector/townevent.h [hunk 6]
```diff
@@ -0,0 +1,53 @@
...
+
+#include "../StdInc.h"
+#include <QDialog>
+#include "../lib/mapObjects/CGTownInstance.h"
+
+namespace Ui {
+	class TownEvent;
+}
+
+class TownEvent : public QDialog
```
Comment (kambala-decapitator) [inline mapeditor/inspector/townevent.h:20]: TownEventDialog

File: mapeditor/inspector/towneventswidget.h [hunk 7]
```diff
@@ -0,0 +1,59 @@
...
+	TownEventsDelegate(CGTownInstance &, MapController &);
+
+	QWidget* createEditor(QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const override;
+	void setEditorData(QWidget * editor, const QModelIndex & index) const override;
+	void setModelData(QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const override;
+
+private:
+	CGTownInstance & town;
+	MapController & controller;
+};
```
Comment (kambala-decapitator) [inline mapeditor/inspector/towneventswidget.h:59]: please add empty line at EOF

File: mapeditor/inspector/towneventswidget.cpp [hunk 8]
```diff
@@ -0,0 +1,179 @@
...
+	result.creatures = creaturesFromVariant(v.value("creatures"));
+	return result;
+}
+
+void TownEventsWidget::obtainData()
+{
+	for (const auto & event : town.events)
+	{
+		auto eventName = QString::fromStdString(event.name);
+		auto itemText = QString::fromStdString("Day %1 - %2").arg(event.firstOccurrence+1, 3).arg(eventName);
```
Comment (kambala-decapitator) [inline mapeditor/inspector/towneventswidget.cpp]: `QString{"Day %1 - %2"}.arg...`

File: mapeditor/inspector/towneventswidget.cpp [hunk 9]
```diff
@@ -0,0 +1,179 @@
...
+
+void TownEventsWidget::on_timedEventRemove_clicked()
+{
+	if (auto* item = ui->eventsList->currentItem())
+		ui->eventsList->takeItem(ui->eventsList->row(item));
+}
+
+void TownEventsWidget::on_eventsList_itemActivated(QListWidgetItem* item)
+{
+	new TownEvent(town, item, parentWidget());
```
Comment (kambala-decapitator) [inline mapeditor/inspector/towneventswidget.cpp:141]: is it supposed to show modal dialog?

File: mapeditor/inspector/towneventswidget.cpp [hunk 10]
```diff
@@ -0,0 +1,179 @@
...
+}
+
+void TownEventsWidget::onItemChanged(QStandardItem * item)
+{
+}
```
Comment (kambala-decapitator) [inline mapeditor/inspector/towneventswidget.cpp:146]: what is this for?

File: mapeditor/inspector/towneventswidget.cpp [hunk 11]
```diff
@@ -0,0 +1,179 @@
...
+	auto* item = new QListWidgetItem(QString::fromStdString(event.name));
+	item->setData(Qt::UserRole, toVariant(event));
+	ui->eventsList->addItem(item);
+	on_eventsList_itemActivated(item);
+}
+
+void TownEventsWidget::on_timedEventRemove_clicked()
+{
+	if (auto* item = ui->eventsList->currentItem())
+		ui->eventsList->takeItem(ui->eventsList->row(item));
```
Comment (kambala-decapitator) [inline mapeditor/inspector/towneventswidget.cpp:136]: `delete ui->eventsList->takeItem(ui->eventsList->currentRow());`

File: mapeditor/inspector/townevent.h [hunk 12]
```diff
@@ -0,0 +1,53 @@
...
+	QVariantList creaturesToVariant();
+
+	QStandardItem * addBuilding(const CTown & ctown, BuildingID bId, std::set<si32> & remaining);
+
+	Ui::TownEvent * ui;
+	CGTownInstance & town;
+	QListWidgetItem * item;
+	QMap<QString, QVariant> params;
+	mutable QStandardItemModel buildingsModel;
+};
```
Comment (kambala-decapitator) [inline mapeditor/inspector/townevent.h:53]: please add empty line at EOF

File: mapeditor/inspector/townevent.cpp [hunk 13]
```diff
@@ -0,0 +1,320 @@
...
+	ui->eventAffectsHuman->setChecked(params.value("humanAffected").toBool());
+	ui->eventFirstOccurrence->setValue(params.value("firstOccurrence").toInt()+1);
+	ui->eventRepeatAfter->setValue(params.value("nextOccurrence").toInt());
+
+	initPlayers();
+	initResources();
+	initBuildings();
+	initCreatures();
+
+	show();
```
Comment (kambala-decapitator) [inline mapeditor/inspector/townevent.cpp:44]: this is a wrong approach to work with windows, the calling code is responsible to call show/exec

File: mapeditor/inspector/townevent.cpp [hunk 14]
```diff
@@ -0,0 +1,320 @@
...
+
+	params = item->data(Qt::UserRole).toMap();
+	ui->eventFirstOccurrence->setMinimum(1);
+	ui->eventFirstOccurrence->setMaximum(999);
+	ui->eventRepeatAfter->setMaximum(999);
+	ui->eventNameText->setText(params.value("name").toString());
+	ui->eventMessageText->setPlainText(params.value("message").toString());
+	ui->eventAffectsCpu->setChecked(params.value("computerAffected").toBool());
+	ui->eventAffectsHuman->setChecked(params.value("humanAffected").toBool());
+	ui->eventFirstOccurrence->setValue(params.value("firstOccurrence").toInt()+1);
```
Comment (kambala-decapitator) [inline mapeditor/inspector/townevent.cpp:36]: why do you need to use +/- 1? can't you save as is?

File: mapeditor/inspector/townevent.cpp [hunk 15]
```diff
@@ -0,0 +1,320 @@
...
+TownEvent::~TownEvent()
+{
+	delete ui;
+}
+
+void TownEvent::initPlayers()
+{
+	for (int i = 0; i < PlayerColor::PLAYER_LIMIT_I; ++i)
+	{
+		bool isAffected = (1 << i) & params.value("players").toInt();
```
Comment (kambala-decapitator) [inline mapeditor/inspector/townevent.cpp:56]: what is this bit magic? can't you store an array?

File: mapeditor/inspector/townevent.cpp [hunk 16]
```diff
@@ -0,0 +1,320 @@
...
+	item(item)
+{
+	ui->setupUi(this);
+
+	ui->buildingsTree->setModel(&buildingsModel);
+
+	params = item->data(Qt::UserRole).toMap();
+	ui->eventFirstOccurrence->setMinimum(1);
+	ui->eventFirstOccurrence->setMaximum(999);
+	ui->eventRepeatAfter->setMaximum(999);
```
Comment (kambala-decapitator) [inline mapeditor/inspector/townevent.cpp:31]: magic numbers should be named constants

File: mapeditor/inspector/townevent.cpp (hunk 2 above)
Comment (kambala-decapitator) [reply mapeditor/inspector/townevent.cpp:76]: magic numbers should be named constants

File: mapeditor/inspector/townevent.cpp [hunk 17]
```diff
@@ -0,0 +1,320 @@
...
+	}
+}
+
+void TownEvent::initBuildings()
+{
+	auto * ctown = town.town;
+	if (!ctown)
+		ctown = VLC->townh->randomTown;
+	if (!ctown)
+		throw std::runtime_error("No Town defined for type selected");
```
Comment (kambala-decapitator) [inline mapeditor/inspector/townevent.cpp:90]: do you really want to crash editor? Haven't seen exception handling where dialog is created

File: mapeditor/inspector/townevent.cpp [hunk 18]
```diff
@@ -0,0 +1,320 @@
...
+{
+	auto bId = buildingId.num;
+	const CBuilding * building = ctown.buildings.at(buildingId);
+	if (!building)
+	{
+		remaining.erase(bId);
+		return nullptr;
+	}
+
+	QString name = tr(building->getNameTranslated().c_str());
```
Comment (kambala-decapitator) [inline mapeditor/inspector/townevent.cpp:111]: `tr` doesn't work with runtime strings

File: mapeditor/inspector/townevent.cpp [hunk 19]
```diff
@@ -0,0 +1,320 @@
...
+				QModelIndex index = buildingsModel.index(i, 0, pindex);
+				if (building->upgrade.getNum() == buildingsModel.itemFromIndex(index)->data(Qt::UserRole).toInt())
+				{
+					parent = buildingsModel.itemFromIndex(index);
+					break;
+				}
+				if (buildingsModel.hasChildren(index))
+					stack.push_back(index);
+			}
+		}
```
Comment (kambala-decapitator) [inline mapeditor/inspector/townevent.cpp:150]: looks quite similar to the other place, can you extract it to a function?

File: mapeditor/inspector/townevent.cpp [hunk 20]
```diff
@@ -0,0 +1,320 @@
...
+
+	remaining.erase(bId);
+	return checks.front();
+}
+
+void TownEvent::initCreatures()
+{
+	auto creatures = params.value("creatures").toList();
+	auto * ctown = town.town;
+	for (int i = 0; i < 7; ++i)
```
Comment (kambala-decapitator) [inline mapeditor/inspector/townevent.cpp:172]: magic number

File: mapeditor/inspector/townevent.cpp [hunk 21]
```diff
@@ -0,0 +1,320 @@
...
+	{
+		QString creatureNames;
+		if (!ctown)
+		{
+			creatureNames.append(QString("Creature %1 / Creature %1 Upgrade").arg(i + 1));
```
Comment (kambala-decapitator) [inline mapeditor/inspector/townevent.cpp]: why don't you want to make this string translatable?

File: mapeditor/inspector/townevent.cpp [hunk 22]
```diff
@@ -0,0 +1,320 @@
...
+				auto creatureName = QString::fromStdString(cre->getNameSingularTranslated());
+				creatureNames.append(creatureNames.isEmpty() ? creatureName : " / " + creatureName);
+			}
+		}
+		auto * item = new QTableWidgetItem();
+		item->setFlags(item->flags() & ~Qt::ItemIsEditable);
+		item->setText(creatureNames);
+		ui->creaturesTable->setItem(i, 0, item);
+
+		auto creatureNumber = creatures.size() > i ? creatures.at(i).toInt() : 0;
```
Comment (kambala-decapitator) [inline mapeditor/inspector/townevent.cpp:194]: does it make sense to add spinbox in the false case?

File: mapeditor/inspector/townevent.cpp [hunk 23]
```diff
@@ -0,0 +1,320 @@
...
+		QSpinBox* edit = new QSpinBox(ui->creaturesTable);
+		edit->setValue(creatureNumber);
+		edit->setMaximum(999999);
```
Comment (kambala-decapitator) [inline mapeditor/inspector/townevent.cpp:197]: same magic number as above

Comment (kambala-decapitator) [inline mapeditor/inspector/townevent.cpp:197]: same magic number as above

File: lib/gameState/CGameState.cpp [hunk 24]
```diff
@@ -904,7 +904,7 @@ void CGameState::initTowns()
 		}
 		//init spells
 		vti->spells.resize(GameConstants::SPELL_LEVELS);
-
+		vti->possibleSpells -= SpellID::PRESET;
```
[the remark this answers is not in the document]
Comment (IvanSavenko) [reply lib/gameState/CGameState.cpp:907]: It is not harmful, but not sure how SpellID::PRESET can even appear in towns.
It is used to indicate starting spells of a hero.

**Review by kambala-decapitator — CHANGES_REQUESTED** [review]
please avoid creating such huge PRs that contain separate unrelated changes

File: lib/gameState/CGameState.cpp (hunk 24 above)
[the remark this answers is not in the document]
Comment (kambala-decapitator) [reply lib/gameState/CGameState.cpp:907]: I saw that editor uses it as some kind of placeholder, probably related to that

[the remark this answers is not in the document]
Comment (godric3) [reply lib/gameState/CGameState.cpp:907]: Yes, I used it also for marking that town possible spells had been customized, so editor can detect that, otherwise I would have to compare town possible spells with allowed spells for differences to know if spells were customized. 
May create separate const specific for towns if that one was meant bo be hero only

File: mapeditor/inspector/towneventswidget.cpp (hunk 9 above)
Comment (godric3) [reply mapeditor/inspector/towneventswidget.cpp:141]: Yes

File: lib/gameState/CGameState.cpp (hunk 24 above)
[the remark this answers is not in the document]
Comment (IvanSavenko) [reply lib/gameState/CGameState.cpp:907]: Should be fine. At the moment it is only used for heroes, but using it for towns if needed should also be fine.

Personally I don't like this approach with fake spells, but don't see any clean solution either. And it is not like this weird approach was introduced in this PR.

File: mapeditor/inspector/townevent.cpp (hunk 15 above)
Comment (godric3) [reply mapeditor/inspector/townevent.cpp:56]: Code copied from timedevent.cpp, looks like players in events are stored in bit field
https://github.com/vcmi/vcmi/blob/3c611ffa5b76686156d89aded68e87fc4e34c2b6/lib/mapping/CMapDefines.h#L39

Comment (IvanSavenko) [reply mapeditor/inspector/townevent.cpp:56]: Might be a good idea to replace with std::set<PlayerColor>, but not insisting.

File: mapeditor/inspector/townevent.cpp (hunk 17 above)
Comment (godric3) [reply mapeditor/inspector/townevent.cpp:90]: don't really see this triggering without corrupted townh, but anyway I used same approach as in townbuildingswidget

File: mapeditor/inspector/townevent.cpp (hunk 21 above)
Comment (godric3) [reply mapeditor/inspector/townevent.cpp]: Already changed, somehow you reviewed older commit?

File: mapeditor/inspector/towneventswidget.cpp (hunk 9 above)
Comment (kambala-decapitator) [reply mapeditor/inspector/towneventswidget.cpp:141]: then the right way is:
```cpp
TownEventDialog dlg{town, item, parentWidget()};
dlg.exec();
```

and drop that `show()` from constructor

File: mapeditor/inspector/townevent.cpp (hunk 15 above)
Comment (kambala-decapitator) [reply mapeditor/inspector/townevent.cpp:56]: ah, since it's coming not from editor settings, then it's fine of course

File: mapeditor/inspector/townevent.cpp (hunk 21 above)
Comment (kambala-decapitator) [reply mapeditor/inspector/townevent.cpp]: yeah, was looking commit by commit because it's easier to understand separate changes like that, not all changes at once

File: mapeditor/inspector/townevent.cpp (hunk 14 above)
Comment (godric3) [reply mapeditor/inspector/townevent.cpp:36]: To show user 1 based day numbering, not 0 based as in code, probably could be done better...

File: mapeditor/inspector/towneventswidget.cpp (hunk 10 above)
Comment (godric3) [reply mapeditor/inspector/towneventswidget.cpp:146]: leftover, will delete

File: mapeditor/inspector/townevent.cpp (hunk 14 above)
Comment (kambala-decapitator) [reply mapeditor/inspector/townevent.cpp:36]: are these params read/written from/to map object? Probably I missed that, then it's fine to apply +- 1 for UI. I thought that's some kind of editor-only data.

File: mapeditor/inspector/townevent.h [hunk 25]
```diff
@@ -0,0 +1,53 @@
...
+	QVariantList buildingsToVariant();
+	QVariantList creaturesToVariant();
+
+	QStandardItem * addBuilding(const CTown & ctown, BuildingID bId, std::set<si32> & remaining);
+
+	Ui::TownEvent * ui;
+	CGTownInstance & town;
+	QListWidgetItem * item;
+	QMap<QString, QVariant> params;
+	mutable QStandardItemModel buildingsModel;
```
Comment (kambala-decapitator) [inline mapeditor/inspector/townevent.h:52]: why is it marked as mutable?

File: mapeditor/inspector/townevent.h [hunk 26]
```diff
@@ -0,0 +1,53 @@
...
+	QVariant playersToVariant();
+	QVariantMap resourcesToVariant();
+	QVariantList buildingsToVariant();
+	QVariantList creaturesToVariant();
+
+	QStandardItem * addBuilding(const CTown & ctown, BuildingID bId, std::set<si32> & remaining);
+
+	Ui::TownEvent * ui;
+	CGTownInstance & town;
+	QListWidgetItem * item;
```
Comment (kambala-decapitator) [inline mapeditor/inspector/townevent.h:50]: please give the variable a better name to make it clear what kind of item it is

**Comment by godric3** [comment]
ok, pipelines are finally happy, ready to review

File: mapeditor/inspector/townspellswidget.cpp [hunk 27]
```diff
@@ -0,0 +1,175 @@
...
+{
+	if (auto * ed = qobject_cast<TownSpellsWidget *>(editor))
+	{
+		ed->commitChanges();
+	}
+	else
+	{
+		QStyledItemDelegate::setModelData(editor, model, index);
+	}
+}
```
Comment (kambala-decapitator) [inline mapeditor/inspector/townspellswidget.cpp:175]: please add line break at EOF

File: mapeditor/mapeditorroles.h [hunk 28]
```diff
@@ -0,0 +1,20 @@
...
+#pragma once
+
+#include "StdInc.h"
+
+enum MapEditorRoles
+{
+    TownEventRole = Qt::UserRole +1,
+    PlayerIDRole,
+    BuildingIDRole,
+	SpellIDRole
```
Comment (kambala-decapitator) [inline mapeditor/mapeditorroles.h:19]: something's wrong with indentation

File: mapeditor/mapeditorroles.h [hunk 29]
```diff
@@ -0,0 +1,20 @@
...
+ * Full text of license available in license.txt file, in main folder
+ *
+ */
+#pragma once
+
+#include "StdInc.h"
+
+enum MapEditorRoles
+{
+    TownEventRole = Qt::UserRole +1,
```
Comment (kambala-decapitator) [inline mapeditor/mapeditorroles.h:16]:
```suggestion
    TownEventRole = Qt::UserRole + 1,
```

File: mapeditor/inspector/townbuildingswidget.cpp [hunk 30]
```diff
@@ -68,6 +69,56 @@ std::string defaultBuildingIdConversion(BuildingID bId)
...
+			if (model.hasChildren(index))
+				stack.push_back(index);
+		}
+	}
+	return parent;
+}
+
+std::list<QVariant> getBuildingVariantsFromModel(QStandardItemModel & model, int modelColumn, Qt::CheckState checkState)
+{
+	std::list<QVariant> result;
```
[the remark this answers is not in the document]
Comment (godric3) [reply mapeditor/inspector/townbuildingswidget.cpp:98]: list is just for easier creation of QVariantList, and QVariant is because of the same reason. QVariantList is then saved into QVariantMap that is stored as townEventListItem data

**Comment by IvanSavenko** [comment]
And by the way - take a look at stuff found by SonarCloud in this PR:
https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&sinceLeakPeriod=true&pullRequest=4225&id=vcmi_vcmi

Not asking you to fix everything from it, just items that you agree with and makes sense to fix.

File: mapeditor/inspector/townbuildingswidget.cpp (hunk 30 above)
[the remark this answers is not in the document]
Comment (kambala-decapitator) [reply mapeditor/inspector/townbuildingswidget.cpp:98]: - QVariantList is **not** `std::list` under the hood
- you can create it from any container that has begin/end

use vector if you don't need special behavior of some other container

[the remark this answers is not in the document]
Comment (godric3) [reply mapeditor/inspector/townbuildingswidget.cpp:98]: I know it's not std::list but it have convenient api for conversion from it. I had problems with using set (and I think the same with vector) for construction of QVaraintList. I already cleaned git history but I may double check that in the evening

[the remark this answers is not in the document]
Comment (kambala-decapitator) [reply mapeditor/inspector/townbuildingswidget.cpp:98]: this should work:
```cpp
std::vector<QVariant> vec;
QVariantList list{vec.cbegin(), vec.cend()};
```

[the remark this answers is not in the document]
Comment (godric3) [reply mapeditor/inspector/townbuildingswidget.cpp:98]: even before qt 5.14?

[the remark this answers is not in the document]
Comment (IvanSavenko) [reply mapeditor/inspector/townbuildingswidget.cpp:98]: Why not simply use QVariantList? Mixing std and Qt containers is a bit weird approach IMO

[the remark this answers is not in the document]
Comment (godric3) [reply mapeditor/inspector/townbuildingswidget.cpp:98]: Perhaps that will be better solution, will check it

File: mapeditor/inspector/towneventdialog.cpp [hunk 31]
```diff
@@ -0,0 +1,299 @@
...
+	ui->buildingsTree->resizeColumnToContents(0);
+
+	connect(&buildingsModel, &QStandardItemModel::itemChanged, this, &TownEventDialog::onItemChanged);
+}
+
+QStandardItem * TownEventDialog::addBuilding(const CTown& ctown, BuildingID buildingId, std::set<si32>& remaining)
+{
+	auto bId = buildingId.num;
+	const CBuilding * building = ctown.buildings.at(buildingId);
+	if (!building)
```
[the remark this answers is not in the document]
Comment (godric3) [reply mapeditor/inspector/towneventdialog.cpp:113]: `buildingId` here may come only from two places
1.  element from `ctown->getAllBuildings()`
2.  `building->upgrade`

So it looks like `at` will always return valid pointer, will remove null checks

**Comment by IvanSavenko** [comment]
@kambala-decapitator Anything else that you want to address in this PR?

**Review by kambala-decapitator — APPROVED** [review]

**Comment by Fabrice-TIERCELIN** [comment]
@godric3, if you are on Windows, you can screenshot a dialog directly by pressing `Alt+Print Screen`.
