### PR TITLE
[1.7.2] Monster spell fix

### LINKED ISSUE #6731: [1.7.2] Teleport bug
**Describe the bug**
Jotunn and Jotunn Warlord can use teleport, it is fixed last time.
However, there is still a bug.
If Jotunn use teleport without click the button from right panel,
it can only select the target creature, but CANNOT select a target **within the caster's movement range** to finish the next step.

Case 1: Since spells cannot be cast within movement range, the default is to walk to that location. However, spells can no longer be cast during this battle.

https://github.com/user-attachments/assets/fa3e1546-689d-48ea-965e-40c487e098a2

Case 2: Because the spell was canceled due to the inability to cast, the target can only be teleported to the top left corner in the next round.

https://github.com/user-attachments/assets/56062f4c-5f77-4649-a555-1ee93de71b34

**Did it work earlier?**
New feature in testing.

**Version**

- OS:Windows
- Version:1.7.2 beta

### PR DESCRIPTION
**Pull request by kdmcser**
fix #6731. deactive stack when casting teleport and sacrifice.

### CODE REVIEW

File: client/battle/BattleActionsController.cpp [hunk 1]
```diff
@@ -932,19 +939,33 @@ void BattleActionsController::actionRealize(PossiblePlayerBattleAction action, c
...
 					if(heroSpellToCast)
+					{
 						heroSpellToCast->aimToHex(targetHex);
+					}
 					else
+					{
 						monsterSpellTargets.push_back(targetHex);
+						monsterCaster = owner.stacksController->getActiveStack();
+						owner.windowObject->blockUI(true);
+						owner.stacksController->deactivateStack();
```
Comment (IvanSavenko) [inline client/battle/BattleActionsController.cpp]: Why you need to deactivate stack and block UI?

Sacrifice / Teleport actions should have higher priority than all normal actions like movement, so should not interfere

Comment (kdmcser) [reply client/battle/BattleActionsController.cpp]: OK，I just copy from hero cast, will delete it

Comment (IvanSavenko) [reply client/battle/BattleActionsController.cpp]: I was not saying that this is wrong (I am not sure which is correct), but about the reason why it was added.

And why you also need to deactivate stack?

Comment (kdmcser) [reply client/battle/BattleActionsController.cpp]: If I don't deactivate the stack, moving this unit will take priority over teleport. I'm not entirely sure about the effect of blocking UI. Adding or not adding it seems to make little difference. I thought you meant that blocking the UI is unnecessary.

Comment (IvanSavenko) [reply client/battle/BattleActionsController.cpp]: Ah, I think UI is blocked during hero spellcast simply because H3 does the same. So not sure what we should do for creature spellcasting. Fine for me either way.

As for deactivation of stacks - check `BattleActionsController::reorderPossibleActionsPriority`. Proper solution would be to make TELEPORT and possibly SACRIFICE actions having higher (e.g. closer to zero) priority than movement (or other unit actions)

Comment (kdmcser) [reply client/battle/BattleActionsController.cpp]: I tried  to modify the priority of `BattleActionsController::reorderPossibleActionsPriority`, it works. But the creature's movement shadow will remains. Perhaps we should make this invisible?

Comment (IvanSavenko) [reply client/battle/BattleActionsController.cpp]: How it works for hero cast? Do we deactivate stack or hide movement in some other way?

I think we hide it during hero spellcast? If I am correct, then makes sense to do the same here, and for all spells, not just teleport

Comment (kdmcser) [reply client/battle/BattleActionsController.cpp]: When the hero casts, we deactivate the stack—I actually copied the code from there. As of now, only teleport and sacrifice enter this interface; other spells take effect immediately when the target is clicked. I’ve already adjusted the position of the deactivation, so any new spells in the future will also work correctly.
