### PR TITLE
[1.6.2] multiple fixes

### LINKED ISSUE #3245: When you start a campaign, you see a folder with maps and other campaigns that are located in the “others” folder
Not critical of course, but distracting
I made a video [OtherMaps.zip](https://github.com/vcmi/vcmi/files/13500297/OtherMaps.zip)

### LINKED ISSUE #3601: Minor campaigns bugs
1. Map region should blink for short while on opening campaign scenario startup screen as in H3
2. If multiple scenarios are possible to be selected, VCMI doesn't pick first one - for example in Armageddon's Blade campaign Gelu mission gets picked by default

### PR DESCRIPTION
**Pull request by Laserlicht**
- fixes upgrade buttons for hero speciality
- fix preselect order if multiple scenarios are selectable in campaign (fixes  #3601)
- added blink animation for campaign scenario selection screen (fixes  #3601)
- fixed surrender video (reported on discord, regression of #3998)
- workaround to avoid showing list when selecting scenario from campaignset or continuing campaign (fixes  #3245)

### CODE REVIEW

File: lib/mapObjects/CGHeroInstance.cpp [hunk 1]
```diff
@@ -1893,7 +1893,7 @@ bool CGHeroInstance::isMissionCritical() const
 
 void CGHeroInstance::fillUpgradeInfo(UpgradeInfo & info, const CStackInstance & stack) const
 {
-	TConstBonusListPtr lista = getBonusesOfType(BonusType::SPECIAL_UPGRADE, BonusSubtypeID(stack.getId()));
+	TConstBonusListPtr lista = getBonuses(Selector::typeSubtype(BonusType::SPECIAL_UPGRADE, BonusSubtypeID(stack.getId())));
```
Comment (Laserlicht) [inline lib/mapObjects/CGHeroInstance.cpp:1896]: @IvanSavenko Has to revert your change from cached bonuses from #5110 as it breaks the upgrade buttons.

Comment (IvanSavenko) [reply lib/mapObjects/CGHeroInstance.cpp:1896]: This is incorrect fix.
Problem is in getBonusesOfType method. Correct fix is
```diff
diff --git a/lib/bonuses/IBonusBearer.cpp b/lib/bonuses/IBonusBearer.cpp
index fa3f8b250..2e6f29d12 100644
--- a/lib/bonuses/IBonusBearer.cpp
+++ b/lib/bonuses/IBonusBearer.cpp
@@ -59,7 +59,7 @@ TConstBonusListPtr IBonusBearer::getBonusesOfType(BonusType type) const
 TConstBonusListPtr IBonusBearer::getBonusesOfType(BonusType type, BonusSubtypeID subtype) const
 {
        std::string cachingStr = "type_" + std::to_string(static_cast<int>(type)) + "_" + subtype.toString();
-       CSelector s = Selector::type()(type);
+       CSelector s = Selector::typeSubtype(type, subtype);
        return getBonuses(s, cachingStr);
 }
```
