### PR TITLE
Uniform Quickload and Restart logic

### LINKED ISSUE #6389: crash on restart scenario
**Describe the bug**
Game crash on restart scenario.

**Game logs**
Stack trace:
```
std::__atomic_base<bool>::store(std::memory_order __m, std::__atomic_base<bool>::__int_type __i, std::__atomic_base<bool> * const this) (/usr/include/c++/13/bits/atomic_base.h:481)
std::__atomic_base<bool>::operator=(std::__atomic_base<bool> * const this, std::__atomic_base<bool>::__int_type __i) (/usr/include/c++/13/bits/atomic_base.h:373)
std::atomic<bool>::operator=(std::atomic<bool> * const this, bool __i) (/usr/include/c++/13/atomic:80)
ThreadSafeVector<int>::requestTermination(ThreadSafeVector<int> * const this) (/home/laserlicht/vcmi/client/Client.h:63)
CClient::finishGameplay(CClient * const this) (/home/laserlicht/vcmi/client/Client.cpp:172)
ApplyOnLobbyHandlerNetPackVisitor::visitLobbyStartGame(ApplyOnLobbyHandlerNetPackVisitor * const this, LobbyStartGame & pack) (/home/laserlicht/vcmi/client/NetPacksLobbyClient.cpp:165)
libvcmi.so!LobbyStartGame::visitTyped(LobbyStartGame * const this, ICPackVisitor & visitor) (/home/laserlicht/vcmi/lib/networkPacks/NetPacksLib.cpp:748)
libvcmi.so!CPack::visit(CPack * const this, ICPackVisitor & visitor) (/home/laserlicht/vcmi/lib/networkPacks/NetPacksLib.cpp:29)
CServerHandler::visitForLobby(CServerHandler * const this, CPackForLobby & lobbyPack) (/home/laserlicht/vcmi/client/CServerHandler.cpp:992)
ServerHandlerCPackVisitor::visitForLobby(ServerHandlerCPackVisitor * const this, CPackForLobby & lobbyPack) (/home/laserlicht/vcmi/client/CServerHandler.cpp:902)
libvcmi.so!CPackForLobby::visitBasic(CPackForLobby * const this, ICPackVisitor & visitor) (/home/laserlicht/vcmi/lib/networkPacks/NetPacksLib.cpp:54)
libvcmi.so!CPack::visit(CPack * const this, ICPackVisitor & visitor) (/home/laserlicht/vcmi/lib/networkPacks/NetPacksLib.cpp:24)
CServerHandler::onPacketReceived(CServerHandler * const this, const std::vector<std::byte, std::allocator<std::byte> > & message) (/home/laserlicht/vcmi/client/CServerHandler.cpp:920)
libvcmi.so!operator()(const struct {...} * const __closure) (/home/laserlicht/vcmi/lib/network/NetworkConnection.cpp:221)
libvcmi.so!boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> >::operator()(void)(boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> > * const this) (/usr/include/boost/asio/detail/bind_handler.hpp:60)
libvcmi.so!boost::asio::asio_handler_invoke<boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> > >(boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> > &, ...)(boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> > & function) (/usr/include/boost/asio/handler_invoke_hook.hpp:88)
libvcmi.so!boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> >, InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> >(boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> > &, struct {...} &)(boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> > & function, struct {...} & context) (/usr/include/boost/asio/detail/handler_invoke_helpers.hpp:54)
libvcmi.so!boost::asio::detail::asio_handler_invoke<boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> >, InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> >(boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> > &, boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> > *)(boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> > & function, boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> > * this_handler) (/usr/include/boost/asio/detail/bind_handler.hpp:111)
libvcmi.so!boost_asio_handler_invoke_helpers::invoke<boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> >, boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> > >(boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> > &, boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> > &)(boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> > & function, boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> > & context) (/usr/include/boost/asio/detail/handler_invoke_helpers.hpp:54)
libvcmi.so!boost::asio::detail::executor_op<boost::asio::detail::binder0<InternalConnection::receivePacket(const std::vector<std::byte>&)::<lambda()> >, std::allocator<void>, boost::asio::detail::scheduler_operation>::do_complete(void *, boost::asio::detail::scheduler_operation *, const boost::system::error_code &, std::size_t)(void * owner, boost::asio::detail::scheduler_operation * base) (/usr/include/boost/asio/detail/executor_op.hpp:71)
```

**To Reproduce**

1. Start single scenario (e.g. "All for one")
2. Restart Scenario from system options

**Version**

- OS: Linux
- Version: current develop

### PR DESCRIPTION
**Pull request by mrhaandi**
Fixes #6389.

Made quick load logic follow restart logic more closely.
This eliminates double cleanup potential and makes handing of mid-game reloads by quickload unnecessary.
Quickload loading screen now follows the same path as restart.

Tested (quick load from map / quick load from battle / restart) on single player, hotseat, and campaign mode.

### CODE REVIEW

File: server/NetPacksLobbyServer.cpp [hunk 1]
```diff
@@ -118,26 +118,17 @@ void ClientPermissionsCheckerNetPackVisitor::visitLobbyChatMessage(LobbyChatMess
...
-	if (!srv.prepareToStartGame()) {
-		//failure is destructive and an exception is the only way
-		throw std::runtime_error("Failed to prepare to start game during quick load.");
-	}
-
-	// create LobbyStartGame packet with loaded state and announce to all clients
-	LobbyStartGame startPack;
-	startPack.initializedStartInfo = std::make_shared<StartInfo>(*srv.gh->gameState().getInitialStartInfo());
-	startPack.initializedGameState = srv.gh->gs;
-	srv.announcePack(startPack);
```
Comment (IvanSavenko) [inline server/NetPacksLobbyServer.cpp:135]: No longer needed? How clients receive correct initial gamestate now?

Comment (mrhaandi) [reply server/NetPacksLobbyServer.cpp:135]: The two lines above suffice:
```
	// modify StartInfo to load the quicksave
	srv.si->mode = EStartMode::LOAD_GAME;
	srv.si->mapname = pack.saveFilePath;
```
This follows the same logic as restart game, where StartInfo is set and then the StartGame logic takes care of the rest, which is initiated later by the added lines in `client/NetPacksLobbyClient.cpp`
```
	handler.restartGameplay();
	handler.sendStartGame();
```
I just now finished a three hour hotseat session with this PR code and it works well. Had not a single crash, yay, but some other vcmi bugs 🥲.
