### PR TITLE
Fixes for 1.2 branch

### LINKED ISSUE #1836: Game crash if music files are missing
**To Reproduce**
1. Remove mp3 folder from data folder
2. Install and enable Forge mod
3. Start random map with forge town (must be on asphalt terrain)
4. Enter and leave you castle
5. Move hero at asphalt tile

**Expected behavior**
everything goes well

**Actual behavior**
client crash

**Version**
VCMI 1.1.0, 1.1.1

The root cause is "grass.mp3" soundtrack specified in
/forge/Mods/asphalt-terrain-mod/Content/config/terrains.json

Not reproduced in vanilla game

### LINKED ISSUE #1888: Assertion failure hot-seat mode
**Describe the bug**
Assertion failure
vcmiclient -> widgets -> TextControls.cpp, line 360
`assert(enteringText == false);`

**To Reproduce**
1. Start hotseat mode
2. Open console (press Tab)

**Expected behavior**
Console opened

**Actual behavior**
Assertion failure

**Did it work earlier?**
yes

**Version**
 - OS: MacOS
 - Version: develop branch (1.3)

### LINKED ISSUE #1906: Shortcuts for the new System Menu do not work
**Describe the bug**
System Menu shortcuts not working, in fact any key press will just close the menu immediately

**Version**
 - OS: Windows
 - Version: Develop

### LINKED ISSUE #1907: [CRITICAL] Effects appear twice in hotseat game
**Describe the bug**
critical because Impacts game balance

**To Reproduce**
1. Start hotseat game
2. Have any creature which makes some effect
3. Attack human-player hero
4. Trigger any effect

**Expected behavior**
Effect appears once

**Actual behavior**
Effect appears twice

**Did it work earlier?**
Works normally in vcmi-1.1

**Screenshots**
You can see on video as mana has been stolen twice (18 becomes 16)

https://user-images.githubusercontent.com/9308612/230685257-ea435fad-baef-488a-92e4-f175bbd64af4.mp4

**Version**
 - Version: develop (vcmi-1.3)

### PR DESCRIPTION
**Pull request by IvanSavenko**
- Fixes #1836 
- Fixes #1888 
- Fixes #1906 
- Fixes #1907

### CODE REVIEW

File: client/CMusicHandler.cpp [hunk 1]
```diff
@@ -563,12 +555,20 @@ void MusicEntry::load(std::string musicURI)
...
 
 	logGlobal->trace("Loading music file %s", musicURI);
 
-	auto musicFile = MakeSDLRWops(CResourceHandler::get()->load(ResourceID(std::move(musicURI), EResType::MUSIC)));
-
-	music = Mix_LoadMUS_RW(musicFile, SDL_TRUE);
+	try
+	{
+		auto musicFile = MakeSDLRWops(CResourceHandler::get()->load(ResourceID(std::move(musicURI), EResType::MUSIC)));
+		music = Mix_LoadMUS_RW(musicFile, SDL_TRUE);
```
Comment (Nordsoft91) [inline client/CMusicHandler.cpp:565]: who does own memory?

Comment (IvanSavenko) [reply client/CMusicHandler.cpp:565]: Will recheck later, but from what I remember, passing SDL_TRUE as second argument transfers ownership here

**Comment by krs0** [comment]
Installed this from artifacts... cannot start a map
image
