### PR TITLE
CModListView::loadScreenshots(): Ensure a mod is selected in allModsView

### LINKED ISSUE #989: attempt to open screenshots of Neutral Heroes mod triggers assertion
Assertion failed: (modModel->hasMod(modName)), function loadScreenshots, file cmodlistview_moc.cpp, line 723.

### LINKED ISSUE #3811: Debug build: downloading mod screenshots via going into screenshot mod info tab results in "assert failed"
As in title. Does not happen if screenshots are cached for particular mod already. Error message: vcmilauncher: /home/dydzio/VCMI/source_main/launcher/modManager/cmodlistview_moc.cpp:891: void CModListView::loadScreenshots(): Assertion `modModel->hasMod(modName)' failed.

### PR DESCRIPTION
**Pull request by Alexander-Wilms**
Fixes #989
Fixes #3811

I tried setting the index in the constructor, but that didn't work.

### CODE REVIEW

File: launcher/modManager/cmodlistview_moc.cpp [hunk 1]
```diff
@@ -962,6 +962,12 @@ void CModListView::loadScreenshots()
 {
 	if(ui->tabWidget->currentIndex() == 2)
 	{
+		if(ui->allModsView->currentIndex().row() == -1 || ui->allModsView->currentIndex().column() == -1)
```
Comment (kambala-decapitator) [inline launcher/modManager/cmodlistview_moc.cpp:965]:
```suggestion
		if(!ui->allModsView->currentIndex().isValid())
```
