### PR TITLE
fix check to show the move reminder dialog

### LINKED ISSUE #7238: "heroes can still move" warning doesn't appear under some specific conditions
**Describe the bug**
I have one hero that still has MP and who's not sleeping, but when I press Skip Turn, the confirmation dialog saying "heroes can still move" doesn't appear.

**Game logs**
-

**To Reproduce**

1. Load save: [skip_no_warn.vsgm1.zip](https://github.com/user-attachments/files/26742920/skip_no_warn.vsgm1.zip)
2. Observe that the last hero has MP and is not sleeping
3. press Skip Turn

**Expected behavior**
confirmation dialog saying "heroes can still move" appears

**Actual behavior**
the dialog doesn't appear

**Did it work earlier?**
I guess so

**Version**

- OS: macOS Intel
- Version: 1.7.3 @ 2f752d4945aeb1db03afe48ba987c8af63c12f50

**Additional context**
Using Extras and HOTA mods

### PR DESCRIPTION
**Pull request by kambala-decapitator**
The case when hero can still move and can move along the planned path was handled incorrectly.

fixes #7238

### CODE REVIEW

File: client/adventureMap/AdventureMapShortcuts.cpp [hunk 1]
```diff
@@ -284,27 +284,35 @@ void AdventureMapShortcuts::endTurn()
...
+			LIBRARY->generaltexth->allTexts[55],
+			[this](){ owner.hotkeyEndingTurn(); },
+			nullptr
+		);
+	};
+
 	if(settings["adventure"]["heroReminder"].Bool())
 	{
-		for(auto hero : GAME->interface()->localState->getWanderingHeroes())
+		for(const auto hero : GAME->interface()->localState->getWanderingHeroes())
```
Comment (C3pa) [inline client/adventureMap/AdventureMapShortcuts.cpp:298]: Is there a reason you don't take hero as a reference?

Comment (kambala-decapitator) [reply client/adventureMap/AdventureMapShortcuts.cpp:298]: That's a pointer
