### PR TITLE
Fix for #5885

### LINKED ISSUE #5885: game close when AI attack on the town other AI
save [Quit.zip](https://github.com/user-attachments/files/21082147/Quit.zip)
reproduce is random
Hota, develop 1.7.0.9c1b03cd8ad97acee1477ea3b706d176da2062fe, msvc

log [VCMI_Client_log.txt](https://github.com/user-attachments/files/21082152/VCMI_Client_log.txt)

> [2025-Jul-06 01:49:20.422021] TRACE [runNetwork] ai - Entering void __cdecl CBattleAI::activeStack(const class BattleID &,const class CStack *): stack: orange battle stack [8]: 3 of core:goldDragon from slot 0 of armyobj=3387.
> [2025-Jul-06 01:49:20.436013] TRACE [runNetwork] ai - Find move towards unreachable. Enemies count 0
> [2025-Jul-06 01:49:20.442013] DEBUG [runNetwork] ai - BattleAI: core:goldDragon -> core:azureDragon x 3, from 97 curpos 14 dist 5 speed 17: +2.780670 -24.690926 = 10.869889
> [2025-Jul-06 01:49:20.442013] TRACE [runNetwork] ai - orange Battle AI[0000005975DFF060]: Casting spells sounds like fun. Let's see...
> [2025-Jul-06 01:49:20.446010] WARN [runNetwork] global - Unauthorized obstacles access attempt, assuming massive spell
> [2025-Jul-06 01:49:20.447008] TRACE [runNetwork] ai - orange Battle AI[0000005975DFF060]: I can cast 10 spells.
> [2025-Jul-06 01:49:20.447008] TRACE [runNetwork] ai - orange Battle AI[0000005975DFF060]: I know how 10 of them works.
> [2025-Jul-06 01:49:20.482987] TRACE [runNetwork] ai - orange Battle AI[0000005975DFF060]: Found 84 spell-target combinations.
> [2025-Jul-06 01:49:20.482987] TRACE [runNetwork] ai - orange Battle AI[0000005975DFF060]: I have 6 turns left in this round
> [2025-Jul-06 01:49:20.482987] TRACE [runNetwork] ai - orange Battle AI[0000005975DFF060]: I could wait better moment to cast a spell
> [2025-Jul-06 01:49:20.499976] TRACE [MainGUI] global - loading C:\Users\New\Documents\My Games\vcmi\Mods\hota\Mods\mapDecorations\content\sprites\hota\fires\avdcfir8.def
> [2025-Jul-06 01:49:20.507972] TRACE [MainGUI] global - loading C:\Users\New\Documents\My Games\vcmi\Mods\hota\Mods\terrainOverlays\content\sprites\zwat03.def
>

### PR DESCRIPTION
**Pull request by Opuszek**
Fixes #5885
The crashes were caused by the behaviour of method meleeAttackHexes when receiving two double-wide units stacked one on another. 
position
One represents the position of helldoggos, two the position of an enemy double-wide unit.
The old method would consider it a viable melee position.

Now, why BattleAI tries to check for such a situation is a completely different can of worms. I think it has to do with how reachability for flying units is calculated but I am not sure yet how to fix it or even if it should be fixed.

### CODE REVIEW

File: lib/CStack.cpp [hunk 1]
```diff
@@ -246,51 +246,22 @@ void CStack::prepareAttacked(BattleStackAttacked & bsa, vstd::RNG & rand, const
...
 	BattleHexArray res;
 
 	if (!attackerPos.isValid())
 		attackerPos = attacker->getPosition();
 	if (!defenderPos.isValid())
 		defenderPos = defender->getPosition();
 
-	BattleHex otherAttackerPos = attackerPos.toInt() + (attacker->unitSide() == BattleSide::ATTACKER ? -1 : 1);
-	BattleHex otherDefenderPos = defenderPos.toInt() + (defender->unitSide() == BattleSide::ATTACKER ? -1 : 1);
+	BattleHexArray attackableHxs = attacker->doubleWide() ? attackerPos.getNeighbouringTilesDoubleWide(attacker->unitSide()) : attackerPos.getNeighbouringTiles();
```
Comment (IvanSavenko) [inline lib/CStack.cpp]:
```suggestion
	BattleHexArray attackableHxs = attacker->getSurroundingHexes(attackerPos);
```

File: lib/CStack.cpp [hunk 2]
```diff
@@ -246,51 +246,22 @@ void CStack::prepareAttacked(BattleStackAttacked & bsa, vstd::RNG & rand, const
...
 
-	if(BattleHex::mutualPosition(attackerPos, defenderPos) >= 0) //front <=> front
+	if (std::find(attackableHxs.begin(), attackableHxs.end(), defenderPos) != attackableHxs.end())
```
Comment (IvanSavenko) [inline lib/CStack.cpp]:
```suggestion
	if (attackableHxs.contains(defenderPos))
```

File: lib/CStack.cpp [hunk 3]
```diff
@@ -246,51 +246,22 @@ void CStack::prepareAttacked(BattleStackAttacked & bsa, vstd::RNG & rand, const
...
-			res.insert(defenderPos);
-		}
-	}
-	if (defender->doubleWide()//front <=> back
-		&& BattleHex::mutualPosition(attackerPos, otherDefenderPos) >= 0)
-	{
-		if((mask & 2) == 0)
-		{
-			mask |= 2;
+		BattleHex otherDefenderPos = defenderPos.toInt() + (defender->unitSide() == BattleSide::ATTACKER ? -1 : 1);
```
Comment (IvanSavenko) [inline lib/CStack.cpp]:
```suggestion
		BattleHex otherDefenderPos = defender->occupiedHex(defenderPos);
```

File: lib/CStack.cpp [hunk 4]
```diff
@@ -246,51 +246,22 @@ void CStack::prepareAttacked(BattleStackAttacked & bsa, vstd::RNG & rand, const
...
+		if (std::find(attackableHxs.begin(), attackableHxs.end(), otherDefenderPos) != attackableHxs.end())
```
Comment (IvanSavenko) [inline lib/CStack.cpp]:
```suggestion
		if (attackableHxs.contains(otherDefenderPos))
```

**Comment by IvanSavenko** [comment]
> Now, why BattleAI tries to check for such a situation is a completely different can of worms.

Would be great to at least add debugging / tracking for such cases. Assuming that you can't reproduce this scenario reliably or can't figure out what exactly led to this situation

File: lib/CStack.cpp (hunk 1 above)
Comment (Opuszek) [reply lib/CStack.cpp]: It cannot be done, as we use attacker's position only if BattleHex position was not received through a function's parameter.

**Comment by Opuszek** [comment]
Right. I will take a better look at it tomorrow.

File: lib/CStack.cpp (hunk 1 above)
Comment (IvanSavenko) [reply lib/CStack.cpp]: This is what that method does:
```cpp
const BattleHexArray & Unit::getSurroundingHexes(const BattleHex & assumedPosition) const
{
	BattleHex hex = (assumedPosition.toInt() != BattleHex::INVALID) ? assumedPosition : getPosition(); //use hypothetical position

	return getSurroundingHexes(hex, doubleWide(), unitSide());
}
```

Comment (Opuszek) [reply lib/CStack.cpp]: Right, sorry, I had a brain fart.

**Comment by thehonestcto** [comment]
Is there any connection with this PR https://github.com/vcmi/vcmi/pull/6004 ? 
Would be interesting to try again with the latest develop now that it's merged, because to some degree your scenario is similar to the bug I experienced. Just to be sure.

**Comment by GrafDeVan** [comment]
1 more case quit from the game. No idea what has happened in battle
orange attack teal
[1.zip](https://github.com/user-attachments/files/21824544/1.zip)
reproduce in 6016

**Comment by Opuszek** [comment]
@GrafDeVan 
I received a bunch of warnings, but the game does not crash.
Screenshot from 2025-08-19 09-22-38

**Comment by GrafDeVan** [comment]
@Opuszek  please check next cases
[2025-08-17_15-29_The_Lone_Knigh.zip](https://github.com/user-attachments/files/21850697/2025-08-17_15-29_The_Lone_Knigh.zip)
[2025-08-17_16-08_Случайная_карт.zip](https://github.com/user-attachments/files/21850699/2025-08-17_16-08_._.zip)
[2025-08-18_00-05_Epic.zip](https://github.com/user-attachments/files/21850701/2025-08-18_00-05_Epic.zip)
[2025-08-18_12-27_Fall_and_Rise_.zip](https://github.com/user-attachments/files/21850702/2025-08-18_12-27_Fall_and_Rise_.zip)

reproduce
msvc, develop, 1.7.0.9a66130c1270e064a9b157973c7f35e2983b970e
msvc, 6016, 1.7.0.3018302bf6e2283211685be7530bdb369efa69ac

quit from the game on AI turn

**Comment by GrafDeVan** [comment]
@Opuszek sorry, I didn't notice you updated to 1.7.0.fbb639d182c684f156c40a2ef6245cca80fd0c79 . Now all is ok

**Comment by GrafDeVan** [comment]
still happens in battle
[3Open.zip](https://github.com/user-attachments/files/21860915/3Open.zip)

**Comment by Opuszek** [comment]
@GrafdeVan it is caused by all stacks dying during the battle. It seems that a draw is bugged on develop.
I will try to fix it in the future, but the bug is unrelated.

**Comment by Opuszek** [comment]
@GrafDeVan #6063 fixes this problem.
