### PR TITLE
[1.6.6] portrait mode for android & grey bar fix

### LINKED ISSUE #4141: Gray bar on android after switching apps
**Describe the bug**
Sometimes after switching Apps back to VCMI there is a grey bar overlaying the game (~20% possibility). Can be removed sometimes by switching apps again.

Only new launcher. Noting critical.

**To Reproduce**
1. Start new game
2. Switch to another app (or switch between multiple apps)
3. Switch back to VCMI
4. Sometimes the gray bar appears and stays

**Screenshots**
grafik

**Version**
 - OS: Android 14
 - Version: 1.5.3 beta

### LINKED ISSUE #5362: VCMI doesn't go back to fullscreen when returning to the app when in-game on Android
**Describe the bug**
Whenever I "alt-tab" from the app when in-game and then return back, Phone UI refuses to hide until reselected from "Active 
Programs" list

**Game logs**
VCMI_.zip with logs and two screenshots
[VCMI_.zip](https://github.com/user-attachments/files/18628637/VCMI_.zip)

**To Reproduce**

1. Open the launcher, start the game
2. While the game [Heroes3] is started, switch to another application (f.e. Discord). **Do not use "Home button", it won't reproduce the bug. You need exactly to switch to another application. Works anywhere (Start menu, loading screen, etc),  as long as the game is started. 
3. Return back to VCMI application
4. See the result

**Expected behavior**
VCMI goes back to fullscreen as usual

**Actual behavior**
Phone UI refuses to be hidden and there is gray line up on the screen

**Did it work earlier?**
Starting from 1.5.x, definitely. Not sure about older versions.

**Screenshots**
in VCMI_.zip

**Version**

- OS: Android 14 (OneUI 6.1)
- Version: 1.5.x and later (including 1.6.4)
- Mods: none/any, works with clean game and with mods as well
- Installation: Heroes 3 Complete

**Additional context**
May appear randomly, can be fixed by pressing "Active Programs" UI button and reselecting VCMI

### PR DESCRIPTION
**Pull request by Laserlicht**
Adds setting to allow portrait mode change by screen rotation on android. No layout changes yet (so: not optimal for smartphones, but good for tablets). Splitscreen is working nicely too.

Also fixes grey bar after switching app.

Portrait mode:
- Related #3765

Gray bar:
- Fixes #4141 
- Fixes #5362
- Related #4336

@kambala-decapitator Don't have an iOS device. If you interested you could also add iOS support afterwards.

### CODE REVIEW

File: launcher/settingsView/csettingsview_moc.cpp [hunk 1]
```diff
@@ -472,6 +475,13 @@ void CSettingsView::on_buttonShowIntro_toggled(bool value)
 	updateCheckbuttonText(ui->buttonShowIntro);
 }
 
+void CSettingsView::on_buttonAllowPortrait_toggled(bool value)
+{
+	Settings node = settings.write["video"]["allowPortrait"];
+	node->Bool() = value;
+	updateCheckbuttonText(ui->buttonAllowPortrait);
+}
+
```
Comment (IvanSavenko) [inline launcher/settingsView/csettingsview_moc.cpp:484]: Is there any point in making this option player-selectable, since there is no usable layout for vertical screen?

**Comment by kambala-decapitator** [comment]
I don't think I understand how it fixes grey bar. What is the explanation?
