### PR TITLE
keep screen on in launcher while downloading

### LINKED ISSUE #5995: Do not turn off display during mods downloading / installing
Currently on Android (Android 15 - Galaxy Tab 9 FE) you can encounter broken downloads / mod installing when your display automatically turns off.

Would be great when will be display always on during these actions in Launcher.

### PR DESCRIPTION
**Pull request by Laserlicht**
Fixes #5995

Replacement for #6022

Only keep screen on while downloading/extracting.

iOS can be added in separate PR later.

Sadly there is no native function in QT for this.

### CODE REVIEW

**Comment by Laserlicht** [comment]
@kambala-decapitator Tested also SDL2 (`SDL_DisableScreenSaver`). Compiles fine. But calling these functions does nothing.

Seems to need an SDL activity to work. So we need this custom implementation.

**Comment by kambala-decapitator** [comment]
the SDL function doesn't work because we don't configure its video subsystem in the launcher (we don't need it). But we can easily use SDL's actual implementation of the screensaver handling without reinventing the wheel:

https://github.com/libsdl-org/SDL/blob/98d1f3a45aae568ccd6ed5fec179330f47d4d356/src/core/android/SDL_android.c#L2198-L2209

basically what you need to is call this static method on the SDL activity class, please check if that'd work:

https://github.com/libsdl-org/SDL/blob/98d1f3a45aae568ccd6ed5fec179330f47d4d356/android-project/app/src/main/java/org/libsdl/app/SDLActivity.java#L1123

or expose a new java method on the launcher activity that does the same thing instead of using that ugly C++ JNI code, implementation would be just a single line of code: https://developer.android.com/develop/background-work/background-tasks/awake/screen-on#java

on iOS we can't reuse SDL's implementation, but it's also a trivial one-liner of objc code, put it into `iOS_utils` (iirc it's already linked to launcher):
```objc
void setScreensaverEnabled(bool isEnabled)
{
	UIApplication.sharedApplication.idleTimerDisabled = isEnabled ? NO : YES;
}
```

File: launcher/modManager/cmodlistview_moc.cpp [hunk 1]
```diff
@@ -798,6 +798,7 @@ void CModListView::downloadFile(QString file, QUrl url, QString description, qin
 
 void CModListView::downloadProgress(qint64 current, qint64 max)
 {
+	Helper::keepScreenOn(true);
```
Comment (kambala-decapitator) [inline launcher/modManager/cmodlistview_moc.cpp]: better do it once on download start

**Comment by Laserlicht** [comment]
Ugly, but it works. 🤣

Tested a lot. But testing here is a pain.

For example my first test:
https://github.com/vcmi/vcmi/commit/27ee1359a63fffdd25b26a437d4d215c0152f910

No idea why it doesn't work...

Will test SDL call.

**Comment by kambala-decapitator** [comment]
your initial attempt looks correct. Were there any errors / crashes?

Maybe the difference is `QtAndroid::runOnAndroidThread`? Have you checked `logcat` for hints?

**Comment by Laserlicht** [comment]
Works now! `QtAndroid::runOnAndroidThread` was the missing thing.

File: launcher/helper.cpp [hunk 2]
```diff
@@ -114,4 +115,17 @@ MainWindow * getMainWindow()
...
+
+void keepScreenOn(bool on)
+{
+#if defined(VCMI_ANDROID)
+	QtAndroid::runOnAndroidThread([on]
+	{
+		QtAndroid::androidActivity().callMethod<void>("setScreensaverEnabled", "(Z)V", !on);
+	});
+#elif defined(VCMI_IOS)
+	iOS_utils::setScreensaverEnabled(!on);
```
Comment (kambala-decapitator) [inline launcher/helper.cpp]: why not naming all the methods in the same way?

File: launcher/modManager/cmodlistview_moc.cpp [hunk 3]
```diff
@@ -806,6 +807,7 @@ void CModListView::downloadProgress(qint64 current, qint64 max)
 
 void CModListView::extractionProgress(qint64 current, qint64 max)
 {
+	Helper::keepScreenOn(true);
```
Comment (kambala-decapitator) [inline launcher/modManager/cmodlistview_moc.cpp]: is the call really needed here? Currently it looks imbalanced: you call it with true twice, but with false - only once.

Comment (Laserlicht) [reply launcher/modManager/cmodlistview_moc.cpp]: Added it above `ui->progressBar->setVisible(true);` because it should be depend on progressbar.

File: launcher/helper.cpp (hunk 2 above)
Comment (Laserlicht) [reply launcher/helper.cpp]: Can do. But would prefer `keepScreenOn`. Because `setScreensaverEnabled` is a little bit confusing (inverted logic).

Comment (kambala-decapitator) [reply launcher/helper.cpp]: yes please, keepScreenOn is fine

File: launcher/modManager/cmodlistview_moc.cpp (hunk 3 above)
Comment (kambala-decapitator) [reply launcher/modManager/cmodlistview_moc.cpp]: it shouldn't depend on any UI element. Correct logic is:
1. long operation starts -> Helper::keepScreenOn(true)
2. long operation ends -> Helper::keepScreenOn(false)

Comment (Laserlicht) [reply launcher/modManager/cmodlistview_moc.cpp]: Adjusted positions to set.

It's still imbalanced because there is an abort possibility.

**Review by kambala-decapitator — APPROVED** [review]
