### PR TITLE
audio from SMK video file

### LINKED ISSUE #2760: No audio for 3DO intro
**Describe the bug**
I don't have audio playing for the game "3DO" intro. After skipping the intro, main menu music plays fine.

**Game logs**
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/12522375/VCMI_Client_log.txt)

**To Reproduce**
1. Start the game

**Expected behavior**
Intro plays with audio

**Actual behavior**
Intro plays without audio.

**Did it work earlier?**
No

**Screenshots**
N/A, video if you request, but I think the description is self-explanatory.

**Version**
 - OS: Fedora 38
 - Version: 1.3.1

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Laserlicht**
fixes #2760

### CODE REVIEW

File: client/mainmenu/CPrologEpilogVideo.h [hunk 1]
```diff
@@ -23,6 +23,7 @@ class CPrologEpilogVideo : public CWindowObject
 
 	std::shared_ptr<CMultiLineLabel> text;
 
+	int sound = 0;
```
Comment (IvanSavenko) [inline client/mainmenu/CPrologEpilogVideo.h:26]:
```suggestion
	int soundChannelID = 0;
```

File: client/CVideoHandler.cpp [hunk 2]
```diff
@@ -435,6 +453,163 @@ void CVideoPlayer::close()
...
+		ui32 ChunkSize;
+		ui8 WAVE[4] = {'W', 'A', 'V', 'E'};
+		ui8 fmt[4] = {'f', 'm', 't', ' '};
+		ui32 Subchunk1Size = 16;
+		ui16 AudioFormat = 1;
+		ui16 NumOfChan = 2;
+		ui32 SamplesPerSec = 22050;
+		ui32 bytesPerSec = 22050 * 2;
+		ui16 blockAlign = 2;
+		ui16 bitsPerSample = 16;
```
Comment (IvanSavenko) [inline client/CVideoHandler.cpp:574]: What happens if video has different number of channels / samples per second?
Can we extract this information from video?

Comment (Laserlicht) [reply client/CVideoHandler.cpp:574]: Yes. It's a few lines below overwritten.
For channel I removed this functionality.

All h3 videos have 2 channels. It's possible, but a pain with ffmpeg, because they changed the api and you need different functions for different ffmpeg versions.

File: client/CVideoHandler.h [hunk 3]
```diff
@@ -36,6 +36,7 @@ class IMainVideoPlayer : public IVideoPlayer
 	{
 		return false;
 	}
+	virtual std::pair<std::unique_ptr<ui8 []>, si64> getAudio(const VideoPath & videoToOpen) { return std::pair<std::unique_ptr<ui8 []>, si64>(std::make_pair(std::make_unique<ui8[]>(0), 0)); };
```
Comment (Nordsoft91) [inline client/CVideoHandler.h:39]:
```suggestion
	virtual std::pair<std::unique_ptr<ui8 []>, si64> getAudio(const VideoPath & videoToOpen) { return std::make_pair(std::make_unique<ui8[]>(nullptr), 0); };
```

File: client/CVideoHandler.cpp [hunk 4]
```diff
@@ -435,6 +453,163 @@ void CVideoPlayer::close()
...
+	} wav_hdr;
+
+	wav_hdr wav;
+	wav.ChunkSize = samples.size() + sizeof(wav_hdr) - 8;
+  	wav.Subchunk2Size = samples.size() + sizeof(wav_hdr) - 44;
+	wav.SamplesPerSec = formatAudio->streams[streamAudio]->codecpar->sample_rate;
+	wav.bitsPerSample = formatAudio->streams[streamAudio]->codecpar->bits_per_coded_sample;
+	auto wavPtr = reinterpret_cast<ui8*>(&wav);
+
+	dat = std::pair<std::unique_ptr<ui8 []>, si64>(std::make_pair(std::make_unique<ui8[]>(samples.size() + sizeof(wav_hdr)), samples.size() + sizeof(wav_hdr)));
```
[the remark this answers is not in the document]
Comment (Nordsoft91) [reply client/CVideoHandler.cpp:586]: BTW, are you sure it's correct statement to make unique_ptr this way?
If I understand it correctly, it should be
```
std::make_unique<ui8[]>(new ui8[samples.size() + sizeof(wav_hdr)]);
```

File: client/CMusicHandler.cpp [hunk 5]
```diff
@@ -142,6 +142,30 @@ Mix_Chunk *CSoundHandler::GetSoundChunk(const AudioPath & sound, bool cache)
...
+		if (cache)
+			soundChunksRaw.insert({startBytes, std::make_pair (chunk, std::move (data.first))});
+
+		return chunk;
+	}
+	catch(std::exception &e)
+	{
+		logGlobal->warn("Cannot get sound chunk: %s", e.what());
+		return nullptr;
+	}
```
[the remark this answers is not in the document]
Comment (Laserlicht) [reply client/CMusicHandler.cpp:166]: I think the SDL functions. But I'm not sure. For Video it's similar.

File: client/CVideoHandler.h (hunk 3 above)
Comment (Laserlicht) [reply client/CVideoHandler.h]: Is not possible to use `nullptr` here. Accepts only `0`. :(

File: client/CMusicHandler.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (IvanSavenko) [reply client/CMusicHandler.cpp:166]: No, no functions might throw here.

Function that *might* throw is attempt to load non-existing file. No such attempts here

File: client/CVideoHandler.h (hunk 3 above)
Comment (Nordsoft91) [reply client/CVideoHandler.h]: I guess this might work
```
std::make_pair(nullptr, 0);
```
