### PR TITLE
Reorganize player turn order handling on server

### LINKED ISSUE #2539: After deafeating AI player there is info, just like if it was a human player
**Describe the bug**
After killing the last enemy hero and winning the game, I received three infobox:
imag123e
asdfasfd
asdfasdfasdf
The first would be directed to the human player in a multiplayer game, but blue was controlled by AI

**To Reproduce**
1.Turn on the mods needed to start "Antagarich Burning - maps"
2.Run the save below
https://1drv.ms/u/s!Ahfxr6a8tP2F8yTk689hMClb0GeK?e=6qDfQc

 - OS: Windows 10
 - Version: 1.3

### LINKED ISSUE #2564: Incorrect panel color in hotseat game
**Describe the bug**
Color for latest player is shown

**To Reproduce**
1. Start hotseat game
2. Observe problem

**Did it work earlier?**
Yes

**Screenshots**

Снимок экрана 2023-08-12 в 13 37 17
Снимок экрана 2023-08-12 в 13 34 52

**Version**
 - Version: VCMI-1.3

### LINKED ISSUE #2609: In Hotseat game, before player 1 turn start the right side screen for player 2 is shown
In the screenshot below player 1 (Red) is Cove and he sees Player 2 (blue) heroes and castles.
It happens in later turns as well.

image

### LINKED ISSUE #2662: Crash after escape
**Describe the bug**
It crashes after choosing escape from battle.

**To Reproduce**
1. Go to any battle
2. Click on 'escape' and ensure it.
3. Crash happens

**Did it work earlier?**
Just found it from yesterday's version.

**Screenshots**
image

**Version**
 - OS: Windows
 - Version: 1.4.0.

### PR DESCRIPTION
**Pull request by IvanSavenko**
First step for simturns support out of many:
- Moved logic related to player turn order out of GameHandler into a new class.
- Reorganized server-side logic to allow potential support for multiple acting players
- Tavern will now be updated immediately when player ends turn on 7th day (to simplify logic for 7th day retreat)
- Fixes #2662 
- Fixes #2609
- Fixes #2564
- Fixes #2539
- Fixes incorrect infobox message (%s placeholder not replaced) on defeating player

TODO:
- [x] Test turn order (single-player)
- [x] Test turn order (hot-seat)
- [x] Check human player defeating (single-player)
- [x] Check human player defeating (hotseat)
- [x] Check AI player defeating
- [x] Check "7 days without castle" loss condition
- [x] Check maps with turn limit
- [x] Refresh tavern when player ends turn (and remove 7th day workaround)

### CODE REVIEW

File: lib/NetPackVisitor.h [hunk 1]
```diff
@@ -27,6 +27,7 @@ class ICPackVisitor
 	virtual void visitPlayerBlocked(PlayerBlocked & pack) {}
 	virtual void visitPlayerCheated(PlayerCheated & pack) {}
 	virtual void visitYourTurn(YourTurn & pack) {}
+	virtual void visitYourTurn(DaysWithoutTown & pack) {}
```
Comment (Nordsoft91) [inline lib/NetPackVisitor.h:30]: visitDaysWithoutTown?

File: server/CGameHandler.h [hunk 2]
```diff
@@ -248,14 +225,11 @@ class CGameHandler : public IGameCallback, public CBattleInfoCallback, public En
...
 	{
 		h & QID;
-		h & states;
-		h & battles;
-		h & heroPool;
 		h & getRandomGenerator();
-		h & playerMessages;
-
-		if (!h.saving)
-			deserializationFix();
```
Comment (Nordsoft91) [inline server/CGameHandler.h:258]: Did you check that game over network works well? I remember there were some issues with stacks of heros because of this deserialization fix but don't remember details

File: server/processors/TurnOrderProcessor.cpp [hunk 3]
```diff
@@ -0,0 +1,213 @@
...
+			doStartPlayerTurn(player);
+	}
+}
+
+bool TurnOrderProcessor::playerAwaitsTurn(PlayerColor which) const
+{
+	return vstd::contains(awaitingPlayers, which);
+}
+
+bool TurnOrderProcessor::playerMakingTurn(PlayerColor which) const
```
Comment (Nordsoft91) [inline server/processors/TurnOrderProcessor.cpp:205]:
```suggestion
bool TurnOrderProcessor::isPlayerMakingTurn(PlayerColor which) const
```

File: server/processors/TurnOrderProcessor.cpp [hunk 4]
```diff
@@ -0,0 +1,213 @@
...
+{
+	return vstd::contains(actingPlayers, which);
+}
+
+bool TurnOrderProcessor::playerAwaitsNewDay(PlayerColor which) const
```
Comment (Nordsoft91) [inline server/processors/TurnOrderProcessor.cpp:210]:
```suggestion
bool TurnOrderProcessor::isPlayerAwaitingNewDay(PlayerColor which) const
```

File: server/processors/TurnOrderProcessor.cpp [hunk 5]
```diff
@@ -0,0 +1,213 @@
...
+{
+	auto awaitingPlayersCopy = awaitingPlayers;
+	for (auto player : awaitingPlayersCopy)
+	{
+		if (canStartTurn(player))
+			doStartPlayerTurn(player);
+	}
+}
+
+bool TurnOrderProcessor::playerAwaitsTurn(PlayerColor which) const
```
Comment (Nordsoft91) [inline server/processors/TurnOrderProcessor.cpp:200]:
```suggestion
bool TurnOrderProcessor::isPlayerAwaitingTurn(PlayerColor which) const
```

File: server/CGameHandler.h (hunk 2 above)
Comment (IvanSavenko) [reply server/CGameHandler.h:258]: No, this is different deserializationFix, not related to stacks/bonus system. Check CGameHandler.cpp
