### PR TITLE
Fixes android crash

### LINKED ISSUE #5803: App crashes on exit
**Describe the bug**
As stated in title.

**Game logs**
Not necessary.

**To Reproduce**

1. Open VCMI
2. Click "exit".
3. See error

**Expected behavior**
No crash, just return to OS/launcher

**Actual behavior**
Crash

**Did it work earlier?**
Worked in 1.6.

**Screenshots**
Not necessary.

**Version**

- OS: Android
- Version: develop

**Additional context**
Probably OS-related.

### PR DESCRIPTION
**Pull request by Laserlicht**
Fixes #5803

- App closes now on VCMI exit.
- Autosave is now performed when app pauses -> should cover previous use case and is supported on iOS

### CODE REVIEW

File: client/GameInstance.cpp [hunk 1]
```diff
@@ -112,3 +113,29 @@ void GameInstance::onShutdownRequested(bool ask)
...
+		return;
+	}
+
+	if (!GAME->server().logicConnection)
+	{
+		logGlobal->info("... but no active connection found!");
+		return;
+	}
+
+	if(GAME->interface()->cb->getActiveBattles().size() > 0)
```
Comment (IvanSavenko) [inline client/GameInstance.cpp]:
```suggestion
	if(!GAME->interface()->cb->getActiveBattles().empty())
```

File: client/eventsSDL/InputHandler.cpp [hunk 2]
```diff
@@ -217,6 +217,18 @@ void InputHandler::preprocessEvent(const SDL_Event & ev)
...
+	else if(ev.type == SDL_APP_WILLENTERBACKGROUND)
+	{
+		std::scoped_lock interfaceLock(ENGINE->interfaceMutex);
+		ENGINE->user().onAppPaused(false);
+		return;
+	}
+	else if(ev.type == SDL_APP_WILLENTERFOREGROUND)
+	{
+		std::scoped_lock interfaceLock(ENGINE->interfaceMutex);
+		ENGINE->user().onAppPaused(true);
```
Comment (IvanSavenko) [inline client/eventsSDL/InputHandler.cpp]: This will trigger second autosave on entering *foreground*. Am I right? Probably unnecessary.

Comment (Laserlicht) [reply client/eventsSDL/InputHandler.cpp]: Yes. Forgot if for `resume` flag. Would like to keep `SDL_APP_WILLENTERFOREGROUND` as we can use resume flag for later improvements. And it's imo a little bit more understandable.

File: client/eventsSDL/InputHandler.cpp [hunk 3]
```diff
@@ -217,6 +217,18 @@ void InputHandler::preprocessEvent(const SDL_Event & ev)
 #endif
 		return;
 	}
+	else if(ev.type == SDL_APP_WILLENTERBACKGROUND)
+	{
+		std::scoped_lock interfaceLock(ENGINE->interfaceMutex);
+		ENGINE->user().onAppPaused(false);
+		return;
+	}
+	else if(ev.type == SDL_APP_WILLENTERFOREGROUND)
```
Comment (kambala-decapitator) [inline client/eventsSDL/InputHandler.cpp]: the events are balanced incorrectly. Most likely you want SDL_APP_**DID**ENTERFOREGROUND, depends on the actual event you're trying to handle. For example, on iOS when you receive a call, you'll get only SDL_APP_WILLENTERBACKGROUND at first, and if the interruption was short, there will be no SDL_APP_DIDENTERBACKGROUND - next will be SDL_APP_DIDENTERFOREGROUND.

Comment (IvanSavenko) [reply client/eventsSDL/InputHandler.cpp]: Problem is, right now we *need* some time to save the game since cb->saveGame() only sends pack to server (via boost::asio task, not network), which requires processing in different thread.

So using `DID` events might not work for saves since OS won't allocate CPU time for server thread anymore. (untested, might be wrong)

Correct solution would be to wait for some signal from server that save was made, but not sure if there is easy way to implement it at the moment.

Comment (kambala-decapitator) [reply client/eventsSDL/InputHandler.cpp]: on iOS you can [request additional execution time in background](https://developer.apple.com/documentation/uikit/uiapplication/beginbackgroundtask(withname:expirationhandler:)?language=objc), about 10-20s (the actual time varies between devices / iOS versions). Maybe android has something similar, but it also has full-featured background services (processes).

Comment (kambala-decapitator) [reply client/eventsSDL/InputHandler.cpp]: > So using DID events might not work for saves since OS won't allocate CPU time for server thread anymore

to clarify, the flow of events on minimizing an app and opening (resuming) it later:
1. SDL_APP_WILLENTERBACKGROUND
2. \<inactive>
3. SDL_APP_DIDENTERBACKGROUND
4. \<minimized>
5. SDL_APP_WILLENTERFOREGROUND
6. SDL_APP_DIDENTERFOREGROUND
7. \<active / working>

and there're cases like short phone call interruption where you'll observe only: 1,2,6,7

Comment (Laserlicht) [reply client/eventsSDL/InputHandler.cpp]: But this behavior is only on iOS. For Android both will the same.

> and there're cases like short phone call interruption where you'll observe only: 1,2,6,7

Is there some documentation about this confusing behavior?

But as far as I understand 1 will always called. So saving process in this pr should be correct?

Comment (kambala-decapitator) [reply client/eventsSDL/InputHandler.cpp]: - iOS: https://developer.apple.com/documentation/uikit/managing-your-app-s-life-cycle?language=objc#Respond-to-app-based-life-cycle-events I wouldn't call this behavior confusing :)
- Android: https://developer.android.com/guide/components/activities/activity-lifecycle (onPause -> onResume is also potentially possible, but maybe not the case for VCMI)

> But as far as I understand 1 will always called. So saving process in this pr should be correct?

yes, 1 is always called. But right now you're also using 5 to "restore" the engine which is incorrect.

Comment (Laserlicht) [reply client/eventsSDL/InputHandler.cpp]: Okay, then let's remove `SDL_APP_WILLENTERFOREGROUND` as this path is currently unused.

Comment (kambala-decapitator) [reply client/eventsSDL/InputHandler.cpp]: then you'll break iOS behavior on resuming the app, dunno about other platforms

Comment (kambala-decapitator) [reply client/eventsSDL/InputHandler.cpp]: also, it seems that values for onAppPaused are swapped right now

Comment (Laserlicht) [reply client/eventsSDL/InputHandler.cpp]: > then you'll break iOS behavior on resuming the app, dunno about other platforms

Why?
Querying these flags (and only one of them) should purely optional, right?
The os specific stuff should be handled by SDL?

Comment (kambala-decapitator) [reply client/eventsSDL/InputHandler.cpp]: I mean that you call `ENGINE->user().onAppPaused` (that pauses all engine operations IIUC) but then you don't restore it

Comment (Laserlicht) [reply client/eventsSDL/InputHandler.cpp]: > I mean that you call `ENGINE->user().onAppPaused` (that pauses all engine operations IIUC) but then you don't restore it

No, `onAppPaused` only does autosave atm. Nothing else. Moved it to `pauseAutoSave` to clarify.

**Comment by Olegmods** [comment]
Finally!
I'll give it a try and will report back if it works for me or not.

**Comment by Olegmods** [comment]
Tried. It no longer crashes.
A bit of suggestion would be to make it going to launcher on exit from the client (IIRC it was like that before), though. That would be nice of it would be possible.

**Comment by Laserlicht** [comment]
> Tried. It no longer crashes. A bit of suggestion would be to make it going to launcher on exit from the client (IIRC it was like that before), though. That would be nice of it would be possible.

Yes. My goal was removing crash and invalid app state (black screen).

Bringing back launcher has to be done by an android dev. No idea, why we got an blackscreen and how the stuff works.

Can done in later PR.

**Comment by kambala-decapitator** [comment]
> Bringing back launcher has to be done by an android dev

do we have one? ;)

**Comment by Laserlicht** [comment]
> > Bringing back launcher has to be done by an android dev
> 
> do we have one? ;)

Would be great to have one. ;)
