### PR TITLE
[1.6.x] Android native copy files

### LINKED ISSUE #5193: Cannot install Heroes Chronicles on Android
**Describe the bug**
I am attempting to import the Heroes Chronicles installer files from GOG on Android, but nothing happens when I select a file, it just goes back to the VCMI interface with no change.

**Game logs**
Not sure how to get logs on Android. I don't have access to the Data folder on Android 14.

**To Reproduce**

1. Open VCMI
2. Select "Import Files" next to the Heroes Chronicles information text.
3. Select any Heroes Chronicles installer.

**Expected behavior**
Heroes Chronicles installation.

**Actual behavior**
Heroes Chronicles doesn't install.

**Did it work earlier?**
No.

**Screenshots**
No relevant screenshots.

**Version**
- Android 14 (OxygenOS)
- Version: [VCMI version 1.6.1]

**Additional context**
Device: OnePlus Pad Go

### PR DESCRIPTION
**Pull request by Laserlicht**
attempt to fix #5193

### CODE REVIEW

**Comment by IvanSavenko** [comment]
Not required, but more details logging / error reporting would also be nice (does copied file exists? Does it have correct size? Can we open it? ) - so in case if something still does not works, we would have some useful info about what exactly is broken.

File: launcher/firstLaunch/firstlaunch_moc.cpp [hunk 1]
```diff
@@ -369,8 +371,20 @@ void FirstLaunchView::extractGogData()
 
 		QString tmpFileExe = tempDir.filePath("h3_gog.exe");
 		QString tmpFileBin = tempDir.filePath("h3_gog-1.bin");
+#ifdef VCMI_ANDROID
+		auto copyFunc = [](std::string src, std::string dst)
+		{
+			CAndroidVMHelper vmHelper;
+			vmHelper.callCustomMethod(CAndroidVMHelper::NATIVE_METHODS_DEFAULT_CLASS, "copyFileFromUri", "(Ljava/lang/String;Ljava/lang/String;)V", [src, dst](JNIEnv * env, jclass javaHelper, jmethodID methodId){
+				env->CallStaticVoidMethod(javaHelper, methodId, env->NewStringUTF(src.c_str()), env->NewStringUTF(dst.c_str()));
+			}, true);
```
Comment (kambala-decapitator) [inline launcher/firstLaunch/firstlaunch_moc.cpp:380]: not sure why you decided to write something out of your head instead of checking how it's already done in the launcher, for example:
https://github.com/vcmi/vcmi/blob/6e032946337ccaaeb189cc5f01d64f8299068305/launcher/prepare.cpp#L63

and it doesn't involve any lambdas, just pass proper objects

File: android/vcmi-app/src/main/java/eu/vcmi/vcmi/NativeMethods.java [hunk 2]
```diff
@@ -104,4 +111,29 @@ private static Messenger requireServerMessenger()
         }
         return msg;
     }
+
+    @SuppressWarnings(Const.JNI_METHOD_SUPPRESS)
+    public static void copyFileFromUri(String sourceFileUri, String destinationFile)
```
Comment (kambala-decapitator) [inline android/vcmi-app/src/main/java/eu/vcmi/vcmi/NativeMethods.java:116]: it should go into `util/FileUtil.java`. And that file already contains basically the same code inside the directory copy method, just extract it.

**Review by kambala-decapitator — CHANGES_REQUESTED** [review]

File: launcher/firstLaunch/firstlaunch_moc.cpp (hunk 1 above)
Comment (Laserlicht) [reply launcher/firstLaunch/firstlaunch_moc.cpp:380]: To be honest. I wasn't aware of this function. I thought all functions that are called by native c++ code would be in NativeFunctions.

Feel free to provide tested code to use suggested approach.

I don't have any android build environment on my pc. The build instructions for android never worked for me. And without working ccache it's a pain to use CI for this.
Don't want to spend another hours on this. Was already too time consuming. But we needed a solution for this.

Comment (kambala-decapitator) [reply launcher/firstLaunch/firstlaunch_moc.cpp:380]: > I don't have any android build environment on my pc. The build instructions for android never worked for me

have you tried asking for help / guidance?

> And without working ccache it's a pain to use CI for this.

are you in a hurry? We're not releasing another update in a few hours :) I suggest to configure local environment to speed things up.

Comment (Laserlicht) [reply launcher/firstLaunch/firstlaunch_moc.cpp:380]: > are you in a hurry?

Not really.
But prioritys are shifting. Winter holiday season is over. So not sure how much time left in the next weeks besides small fixes. And would be great to fix this in the next 1.6.x as we have many reports on this problem.

**Comment by kambala-decapitator** [comment]
ignoring review comments is not a healthy way of collaboration. I'm against merging PR in the current state.

**Comment by Laserlicht** [comment]
> ignoring review comments is not a healthy way of collaboration. I'm against merging PR in the current state.

Insinuations are also not helpful. I was not ignoring your comments.

But my usual way is solving problems before open 10 new problems.

I wanted to know if it in general works. And for that a prototype build is needed. Because if it didn't work it's not worth to spend any time on it.

And the android build isn't that easy like e.g. for Linux. For non android devs the docs arent also not really clear (how to install sdk etc.). For example compiling fuzzylite doesn't work. Seen your comments in forum. But don't want mess with my system cmake install. Now my way is a docker container... Btw. why do we not provide dockerfiles for building? Would be much easier with this complex building mechanism.

**Comment by kambala-decapitator** [comment]
> I was not ignoring your comments (that's why I left them open).

well, you responded with "I didn't know about this way and have no time to do it like that". And your further commit was also using the "wrong" way to call JNI, from what I conclude that you don't care.

> I wanted to know if it in general works. And for that a prototype build is needed. Because if it didn't work it's not worth to spend any time on it.

then mark as draft when creating PR. Once ready for review, mark as ready for review. Leaving a similar comment in the PR upon creation also helps.

> And the android build isn't that easy like e.g. for Linux. For non android devs the docs arent also not really clear (how to install sdk etc.). For example compiling fuzzylite doesn't work. Seen your comments in forum. But don't want mess with my system cmake install.

no idea what your problem is. Install another cmake separately or just build from source, is it not an option? I'm not an android dev FYI, just able to read docs and write C-like Java. If something doesn't work / build, open an issue. (but on CI it works, right?) I don't think I have to explain to you something like `apt install openjdk`, I'm also not a linux user btw. Ask here, ask on discord (even in PM), really...

> Btw. why do we not provide dockerfiles for building? Would be much easier with this complex building mechanism.

I don't know how to use docker and not interested in that, so feel free to do that

**Comment by Laserlicht** [comment]
> > I was not ignoring your comments (that's why I left them open).
> 
> well, you responded with "I didn't know about this way and have no time to do it like that". And your further commit was also using the "wrong" way to call JNI, from what I conclude that you don't care.

Then sorry for created misunderstanding.

> no idea what your problem is. Install another cmake separately or just build from source, is it not an option? I'm not an android dev FYI, just able to read docs and write C-like Java. If something doesn't work / build, open an issue. (but on CI it works, right?) I don't think I have to explain to you something like `apt install openjdk`, I'm also not a linux user btw. Ask here, ask on discord (even in PM), really...

Talked about this issue: https://forum.vcmi.eu/t/fail-to-make-an-android-build/6264

> > Btw. why do we not provide dockerfiles for building? Would be much easier with this complex building mechanism.
> 
> I don't know how to use docker and not interested in that, so feel free to do that

Yeah, created a dockerfile to have a reproducible building environment here (not depending on any system library installed).

Place under: `docker/BuildAndroid.dockerfile` in vcmi dir:
```
FROM debian:trixie
WORKDIR /usr/local/app

RUN apt-get update && apt-get install -y openjdk-17-jdk python3 pipx cmake ccache ninja-build wget git sdkmanager xz-utils
RUN pipx ensurepath
RUN pipx install 'conan<2.0'

RUN ~/.local/bin/conan profile new conan --detect

RUN wget https://github.com/vcmi/vcmi-dependencies/releases/download/1.3/dependencies-android-arm64-v8a.txz
RUN tar -xf dependencies-android-arm64-v8a.txz -C ~/.conan
RUN rm dependencies-android-arm64-v8a.txz

ENV JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
ENV ANDROID_HOME="/usr/lib/android-sdk"
ENV PATH="$PATH:~/.local/bin"

RUN sdkmanager --install "platform-tools"
RUN sdkmanager --install "platforms;android-34"
RUN yes | sdkmanager --licenses

RUN ~/.local/bin/conan download android-ndk/r25c@:4db1be536558d833e52e862fd84d64d75c2b3656 -r conancenter

CMD ["sh", "-c", " \
        cd /vcmi ; \
        conan install . --install-folder=conan-generated --no-imports --build=never --profile:build=default --profile:host=CI/conan/android-64-ndk ; \
        cmake --preset android-daily-release ; \
        cmake --build --preset android-daily-release \
    "]
```
build with ("vcmi" as workingdir in bash): `docker build -f docker/BuildAndroid.dockerfile -t vcmi-android-build .`
run build with (each time you want to rebuild package): `docker run -it --rm -v $PWD/:/vcmi vcmi-android-build`

Not sure if there is any interest in upstreaming this file...

**Comment by kambala-decapitator** [comment]
btw here's how to fix fuzzylite build properly, haven't PRd it yet: https://github.com/kambala-decapitator/vcmi/commit/ca38be18d686167aea5026f4334f5ae9774f64ec

**Comment by Laserlicht** [comment]
Addressed suggestions.

But still not able to build it correctly (missing libs in apk). But I won't pursue it any further. It's not worth looking for the problems just for this PR. If someone want to try:
```
FROM ubuntu:noble
WORKDIR /usr/local/app

RUN apt-get update && apt-get install -y openjdk-17-jdk python3 pipx cmake ccache ninja-build wget git xz-utils
RUN pipx install 'conan<2.0'
RUN pipx install 'sdkmanager==0.6.10'

RUN ~/.local/bin/conan profile new conan --detect

RUN wget https://github.com/vcmi/vcmi-dependencies/releases/download/1.3/dependencies-android-arm64-v8a.txz
RUN tar -xf dependencies-android-arm64-v8a.txz -C ~/.conan
RUN rm dependencies-android-arm64-v8a.txz

ENV JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
ENV ANDROID_HOME="/usr/lib/android-sdk"
ENV GRADLE_USER_HOME="/vcmi/.cache/grandle"
ENV GENERATE_ONLY_BUILT_CONFIG=1

RUN ~/.local/bin/sdkmanager --install "platform-tools"
RUN ~/.local/bin/sdkmanager --install "platforms;android-34"
RUN yes | ~/.local/bin/sdkmanager --licenses

RUN ~/.local/bin/conan download android-ndk/r25c@:4db1be536558d833e52e862fd84d64d75c2b3656 -r conancenter

CMD ["sh", "-c", " \
    # switch to mounted dir
    cd /vcmi ; \
    # install conan stuff
    ~/.local/bin/conan install . --install-folder=conan-generated --no-imports --build=never --profile:build=default --profile:host=CI/conan/android-64-ndk ; \
    # link conan ndk that grandle can find it
    mkdir -p /usr/lib/android-sdk/ndk ; \
    ln -s -T ~/.conan/data/android-ndk/r25c/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin /usr/lib/android-sdk/ndk/25.2.9519653 ; \
    # build
    cmake --preset android-daily-release ; \
    cmake --build --preset android-daily-release \
"]
```

**Comment by Laserlicht** [comment]
Fixed docker. Ready now.

File: launcher/mainwindow_moc.cpp [hunk 3]
```diff
@@ -264,11 +269,25 @@ void MainWindow::dropEvent(QDropEvent* event)
...
+	{
+		auto path = QAndroidJniObject::fromString(filePath);
+		realFilePath = QAndroidJniObject::callStaticObjectMethod("eu/vcmi/vcmi/util/FileUtil", "getFilenameFromUri", "(Ljava/lang/String;)Ljava/lang/String;", path.object<jstring>()).toString();
+	}
+	else
+		realFilePath = filePath;
+
+#else
+	QString realFilePath = filePath;
+#endif
```
Comment (IvanSavenko) [inline launcher/mainwindow_moc.cpp:284]: Extract to shared method? Copy-pasted at least once

**Comment by IvanSavenko** [comment]
This should also fix failures to install game itself, not just Chronicles. Correct?

@kambala-decapitator any comments?

File: launcher/mainwindow_moc.cpp (hunk 3 above)
Comment (Laserlicht) [reply launcher/mainwindow_moc.cpp:284]: Yes, prefered file for placing this?

**Comment by Laserlicht** [comment]
> This should also fix failures to install game itself, not just Chronicles. Correct?

I hope, yes. But cannot confirm.

File: launcher/mainwindow_moc.cpp (hunk 3 above)
Comment (IvanSavenko) [reply launcher/mainwindow_moc.cpp:284]: No string preference. 
There is apparently `helper.h/cpp` pair in Launcher. Probably in there?

File: android/vcmi-app/src/main/java/eu/vcmi/vcmi/util/FileUtil.java [hunk 4]
```diff
@@ -1,18 +1,27 @@
...
 import java.io.File;
+import java.io.FileInputStream;
 import java.io.FileOutputStream;
 import java.io.IOException;
 import java.io.InputStream;
 import java.io.OutputStream;
 import java.util.List;
+import java.lang.Exception;
 
+import eu.vcmi.vcmi.Const;
```
Comment (kambala-decapitator) [inline android/vcmi-app/src/main/java/eu/vcmi/vcmi/util/FileUtil.java:24]: please keep imports alphabetically sorted

File: android/vcmi-app/src/main/java/eu/vcmi/vcmi/util/FileUtil.java [hunk 5]
```diff
@@ -104,4 +113,50 @@ private static void copyStream(InputStream source, OutputStream target) throws I
...
+            Log.e("copyFileFromUri failed: ", e);
+        }
+    }
+
+    @SuppressWarnings(Const.JNI_METHOD_SUPPRESS)
+    private static String getFilenameFromUri(String sourceFileUri)
+    {
+        try
+        {
+            String fileName = "";
```
Comment (kambala-decapitator) [inline android/vcmi-app/src/main/java/eu/vcmi/vcmi/util/FileUtil.java:139]: move it outside `try` and have a single `return` in the end of the method

File: docs/developers/Building_Android.md [hunk 6]
```diff
@@ -68,3 +68,17 @@ cmake --build ../build
 ```
 
 You can also see a more detailed walkthrough on CMake configuration at [How to build VCMI (macOS)](./Building_macOS.md).
+
+## Docker
+
+For developing it's also possible to use docker to build an android APK. As requirement only a installed docker is needed. The container image contains all other prerequisites.
```
Comment (kambala-decapitator) [inline docs/developers/Building_Android.md:74]:
```suggestion
For developing it's also possible to use Docker to build android APK. The only requirement is to have Docker installed. The container image contains all the other prerequisites.
```

File: docs/developers/Building_Android.md [hunk 7]
```diff
@@ -68,3 +68,17 @@ cmake --build ../build
...
+
+To build using docker just open a terminal with `vcmi` as working directory.
+
+Build the image with (only needed once):
+`docker build -f docker/BuildAndroid.dockerfile -t vcmi-android-build .`
+
+After building the image you can compile vcmi with:
+`docker run -it --rm -v $PWD/:/vcmi vcmi-android-build`
+
+The current dockerfile is ARM64 only but can adjusted manually for ARM32.
```
Comment (kambala-decapitator) [inline docs/developers/Building_Android.md:84]: please reflect it in the name of the dockerfile. Also, correct names are: armv7 for ARM32 and aarch64 for ARM64.

File: docker/BuildAndroid.dockerfile [hunk 8]
```diff
@@ -0,0 +1,40 @@
...
+ENV JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
+ENV ANDROID_HOME="/usr/lib/android-sdk"
+ENV GRADLE_USER_HOME="/vcmi/.cache/grandle"
+ENV GENERATE_ONLY_BUILT_CONFIG=1
+
+RUN sdkmanager --install "platform-tools"
+RUN sdkmanager --install "platforms;android-34"
+RUN yes | sdkmanager --licenses
+
+RUN conan download android-ndk/r25c@:4db1be536558d833e52e862fd84d64d75c2b3656 -r conancenter
```
Comment (kambala-decapitator) [inline docker/BuildAndroid.dockerfile:27]: is it not downloaded automatically when using profile with NDK?

File: launcher/helper.h [hunk 9]
```diff
@@ -10,9 +10,11 @@
 #pragma once
 
 class QObject;
+class QString;
```
Comment (kambala-decapitator) [inline launcher/helper.h:13]: you're using QString as a fully defined type and not as a reference/pointer, hence forward declaration is incorrect - include the header instead

File: launcher/modManager/chroniclesextractor.cpp [hunk 10]
```diff
@@ -226,14 +236,22 @@ void ChroniclesExtractor::installChronicles(QStringList exe)
...
 		// Qt can handle those like it does regular files
 		// however, innoextract fails to open such files
 		// so make a copy in directory to which vcmi always has full access and operate on it
 		QString filepath = tempDir.filePath("chr.exe");
+		logGlobal->info("Copying offline installer from '%s' to '%s'", f.toStdString(), filepath.toStdString());
+#ifdef VCMI_ANDROID
+		{
+			auto srcStr = QAndroidJniObject::fromString(f);
+			auto dstStr = QAndroidJniObject::fromString(filepath);
+			QAndroidJniObject::callStaticObjectMethod("eu/vcmi/vcmi/util/FileUtil", "copyFileFromUri", "(Ljava/lang/String;Ljava/lang/String;)V", srcStr.object<jstring>(), dstStr.object<jstring>());
```
Comment (kambala-decapitator) [inline launcher/modManager/chroniclesextractor.cpp:250]: looks copy-pasted

File: android/vcmi-app/src/main/java/eu/vcmi/vcmi/util/FileUtil.java [hunk 11]
```diff
@@ -104,4 +113,50 @@ private static void copyStream(InputStream source, OutputStream target) throws I
             target.write(buffer, 0, read);
         }
     }
+
+    @SuppressWarnings(Const.JNI_METHOD_SUPPRESS)
+    private static void copyFileFromUri(String sourceFileUri, String destinationFile)
+    {
+        try
+        {
+            final Context ctx = SDL.getContext();
```
Comment (kambala-decapitator) [inline android/vcmi-app/src/main/java/eu/vcmi/vcmi/util/FileUtil.java:122]: pass context from C++ as main activity, Qt provides a method to get it. Treat SDL as non-existant in the launcher.

File: android/vcmi-app/src/main/java/eu/vcmi/vcmi/util/FileUtil.java [hunk 12]
```diff
@@ -104,4 +113,50 @@ private static void copyStream(InputStream source, OutputStream target) throws I
...
+    }
+
+    @SuppressWarnings(Const.JNI_METHOD_SUPPRESS)
+    private static String getFilenameFromUri(String sourceFileUri)
+    {
+        try
+        {
+            String fileName = "";
+
+            final Context ctx = SDL.getContext();
```
Comment (kambala-decapitator) [inline android/vcmi-app/src/main/java/eu/vcmi/vcmi/util/FileUtil.java:141]: same

**Comment by kambala-decapitator** [comment]
btw are there any checks that the passed exe is actually chronicles and not something random that can be extracted?

**Comment by Laserlicht** [comment]
> btw are there any checks that the passed exe is actually chronicles and not something random that can be extracted?

Yes, there is a logic after extracting (there was also one before, but @IvanSavenko removed it to simplify process).

File: launcher/modManager/chroniclesextractor.cpp (hunk 10 above)
Comment (Laserlicht) [reply launcher/modManager/chroniclesextractor.cpp:250]: Don't see a better solution here. Suggestions?

File: docker/BuildAndroid.dockerfile (hunk 8 above)
Comment (Laserlicht) [reply docker/BuildAndroid.dockerfile:27]: Yes. But it's also here because this step is better to do in image building part, not in executing script.

File: launcher/modManager/chroniclesextractor.cpp (hunk 10 above)
Comment (kambala-decapitator) [reply launcher/modManager/chroniclesextractor.cpp:250]: just extract it to a separate function (e.g. put it to Helper) and call it in both places.

```cpp
void performNativeCopy(QString src, QString dst)
{
	auto srcStr = QAndroidJniObject::fromString(f);
	auto dstStr = QAndroidJniObject::fromString(filepath);
	QAndroidJniObject::callStaticObjectMethod("eu/vcmi/vcmi/util/FileUtil", "copyFileFromUri", "(Ljava/lang/String;Ljava/lang/String;)V", srcStr.object<jstring>(), dstStr.object<jstring>());
}
```

Comment (Laserlicht) [reply launcher/modManager/chroniclesextractor.cpp:250]: Ah. Misunderstood you first.

Makes sense!

**Comment by Laserlicht** [comment]
Done open points. Tested again on my device - works.

File: launcher/helper.cpp [hunk 13]
```diff
@@ -44,4 +49,30 @@ void enableScrollBySwiping(QObject * scrollTarget)
...
+}
+
+void performNativeCopy(QString src, QString dst)
+{
+#ifdef VCMI_ANDROID
+	auto srcStr = QAndroidJniObject::fromString(src);
+	auto dstStr = QAndroidJniObject::fromString(dst);
+	QAndroidJniObject::callStaticObjectMethod("eu/vcmi/vcmi/util/FileUtil", "copyFileFromUri", "(Ljava/lang/String;Ljava/lang/String;Landroid/content/Context;)V", srcStr.object<jstring>(), dstStr.object<jstring>(), QtAndroid::androidContext().object());
+#else
+	QFile(src).copy(dst);
```
Comment (kambala-decapitator) [inline launcher/helper.cpp:75]:
```suggestion
	QFile::copy(src, dst);
```

**Review by kambala-decapitator — APPROVED** [review]
all good now, just do a minor adjustment please
