### PR TITLE
quick army managment click next

### LINKED ISSUE #2929: There is no possibility of checking the day and number of towns/players in the box in down right corner
**Describe the bug**
OH shows these informations when clicked on castle or hero box in down right corner:
affasd
afafas
VCMI doesn't provide this info
**Version**
 - OS: [Windows 10]
 - Version: [VCMI 1.3.2]

### PR DESCRIPTION
**Pull request by Laserlicht**
fixes #2929

Any drawbacks?
In my opinion only the latest activated object (under cursor) has to receive click event.

Also fixes problem with radial menu in infobox with dimming.

### CODE REVIEW

**Comment by dydzio0614** [comment]
battlefield is something that from the top of my head may have potential for drawback - hexes, creatures, clicking hero to open spellbook etc.

**Comment by Laserlicht** [comment]
@dydzio0614 Yes you're right. There was some minor problems on battlefield. So I made it optionally usable.

File: client/adventureMap/CInfoBar.cpp [hunk 1]
```diff
@@ -289,17 +289,15 @@ void CInfoBar::tick(uint32_t msPassed)
...
 
-void CInfoBar::clickReleased(const Point & cursorPosition)
+void CInfoBar::clickReleased(const Point & cursorPosition, bool lastActivated)
 {
 	timerCounter = 0;
 	removeUsedEvents(TIME); //expiration trigger from just clicked element is not valid anymore
 
 	if(state == HERO || state == TOWN)
 	{
-		if(settings["gameTweaks"]["infoBarCreatureManagement"].Bool())
```
Comment (Nordsoft91) [inline client/adventureMap/CInfoBar.cpp:299]: Not used anymore?

Comment (Laserlicht) [reply client/adventureMap/CInfoBar.cpp:299]: Still used to deactivate this feature.
