### PR TITLE
fix path not updated after cheat

### LINKED ISSUE #5846: Path not updated after cheat
**Describe the bug**
Path is not updated after cheat

**To Reproduce**

1. Start map
2. use all movement points with hero
3. select new destination (path is red)
4. use `vcmigod`
5. path is still red and will get only green if clicking on other point

**Expected behavior**
Path should be green immediately after using cheat

**Version**

- OS: Linux
- Version: develop

### PR DESCRIPTION
**Pull request by Laserlicht**
fix #5846

### CODE REVIEW

File: client/CPlayerInterface.cpp [hunk 1]
```diff
@@ -498,6 +498,7 @@ void CPlayerInterface::heroMovePointsChanged(const CGHeroInstance * hero)
 	if (makingTurn && hero->tempOwner == playerID)
 		adventureInt->onHeroChanged(hero);
 	invalidatePaths();
+	GAME->interface()->localState->verifyPath(hero);
```
Comment (IvanSavenko) [inline client/CPlayerInterface.cpp]:
```suggestion
	localState->verifyPath(hero);
```
