### PR TITLE
Nullkiller ai tweaks

### LINKED ISSUE #3227: The abilities on an unit screen do not scroll on the touch device
Also scroll buttons doesn't working

Screenshot_20231126_130804

OS: [Android]
 - Version: 1.3.2

### PR DESCRIPTION
**Pull request by DjWarmonger**
Many AI tweaks:

- AI will now pick Pandoras as they are valuable objects
- AI will pick Prisons. At the same time I fixed #3227 https://bugs.vcmi.eu/view.php?id=3227
- Fixed exchange dialogs which in particular stopped AI from joining armies from Banks, Pandoras and Diplomacy when it already had 7 stacks in army.
- AI will attack anemy heroes agressively. This in fact makes it able to win in finite time.
- Various value tweak here and there

### CODE REVIEW

File: AI/Nullkiller/Engine/PriorityEvaluator.cpp [hunk 1]
```diff
@@ -273,7 +299,8 @@ float RewardEvaluator::getEnemyHeroStrategicalValue(const CGHeroInstance * enemy
 		vstd::amax(objectValue, getStrategicalValue(obj));
 	}
 
-	return objectValue / 2.0f + enemy->level / 15.0f;
+	//AI should absolutely prioritize killing enemy heroes, even scouts
+	return std::min(1.0f, objectValue * 0.9f + (1.0f - (1.0f / (1 + enemy->level))));
```
Comment (nullkiller) [inline AI/Nullkiller/Engine/PriorityEvaluator.cpp:303]: I think 1.0 it is too high. Scout should not be higher than capturing town with fort in current turn. And better add some basic value than use min(1, value). so that 2 lvl hero is more valuable than 1 lvl. Also we can increase this radius getOneTurnAccessibleObjects.
Just a case which I do not want to get broken. When enemy hero approaches a town you buy and put scouts not far from it and hero attacks them loosing movement points. While you bring your main army to protect the town. This is how original AI did afaik.
Mine idea here is simple. AI captures town and all scouts around become a treat for it. Thus they gain additional strategical value equivalent to this town and AI should eliminate them as well. Probably we can express hero value as a separate fuzzy variable to be able to write more flexible rules. If main hero will start pursuing a scout and the last will constantly run away we might end up having main hero just wasting movement points which is not nice as well. Having a separate variable will allow us writing rules like 
if enemy_hero is weak and turn is now then value is bit_high (or high)
if enemy_hero is strong and turn is now then value is highest

File: server/CGameHandler.cpp [hunk 2]
```diff
@@ -5572,13 +5572,21 @@ bool CGameHandler::isAllowedExchange(ObjectInstanceID id1, ObjectInstanceID id2)
...
+		if (dialog)
+		{
+			auto topArmy = dialog->exchangingArmies.at(0);
+			auto bottomArmy = dialog->exchangingArmies.at(1);
+
+			if (topArmy == o1 && bottomArmy == o2)
 				return true;
 
-			if (dialog->exchangingArmies.at(1) == o1 && dialog->exchangingArmies.at(0) == o2)
+			if (bottomArmy == o1 && topArmy == o2)
```
Comment (Nordsoft91) [inline server/CGameHandler.cpp:5589]: maybe combining those conditions is better
(top==1 && bot==2) || (top==2 && bot==1)

File: AI/Nullkiller/Engine/PriorityEvaluator.cpp (hunk 1 above)
Comment (Nordsoft91) [inline AI/Nullkiller/Engine/PriorityEvaluator.cpp:303]: could you please add a comment about this formula?

**Review by Nordsoft91 — APPROVED** [review]

File: AI/Nullkiller/Engine/PriorityEvaluator.cpp (hunk 1 above)
Comment (DjWarmonger) [reply AI/Nullkiller/Engine/PriorityEvaluator.cpp:303]: Well, I tested this in game AI vs AI and it works. AI finally kills the scouts in lategame instead of playing ping-pong, capturing a town and losing it next turn for weeks. Killing 4 scouts in a a turn is a winning strategy and running past them is not.

Comment (DjWarmonger) [reply AI/Nullkiller/Engine/PriorityEvaluator.cpp:303]: ALso, I think enemy shouldn't know hero level in first place :P

File: AI/Nullkiller/Engine/PriorityEvaluator.cpp [hunk 3]
```diff
@@ -114,10 +116,32 @@ uint64_t getCreatureBankArmyReward(const CGObjectInstance * target, const CGHero
...
-	for(auto c : creatures)
+	const auto& slots = hero->Slots();
+	ui64 weakestStackPower = 0;
+	if (slots.size() >= GameConstants::ARMY_SIZE)
+	{
+		//No free slot, we might discard our weakest stack
+		weakestStackPower = std::numeric_limits<ui64>().max();
+		for (const auto stack : slots)
+		{
+			vstd::amin(weakestStackPower, stack.second->getPower());
```
Comment (Nordsoft91) [inline AI/Nullkiller/Engine/PriorityEvaluator.cpp:127]: stack.second could be a nullptr and game will crash

File: AI/Nullkiller/Engine/PriorityEvaluator.cpp (hunk 1 above)
Comment (nullkiller) [reply AI/Nullkiller/Engine/PriorityEvaluator.cpp:309]: AI knows a bit more about you than human unfortunately. It knows exact army structure and your stats. And this is true for both  VCAI and Nullkiller afaik. But I agree that it should not. So this more a problem of client/server architecture that this info is available to AI. If AI knows - it is possible to build modified client which will also show all these stats.
Ok, in current circumstances this might be a better solution. But what I actually wanted was "What you say would make more sense if AI actually tried to buy units in a town to defend it". Still I think 1 is to high. Lets try 0.7f + instead of std:min(1, and see if it gives what you want.

File: AI/Nullkiller/Engine/PriorityEvaluator.cpp (hunk 3 above)
Comment (DjWarmonger) [reply AI/Nullkiller/Engine/PriorityEvaluator.cpp:127]: Not really. Stack should always have defined creature type - if it doesn't and AI has them in their army, then something is already **very** wrong.

File: AI/Nullkiller/Engine/PriorityEvaluator.cpp (hunk 1 above)
Comment (DjWarmonger) [reply AI/Nullkiller/Engine/PriorityEvaluator.cpp:309]: But it means that 1.0f is the upper cap and the value can still be lower for lesser objects.

Comment (nullkiller) [reply AI/Nullkiller/Engine/PriorityEvaluator.cpp:309]: I misunderstood it, sorry. Yes this way it looks ok.

**Review by nullkiller — APPROVED** [review]
