### PR TITLE
Fix violated assert(direction != BattleHex::NONE) 

### LINKED ISSUE #6282: `Segmentation fault` when trying to buy a unit and during the battle `Error: cannot find a hex to attack hex 1 from!`
Git version https://github.com/vcmi/vcmi/commit/c7a1558c81f6f0c85454471d9c0fc0beb2d4e68f

Gentoo Linux.

Started from the terminal, part of logs here:

```
OI 0, mp 1186, res 1, start (92 25 0), end (92 26 0), attack (0 0 0), fow 
OI 0, mp 1086, res 1, start (92 26 0), end (92 27 0), attack (0 0 0), fow 
OI 0, mp 1086, res 1, start (92 26 0), end (92 27 0), attack (0 0 0), fow 
OI 0, mp 986, res 1, start (92 27 0), end (92 28 0), attack (0 0 0), fow 
OI 0, mp 986, res 1, start (92 27 0), end (92 28 0), attack (0 0 0), fow 
OI 0, mp 845, res 1, start (92 28 0), end (91 29 0), attack (0 0 0), fow 
OI 0, mp 845, res 1, start (92 28 0), end (91 29 0), attack (0 0 0), fow 
OI 0, mp 745, res 1, start (91 29 0), end (90 29 0), attack (0 0 0), fow 
OI 0, mp 745, res 1, start (91 29 0), end (90 29 0), attack (0 0 0), fow 
OI 0, mp 645, res 1, start (90 29 0), end (91 29 0), attack (0 0 0), fow 
OI 0, mp 545, res 1, start (91 29 0), end (92 29 0), attack (0 0 0), fow 
OI 0, mp 445, res 1, start (92 29 0), end (93 29 0), attack (0 0 0), fow 
OI 0, mp 345, res 3, start (93 29 0), end (94 29 0), attack (0 0 0), fow 
OI 0, mp 645, res 1, start (90 29 0), end (91 29 0), attack (0 0 0), fow 
OI 0, mp 645, res 1, start (90 29 0), end (91 29 0), attack (0 0 0), fow 
OI 0, mp 545, res 1, start (91 29 0), end (92 29 0), attack (0 0 0), fow 
OI 0, mp 545, res 1, start (91 29 0), end (92 29 0), attack (0 0 0), fow 
OI 0, mp 445, res 1, start (92 29 0), end (93 29 0), attack (0 0 0), fow 
OI 0, mp 445, res 1, start (92 29 0), end (93 29 0), attack (0 0 0), fow 
OI 0, mp 345, res 3, start (93 29 0), end (94 29 0), attack (0 0 0), fow 
OI 0, mp 345, res 3, start (93 29 0), end (94 29 0), attack (0 0 0), fow 
OI 0, mp 245, res 1, start (93 29 0), end (92 29 0), attack (0 0 0), fow 
OI 0, mp 145, res 1, start (92 29 0), end (91 29 0), attack (0 0 0), fow 
OI 0, mp 0, res 1, start (91 29 0), end (90 30 0), attack (0 0 0), fow 
OI 0, mp 245, res 1, start (93 29 0), end (92 29 0), attack (0 0 0), fow 
OI 0, mp 245, res 1, start (93 29 0), end (92 29 0), attack (0 0 0), fow 
OI 0, mp 145, res 1, start (92 29 0), end (91 29 0), attack (0 0 0), fow 
OI 0, mp 145, res 1, start (92 29 0), end (91 29 0), attack (0 0 0), fow 
OI 0, mp 0, res 1, start (91 29 0), end (90 30 0), attack (0 0 0), fow 
OI 0, mp 0, res 1, start (91 29 0), end (90 30 0), attack (0 0 0), fow 
OI 20, mp 235, res 1, start (88 95 0), end (89 96 0), attack (0 0 0), fow 
OI 20, mp 135, res 1, start (89 96 0), end (90 96 0), attack (0 0 0), fow 
OI 20, mp 0, res 1, start (90 96 0), end (91 97 0), attack (0 0 0), fow 
OI 18, mp 1654, res 1, start (83 103 0), end (82 104 0), attack (0 0 0), fow 
OI 18, mp 1529, res 1, start (82 104 0), end (81 104 0), attack (0 0 0), fow 
OI 18, mp 1404, res 1, start (81 104 0), end (80 104 0), attack (0 0 0), fow 
OI 18, mp 1228, res 1, start (80 104 0), end (79 105 0), attack (0 0 0), fow 
OI 18, mp 1103, res 1, start (79 105 0), end (78 105 0), attack (0 0 0), fow 
OI 18, mp 978, res 1, start (78 105 0), end (77 105 0), attack (0 0 0), fow 
OI 18, mp 853, res 1, start (77 105 0), end (76 105 0), attack (0 0 0), fow 
OI 18, mp 728, res 1, start (76 105 0), end (75 105 0), attack (0 0 0), fow 
OI 18, mp 603, res 1, start (75 105 0), end (74 105 0), attack (0 0 0), fow 
OI 18, mp 478, res 1, start (74 105 0), end (73 105 0), attack (0 0 0), fow 
OI 18, mp 302, res 1, start (73 105 0), end (72 104 0), attack (0 0 0), fow 
OI 18, mp 126, res 1, start (72 104 0), end (73 103 0), attack (0 0 0), fow 
OI 18, mp 0, res 1, start (73 103 0), end (72 102 0), attack (0 0 0), fow 
OI 28, mp 1600, res 1, start (16 21 0), end (17 21 0), attack (0 0 0), fow 
OI 28, mp 1525, res 1, start (17 21 0), end (18 21 0), attack (0 0 0), fow 
OI 28, mp 1450, res 1, start (18 21 0), end (19 21 0), attack (0 0 0), fow 
OI 28, mp 1375, res 1, start (19 21 0), end (20 21 0), attack (0 0 0), fow 
OI 28, mp 1269, res 1, start (20 21 0), end (21 20 0), attack (0 0 0), fow 
OI 28, mp 1194, res 1, start (21 20 0), end (21 19 0), attack (0 0 0), fow 
OI 28, mp 1088, res 3, start (21 19 0), end (22 18 0), attack (0 0 0), fow 
OI 99, mp 1755, res 1, start (22 18 0), end (22 17 0), attack (0 0 0), fow 
OI 28, mp 982, res 1, start (21 19 0), end (22 18 0), attack (0 0 0), fow 
OI 28, mp 907, res 3, start (22 18 0), end (22 17 0), attack (0 0 0), fow 
OI 15, mp 1350, res 1, start (5 21 0), end (5 20 0), attack (0 0 0), fow 
OI 15, mp 1138, res 1, start (5 20 0), end (4 19 0), attack (0 0 0), fow 
OI 15, mp 988, res 1, start (4 19 0), end (3 19 0), attack (1 19 0), fow 
We received YesNoDialog for not our player...
OI 15, mp 776, res 1, start (3 19 0), end (2 18 0), attack (0 0 0), fow 
We received InfoWindow for not our player...
OI 28, mp 807, res 1, start (22 18 0), end (22 19 0), attack (0 0 0), fow 
OI 28, mp 707, res 1, start (22 19 0), end (22 20 0), attack (0 0 0), fow 
OI 28, mp 566, res 1, start (22 20 0), end (23 21 0), attack (0 0 0), fow 
OI 28, mp 491, res 1, start (23 21 0), end (24 21 0), attack (0 0 0), fow 
OI 28, mp 385, res 1, start (24 21 0), end (25 22 0), attack (0 0 0), fow 
OI 28, mp 279, res 1, start (25 22 0), end (26 23 0), attack (0 0 0), fow 
OI 28, mp 204, res 1, start (26 23 0), end (27 23 0), attack (0 0 0), fow 
OI 28, mp 129, res 1, start (27 23 0), end (28 23 0), attack (0 0 0), fow 
OI 28, mp 0, res 1, start (28 23 0), end (29 24 0), attack (0 0 0), fow 
OI 99, mp 1680, res 1, start (22 17 0), end (22 18 0), attack (0 0 0), fow 
OI 99, mp 1580, res 1, start (22 18 0), end (22 19 0), attack (0 0 0), fow 
OI 99, mp 1480, res 1, start (22 19 0), end (22 20 0), attack (0 0 0), fow 
OI 99, mp 1339, res 1, start (22 20 0), end (23 21 0), attack (0 0 0), fow 
OI 99, mp 1264, res 1, start (23 21 0), end (24 21 0), attack (0 0 0), fow 
OI 99, mp 1158, res 1, start (24 21 0), end (25 22 0), attack (0 0 0), fow 
OI 99, mp 1052, res 1, start (25 22 0), end (26 23 0), attack (0 0 0), fow 
OI 99, mp 952, res 1, start (26 23 0), end (26 24 0), attack (0 0 0), fow 
OI 99, mp 852, res 1, start (26 24 0), end (25 24 0), attack (0 0 0), fow 
We received YesNoDialog for not our player...
We received InfoWindow for not our player...
OI 99, mp 711, res 1, start (25 24 0), end (24 25 0), attack (0 0 0), fow 
OI 99, mp 570, res 1, start (24 25 0), end (23 26 0), attack (0 0 0), fow 
OI 99, mp 470, res 1, start (23 26 0), end (22 26 0), attack (0 0 0), fow 
OI 99, mp 329, res 1, start (22 26 0), end (21 25 0), attack (0 0 0), fow 
We received InfoWindow for not our player...
OI 99, mp 188, res 1, start (21 25 0), end (22 26 0), attack (0 0 0), fow 
OI 99, mp 0, res 1, start (22 26 0), end (23 26 0), attack (0 0 0), fow 
OI 15, mp 564, res 1, start (2 18 0), end (3 19 0), attack (0 0 0), fow 
OI 15, mp 414, res 1, start (3 19 0), end (4 19 0), attack (0 0 0), fow 
OI 15, mp 202, res 1, start (4 19 0), end (5 18 0), attack (0 0 0), fow 
OI 15, mp 0, res 1, start (5 18 0), end (6 17 0), attack (0 0 0), fow 
OI 23, mp 1460, res 1, start (59 23 0), end (58 23 0), attack (0 0 0), fow 
OI 23, mp 1360, res 1, start (58 23 0), end (57 23 0), attack (0 0 0), fow 
OI 23, mp 1219, res 1, start (57 23 0), end (56 22 0), attack (0 0 0), fow 
OI 23, mp 1119, res 1, start (56 22 0), end (55 22 0), attack (0 0 0), fow 
OI 23, mp 978, res 1, start (55 22 0), end (54 21 0), attack (0 0 0), fow 
OI 23, mp 878, res 1, start (54 21 0), end (53 21 0), attack (0 0 0), fow 
OI 23, mp 737, res 1, start (53 21 0), end (52 20 0), attack (0 0 0), fow 
OI 23, mp 596, res 1, start (52 20 0), end (51 19 0), attack (0 0 0), fow 
OI 23, mp 455, res 1, start (51 19 0), end (50 18 0), attack (0 0 0), fow 
OI 23, mp 314, res 1, start (50 18 0), end (49 17 0), attack (0 0 0), fow 
OI 23, mp 173, res 1, start (49 17 0), end (50 16 0), attack (0 0 0), fow 
OI 23, mp 0, res 1, start (50 16 0), end (50 15 0), attack (0 0 0), fow 
OI 41, mp 1400, res 1, start (74 52 0), end (74 51 0), attack (0 0 0), fow (71 46 0), (72 46 0), (73 46 0), (74 46 0), (75 46 0), (76 47 0), (77 48 0), (78 49 0), 
We received YesNoDialog for not our player...
We received InfoWindow for not our player...
OI 4, mp 1460, res 1, start (23 91 0), end (22 91 0), attack (0 0 0), fow 
OI 4, mp 1360, res 1, start (22 91 0), end (21 91 0), attack (0 0 0), fow 
OI 4, mp 1219, res 1, start (21 91 0), end (20 90 0), attack (0 0 0), fow 
OI 4, mp 1078, res 1, start (20 90 0), end (19 89 0), attack (0 0 0), fow 
OI 4, mp 937, res 1, start (19 89 0), end (18 88 0), attack (0 0 0), fow 
OI 4, mp 837, res 1, start (18 88 0), end (17 88 0), attack (0 0 0), fow 
OI 4, mp 696, res 1, start (17 88 0), end (16 87 0), attack (0 0 0), fow 
OI 4, mp 555, res 1, start (16 87 0), end (15 86 0), attack (0 0 0), fow 
We received InfoWindow for not our player...
OI 6, mp 1559, res 1, start (24 86 0), end (23 87 0), attack (0 0 0), fow 
OI 6, mp 1418, res 1, start (23 87 0), end (22 88 0), attack (0 0 0), fow 
OI 119, mp 1460, res 1, start (16 98 0), end (16 97 0), attack (0 0 0), fow 
OI 119, mp 1360, res 1, start (16 97 0), end (16 96 0), attack (0 0 0), fow 
OI 119, mp 1260, res 1, start (16 96 0), end (16 95 0), attack (0 0 0), fow 
OI 119, mp 1119, res 1, start (16 95 0), end (15 94 0), attack (0 0 0), fow 
OI 119, mp 1019, res 1, start (15 94 0), end (15 93 0), attack (0 0 0), fow 
OI 119, mp 919, res 1, start (15 93 0), end (15 92 0), attack (0 0 0), fow 
OI 119, mp 778, res 1, start (15 92 0), end (16 91 0), attack (0 0 0), fow 
OI 119, mp 637, res 1, start (16 91 0), end (17 90 0), attack (0 0 0), fow 
OI 119, mp 496, res 1, start (17 90 0), end (18 89 0), attack (0 0 0), fow 
OI 119, mp 396, res 1, start (18 89 0), end (19 89 0), attack (0 0 0), fow 
OI 119, mp 296, res 1, start (19 89 0), end (20 89 0), attack (0 0 0), fow 
OI 119, mp 196, res 1, start (20 89 0), end (21 89 0), attack (0 0 0), fow 
OI 119, mp 0, res 3, start (21 89 0), end (22 88 0), attack (0 0 0), fow 
OI 6, mp 1318, res 1, start (22 88 0), end (23 88 0), attack (0 0 0), fow 
OI 6, mp 1218, res 1, start (23 88 0), end (24 88 0), attack (0 0 0), fow 
OI 6, mp 1118, res 1, start (24 88 0), end (25 88 0), attack (0 0 0), fow 
OI 6, mp 977, res 1, start (25 88 0), end (26 87 0), attack (0 0 0), fow 
OI 6, mp 836, res 1, start (26 87 0), end (27 86 0), attack (0 0 0), fow 
OI 6, mp 695, res 1, start (27 86 0), end (28 85 0), attack (0 0 0), fow 
OI 6, mp 554, res 1, start (28 85 0), end (29 84 0), attack (29 84 0), fow (30 79 0), 
We received YesNoDialog for not our player...
OI 45, mp 1660, res 1, start (28 103 0), end (27 103 0), attack (0 0 0), fow 
OI 45, mp 1519, res 1, start (27 103 0), end (26 102 0), attack (0 0 0), fow 
OI 45, mp 1444, res 1, start (26 102 0), end (25 102 0), attack (0 0 0), fow 
OI 45, mp 1369, res 1, start (25 102 0), end (24 102 0), attack (0 0 0), fow 
OI 45, mp 1294, res 1, start (24 102 0), end (23 102 0), attack (0 0 0), fow 
OI 45, mp 1188, res 1, start (23 102 0), end (22 101 0), attack (0 0 0), fow 
OI 45, mp 1113, res 1, start (22 101 0), end (22 100 0), attack (0 0 0), fow 
OI 45, mp 1007, res 1, start (22 100 0), end (21 99 0), attack (0 0 0), fow 
OI 45, mp 901, res 1, start (21 99 0), end (20 98 0), attack (0 0 0), fow 
OI 45, mp 795, res 1, start (20 98 0), end (19 97 0), attack (0 0 0), fow 
OI 45, mp 720, res 1, start (19 97 0), end (18 97 0), attack (0 0 0), fow 
OI 45, mp 645, res 1, start (18 97 0), end (17 97 0), attack (0 0 0), fow 
OI 45, mp 504, res 1, start (17 97 0), end (16 96 0), attack (0 0 0), fow 
OI 45, mp 404, res 1, start (16 96 0), end (16 95 0), attack (0 0 0), fow 
OI 45, mp 304, res 1, start (16 95 0), end (16 94 0), attack (0 0 0), fow 
OI 45, mp 163, res 1, start (16 94 0), end (15 93 0), attack (0 0 0), fow 
OI 45, mp 0, res 1, start (15 93 0), end (15 92 0), attack (0 0 0), fow 
OI 6, mp 413, res 1, start (29 84 0), end (28 85 0), attack (0 0 0), fow 
OI 6, mp 272, res 1, start (28 85 0), end (27 86 0), attack (0 0 0), fow 
OI 6, mp 131, res 1, start (27 86 0), end (26 87 0), attack (0 0 0), fow 
OI 6, mp 0, res 1, start (26 87 0), end (25 88 0), attack (0 0 0), fow 
OI 4, mp 414, res 1, start (15 86 0), end (16 87 0), attack (0 0 0), fow 
OI 4, mp 273, res 1, start (16 87 0), end (17 88 0), attack (0 0 0), fow 
OI 4, mp 173, res 1, start (17 88 0), end (18 88 0), attack (0 0 0), fow 
OI 4, mp 0, res 1, start (18 88 0), end (19 89 0), attack (0 0 0), fow 
OI 41, mp 1259, res 1, start (74 51 0), end (73 52 0), attack (0 0 0), fow 
OI 41, mp 1118, res 1, start (73 52 0), end (72 53 0), attack (0 0 0), fow 
OI 41, mp 977, res 1, start (72 53 0), end (71 54 0), attack (0 0 0), fow 
OI 41, mp 836, res 1, start (71 54 0), end (70 55 0), attack (0 0 0), fow (65 58 0), (66 59 0), (67 60 0), (68 60 0), (69 60 0), (70 60 0), (71 60 0), 
OI 41, mp 736, res 1, start (70 55 0), end (70 56 0), attack (0 0 0), fow (64 58 0), (65 59 0), (73 59 0), (66 60 0), (72 60 0), (67 61 0), (68 61 0), (69 61 0), (70 61 0), (71 61 0), 
OI 41, mp 636, res 1, start (70 56 0), end (70 57 0), attack (0 0 0), fow (64 59 0), (74 59 0), (65 60 0), (73 60 0), (66 61 0), (72 61 0), (67 62 0), (68 62 0), (69 62 0), (70 62 0), (71 62 0), 
OI 41, mp 495, res 1, start (70 57 0), end (71 58 0), attack (0 0 0), fow (75 58 0), (75 59 0), (74 60 0), (75 60 0), (73 61 0), (74 61 0), (72 62 0), (73 62 0), (68 63 0), (69 63 0), (70 63 0), (71 63 0), (72 63 0), 
OI 41, mp 354, res 3, start (71 58 0), end (72 59 0), attack (0 0 0), fow 
We received InfoWindow for not our player...
OI 41, mp 254, res 1, start (71 58 0), end (72 58 0), attack (0 0 0), fow (76 57 0), (76 58 0), (76 59 0), (76 60 0), (75 61 0), (74 62 0), (73 63 0), 
OI 41, mp 113, res 1, start (72 58 0), end (73 57 0), attack (0 0 0), fow (77 56 0), (77 57 0), (77 58 0), (77 59 0), 
OI 41, mp 0, res 1, start (73 57 0), end (73 56 0), attack (0 0 0), fow 
We received InfoWindow for not our player...
OI 42, mp 1619, res 1, start (17 74 0), end (16 75 0), attack (0 0 0), fow 
OI 42, mp 1478, res 1, start (16 75 0), end (15 76 0), attack (0 0 0), fow 
OI 42, mp 1378, res 1, start (15 76 0), end (15 77 0), attack (0 0 0), fow 
OI 42, mp 1278, res 1, start (15 77 0), end (15 78 0), attack (0 0 0), fow 
OI 42, mp 1178, res 1, start (15 78 0), end (15 79 0), attack (0 0 0), fow 
OI 42, mp 1078, res 1, start (15 79 0), end (15 80 0), attack (0 0 0), fow 
OI 42, mp 978, res 1, start (15 80 0), end (15 81 0), attack (0 0 0), fow 
OI 42, mp 878, res 1, start (15 81 0), end (15 82 0), attack (0 0 0), fow 
OI 42, mp 778, res 1, start (15 82 0), end (15 83 0), attack (0 0 0), fow 
OI 42, mp 637, res 1, start (15 83 0), end (16 84 0), attack (0 0 0), fow 
OI 42, mp 537, res 1, start (16 84 0), end (16 85 0), attack (0 0 0), fow 
OI 42, mp 437, res 1, start (16 85 0), end (16 86 0), attack (0 0 0), fow 
OI 42, mp 337, res 1, start (16 86 0), end (16 87 0), attack (0 0 0), fow 
OI 42, mp 196, res 1, start (16 87 0), end (17 88 0), attack (0 0 0), fow 
OI 42, mp 0, res 1, start (17 88 0), end (17 89 0), attack (0 0 0), fow 
OI 0, mp 1819, res 1, start (90 30 0), end (89 31 0), attack (0 0 0), fow 
OI 0, mp 1678, res 1, start (89 31 0), end (88 32 0), attack (0 0 0), fow 
OI 0, mp 1578, res 3, start (88 32 0), end (88 33 0), attack (0 0 0), fow 
OI 0, mp 1819, res 1, start (90 30 0), end (89 31 0), attack (0 0 0), fow 
OI 0, mp 1819, res 1, start (90 30 0), end (89 31 0), attack (0 0 0), fow 
OI 0, mp 1678, res 1, start (89 31 0), end (88 32 0), attack (0 0 0), fow 
OI 0, mp 1678, res 1, start (89 31 0), end (88 32 0), attack (0 0 0), fow 
OI 0, mp 1578, res 3, start (88 32 0), end (88 33 0), attack (0 0 0), fow 
OI 0, mp 1578, res 3, start (88 32 0), end (88 33 0), attack (0 0 0), fow 
OI 18, mp 1705, res 1, start (72 102 0), end (71 102 0), attack (0 0 0), fow 
OI 18, mp 1529, res 1, start (71 102 0), end (70 101 0), attack (0 0 0), fow 
OI 18, mp 1404, res 1, start (70 101 0), end (70 100 0), attack (0 0 0), fow 
OI 18, mp 1228, res 1, start (70 100 0), end (69 99 0), attack (0 0 0), fow 
OI 0, mp 1437, res 1, start (88 32 0), end (87 31 0), attack (0 0 0), fow 
OI 0, mp 1296, res 1, start (87 31 0), end (86 30 0), attack (0 0 0), fow 
OI 0, mp 1196, res 1, start (86 30 0), end (85 30 0), attack (0 0 0), fow 
OI 0, mp 1055, res 1, start (85 30 0), end (84 29 0), attack (0 0 0), fow 
OI 0, mp 955, res 3, start (84 29 0), end (83 29 0), attack (0 0 0), fow 
OI 18, mp 1052, res 1, start (69 99 0), end (68 98 0), attack (0 0 0), fow 
OI 0, mp 1437, res 1, start (88 32 0), end (87 31 0), attack (0 0 0), fow 
OI 0, mp 1437, res 1, start (88 32 0), end (87 31 0), attack (0 0 0), fow 
OI 18, mp 876, res 1, start (68 98 0), end (69 97 0), attack (0 0 0), fow 
OI 0, mp 1296, res 1, start (87 31 0), end (86 30 0), attack (0 0 0), fow 
OI 0, mp 1296, res 1, start (87 31 0), end (86 30 0), attack (0 0 0), fow 
OI 0, mp 1196, res 1, start (86 30 0), end (85 30 0), attack (0 0 0), fow 
OI 0, mp 1196, res 1, start (86 30 0), end (85 30 0), attack (0 0 0), fow 
OI 18, mp 876, res 2, start (69 97 0), end (65 47 0), attack (0 0 0), fow (62 42 0), (63 42 0), (64 42 0), (65 42 0), (66 42 0), (61 43 0), (62 43 0), (63 43 0), (64 43 0), (65 43 0), (66 43 0), (67 43 0), (60 44 0), (61 44 0), (62 44 0), (63 44 0), (64 44 0), (65 44 0), (66 44 0), (67 44 0), (68 44 0), (59 45 0), (60 45 0), (61 45 0), (62 45 0), (63 45 0), (64 45 0), (65 45 0), (66 45 0), (67 45 0), (68 45 0), (69 45 0), (59 46 0), (60 46 0), (61 46 0), (62 46 0), (63 46 0), (64 46 0), (65 46 0), (66 46 0), (67 46 0), (68 46 0), (69 46 0), (59 47 0), (60 47 0), (61 47 0), (62 47 0), (63 47 0), (64 47 0), (65 47 0), (66 47 0), (67 47 0), (68 47 0), (69 47 0), (59 48 0), (60 48 0), (61 48 0), (62 48 0), (63 48 0), (64 48 0), (65 48 0), (66 48 0), (67 48 0), (68 48 0), (69 48 0), (59 49 0), (60 49 0), (61 49 0), (62 49 0), (63 49 0), (64 49 0), (65 49 0), (66 49 0), (67 49 0), (68 49 0), (69 49 0), (60 50 0), (61 50 0), (62 50 0), (63 50 0), (64 50 0), (65 50 0), (66 50 0), (67 50 0), (68 50 0), (61 51 0), (62 51 0), (63 51 0), (64 51 0), (65 51 0), (66 51 0), (67 51 0), (62 52 0), (63 52 0), (64 52 0), (65 52 0), (66 52 0), 
OI 0, mp 1055, res 1, start (85 30 0), end (84 29 0), attack (0 0 0), fow 
OI 0, mp 1055, res 1, start (85 30 0), end (84 29 0), attack (0 0 0), fow 
OI 0, mp 955, res 3, start (84 29 0), end (83 29 0), attack (0 0 0), fow 
OI 0, mp 955, res 3, start (84 29 0), end (83 29 0), attack (0 0 0), fow 
OI 0, mp 855, res 1, start (84 29 0), end (83 29 0), attack (0 0 0), fow 
OI 0, mp 714, res 1, start (83 29 0), end (82 30 0), attack (0 0 0), fow 
OI 0, mp 614, res 1, start (82 30 0), end (81 30 0), attack (0 0 0), fow 
OI 0, mp 473, res 1, start (81 30 0), end (80 29 0), attack (78 28 0), fow (74 27 0), 
OI 0, mp 855, res 1, start (84 29 0), end (83 29 0), attack (0 0 0), fow 
OI 0, mp 855, res 1, start (84 29 0), end (83 29 0), attack (0 0 0), fow 
OI 0, mp 714, res 1, start (83 29 0), end (82 30 0), attack (0 0 0), fow 
OI 0, mp 714, res 1, start (83 29 0), end (82 30 0), attack (0 0 0), fow 
OI 0, mp 614, res 1, start (82 30 0), end (81 30 0), attack (0 0 0), fow 
OI 0, mp 614, res 1, start (82 30 0), end (81 30 0), attack (0 0 0), fow 
OI 0, mp 473, res 1, start (81 30 0), end (80 29 0), attack (78 28 0), fow (74 27 0), 
OI 0, mp 473, res 1, start (81 30 0), end (80 29 0), attack (78 28 0), fow (74 27 0), 
OI 18, mp 776, res 1, start (65 47 0), end (65 48 0), attack (0 0 0), fow (59 50 0), (69 50 0), (60 51 0), (68 51 0), (61 52 0), (67 52 0), (62 53 0), (63 53 0), (64 53 0), (65 53 0), (66 53 0), 
OI 18, mp 676, res 1, start (65 48 0), end (65 49 0), attack (0 0 0), fow (59 51 0), (69 51 0), (60 52 0), (68 52 0), (61 53 0), (67 53 0), (62 54 0), (63 54 0), (64 54 0), (65 54 0), (66 54 0), 
OI 18, mp 576, res 1, start (65 49 0), end (65 50 0), attack (0 0 0), fow (59 52 0), (69 52 0), (60 53 0), (68 53 0), (61 54 0), (67 54 0), (62 55 0), (63 55 0), (64 55 0), (65 55 0), (66 55 0), 
OI 18, mp 435, res 1, start (65 50 0), end (66 51 0), attack (0 0 0), fow (70 49 0), (70 50 0), (70 51 0), (70 52 0), (69 53 0), (70 53 0), (68 54 0), (69 54 0), (67 55 0), (68 55 0), (63 56 0), (64 56 0), (65 56 0), (66 56 0), (67 56 0), 
OI 18, mp 294, res 1, start (66 51 0), end (67 52 0), attack (0 0 0), fow (71 50 0), (71 51 0), (71 52 0), (71 53 0), (70 54 0), (71 54 0), (69 55 0), (70 55 0), (68 56 0), (69 56 0), (64 57 0), (65 57 0), (66 57 0), (67 57 0), (68 57 0), 
OI 18, mp 194, res 1, start (67 52 0), end (68 52 0), attack (0 0 0), fow (70 48 0), (71 49 0), (72 50 0), (72 51 0), (72 52 0), (72 53 0), (72 54 0), (71 55 0), (70 56 0), (69 57 0), 
OI 18, mp 0, res 1, start (68 52 0), end (69 53 0), attack (0 0 0), fow (73 51 0), (73 52 0), (73 53 0), (73 54 0), (72 55 0), (73 55 0), (71 56 0), (72 56 0), (70 57 0), (71 57 0), (66 58 0), (67 58 0), (68 58 0), (69 58 0), (70 58 0), 
OI 20, mp 1485, res 1, start (91 97 0), end (92 97 0), attack (0 0 0), fow 
OI 20, mp 1410, res 1, start (92 97 0), end (93 97 0), attack (0 0 0), fow 
OI 20, mp 1304, res 1, start (93 97 0), end (94 96 0), attack (0 0 0), fow 
OI 20, mp 1229, res 1, start (94 96 0), end (95 96 0), attack (0 0 0), fow 
OI 20, mp 1129, res 1, start (95 96 0), end (96 96 0), attack (0 0 0), fow 
OI 20, mp 1029, res 1, start (96 96 0), end (97 96 0), attack (0 0 0), fow 
We received InfoWindow for not our player...
OI 20, mp 929, res 1, start (97 96 0), end (96 96 0), attack (0 0 0), fow 
OI 20, mp 829, res 1, start (96 96 0), end (96 95 0), attack (0 0 0), fow 
OI 20, mp 754, res 1, start (96 95 0), end (96 94 0), attack (0 0 0), fow 
OI 20, mp 679, res 1, start (96 94 0), end (96 93 0), attack (95 92 0), fow 
We received YesNoDialog for not our player...
OI 20, mp 604, res 1, start (96 93 0), end (96 92 0), attack (0 0 0), fow 
OI 20, mp 529, res 1, start (96 92 0), end (96 91 0), attack (0 0 0), fow 
We received InfoWindow for not our player...
OI 20, mp 388, res 1, start (96 91 0), end (97 92 0), attack (0 0 0), fow 
OI 20, mp 288, res 1, start (97 92 0), end (98 92 0), attack (0 0 0), fow 
OI 20, mp 188, res 1, start (98 92 0), end (99 92 0), attack (0 0 0), fow 
OI 20, mp 0, res 1, start (99 92 0), end (100 92 0), attack (0 0 0), fow 
OI 0, mp 332, res 1, start (80 29 0), end (79 28 0), attack (0 0 0), fow (75 24 0), (74 25 0), (73 26 0), (74 26 0), (73 27 0), (73 28 0), (73 29 0), (73 30 0), 
OI 0, mp 232, res 1, start (79 28 0), end (79 27 0), attack (0 0 0), fow (76 22 0), (75 23 0), (74 24 0), (73 25 0), 
OI 0, mp 332, res 1, start (80 29 0), end (79 28 0), attack (0 0 0), fow (75 24 0), (74 25 0), (73 26 0), (74 26 0), (73 27 0), (73 28 0), (73 29 0), (73 30 0), 
OI 0, mp 332, res 1, start (80 29 0), end (79 28 0), attack (0 0 0), fow (75 24 0), (74 25 0), (73 26 0), (74 26 0), (73 27 0), (73 28 0), (73 29 0), (73 30 0), 
OI 0, mp 232, res 1, start (79 28 0), end (79 27 0), attack (0 0 0), fow (76 22 0), (75 23 0), (74 24 0), (73 25 0), 
OI 0, mp 232, res 1, start (79 28 0), end (79 27 0), attack (0 0 0), fow (76 22 0), (75 23 0), (74 24 0), (73 25 0), 
OI 0, mp 132, res 1, start (79 27 0), end (79 28 0), attack (0 0 0), fow 
OI 0, mp 0, res 1, start (79 28 0), end (80 29 0), attack (0 0 0), fow 
OI 0, mp 132, res 1, start (79 27 0), end (79 28 0), attack (0 0 0), fow 
OI 0, mp 132, res 1, start (79 27 0), end (79 28 0), attack (0 0 0), fow 
OI 0, mp 0, res 1, start (79 28 0), end (80 29 0), attack (0 0 0), fow 
OI 0, mp 0, res 1, start (79 28 0), end (80 29 0), attack (0 0 0), fow 
OI 23, mp 1460, res 1, start (50 15 0), end (50 16 0), attack (0 0 0), fow 
OI 23, mp 1319, res 1, start (50 16 0), end (49 17 0), attack (0 0 0), fow 
OI 23, mp 1178, res 1, start (49 17 0), end (50 18 0), attack (0 0 0), fow 
OI 23, mp 1078, res 1, start (50 18 0), end (51 18 0), attack (0 0 0), fow 
OI 23, mp 937, res 1, start (51 18 0), end (52 19 0), attack (0 0 0), fow 
OI 23, mp 796, res 1, start (52 19 0), end (53 20 0), attack (0 0 0), fow 
OI 23, mp 696, res 1, start (53 20 0), end (54 20 0), attack (0 0 0), fow 
OI 23, mp 555, res 1, start (54 20 0), end (55 21 0), attack (0 0 0), fow 
OI 23, mp 455, res 1, start (55 21 0), end (56 21 0), attack (0 0 0), fow 
OI 23, mp 314, res 1, start (56 21 0), end (57 22 0), attack (0 0 0), fow 
OI 23, mp 173, res 1, start (57 22 0), end (58 23 0), attack (0 0 0), fow 
OI 23, mp 0, res 1, start (58 23 0), end (59 24 0), attack (0 0 0), fow 
OI 28, mp 1689, res 1, start (29 24 0), end (30 25 0), attack (0 0 0), fow 
OI 28, mp 1589, res 1, start (30 25 0), end (30 26 0), attack (0 0 0), fow 
OI 28, mp 1489, res 1, start (30 26 0), end (29 26 0), attack (0 0 0), fow 
We received InfoWindow for not our player...
OI 15, mp 1359, res 1, start (6 17 0), end (5 16 0), attack (0 0 0), fow 
OI 15, mp 1218, res 1, start (5 16 0), end (4 15 0), attack (0 0 0), fow 
OI 15, mp 1118, res 1, start (4 15 0), end (4 14 0), attack (0 0 0), fow 
We received YesNoDialog for not our player...
OI 99, mp 1400, res 1, start (23 26 0), end (24 26 0), attack (0 0 0), fow 
OI 99, mp 1300, res 1, start (24 26 0), end (25 26 0), attack (0 0 0), fow 
OI 99, mp 1159, res 1, start (25 26 0), end (26 27 0), attack (0 0 0), fow 
OI 99, mp 1018, res 1, start (26 27 0), end (27 28 0), attack (0 0 0), fow 
OI 99, mp 877, res 1, start (27 28 0), end (28 29 0), attack (0 0 0), fow 
OI 99, mp 777, res 1, start (28 29 0), end (28 30 0), attack (0 0 0), fow 
OI 99, mp 677, res 1, start (28 30 0), end (28 31 0), attack (0 0 0), fow 
OI 99, mp 536, res 1, start (28 31 0), end (29 32 0), attack (0 0 0), fow 
OI 99, mp 436, res 1, start (29 32 0), end (30 32 0), attack (0 0 0), fow 
OI 99, mp 295, res 1, start (30 32 0), end (31 31 0), attack (0 0 0), fow 
We received InfoWindow for not our player...
OI 28, mp 1389, res 1, start (29 26 0), end (30 26 0), attack (0 0 0), fow 
OI 28, mp 1289, res 1, start (30 26 0), end (30 25 0), attack (0 0 0), fow 
OI 28, mp 1148, res 1, start (30 25 0), end (31 24 0), attack (0 0 0), fow 
OI 28, mp 1048, res 1, start (31 24 0), end (32 24 0), attack (0 0 0), fow 
OI 28, mp 948, res 1, start (32 24 0), end (33 24 0), attack (0 0 0), fow 
OI 28, mp 807, res 1, start (33 24 0), end (34 23 0), attack (0 0 0), fow 
OI 28, mp 707, res 1, start (34 23 0), end (34 22 0), attack (0 0 0), fow 
OI 28, mp 607, res 1, start (34 22 0), end (34 21 0), attack (0 0 0), fow 
OI 28, mp 466, res 1, start (34 21 0), end (35 20 0), attack (0 0 0), fow 
We received YesNoDialog for not our player...
OI 99, mp 154, res 1, start (31 31 0), end (32 32 0), attack (0 0 0), fow 
OI 99, mp 0, res 1, start (32 32 0), end (33 31 0), attack (0 0 0), fow 
OI 15, mp 1018, res 1, start (4 14 0), end (4 15 0), attack (0 0 0), fow 
OI 15, mp 877, res 1, start (4 15 0), end (5 16 0), attack (0 0 0), fow 
OI 15, mp 777, res 1, start (5 16 0), end (6 16 0), attack (0 0 0), fow 
OI 15, mp 677, res 1, start (6 16 0), end (7 16 0), attack (0 0 0), fow 
OI 15, mp 536, res 1, start (7 16 0), end (8 15 0), attack (0 0 0), fow 
OI 15, mp 436, res 1, start (8 15 0), end (9 15 0), attack (0 0 0), fow 
OI 15, mp 295, res 1, start (9 15 0), end (10 14 0), attack (0 0 0), fow 
OI 15, mp 154, res 1, start (10 14 0), end (11 13 0), attack (0 0 0), fow 
OI 15, mp 0, res 1, start (11 13 0), end (12 12 0), attack (0 0 0), fow 
OI 28, mp 325, res 1, start (35 20 0), end (36 21 0), attack (0 0 0), fow 
OI 28, mp 184, res 1, start (36 21 0), end (37 20 0), attack (0 0 0), fow 
OI 28, mp 0, res 1, start (37 20 0), end (38 19 0), attack (0 0 0), fow 
OI 41, mp 1400, res 1, start (73 56 0), end (73 57 0), attack (0 0 0), fow 
OI 41, mp 1259, res 1, start (73 57 0), end (72 58 0), attack (0 0 0), fow 
OI 41, mp 1118, res 1, start (72 58 0), end (71 57 0), attack (0 0 0), fow 
OI 41, mp 977, res 1, start (71 57 0), end (70 56 0), attack (0 0 0), fow 
OI 41, mp 877, res 1, start (70 56 0), end (70 55 0), attack (0 0 0), fow 
OI 41, mp 777, res 1, start (70 55 0), end (70 54 0), attack (0 0 0), fow 
OI 41, mp 636, res 3, start (70 54 0), end (69 53 0), attack (0 0 0), fow 
OI 6, mp 1460, res 1, start (25 88 0), end (24 88 0), attack (0 0 0), fow 
OI 6, mp 1360, res 1, start (24 88 0), end (23 88 0), attack (0 0 0), fow 
OI 6, mp 1260, res 1, start (23 88 0), end (22 88 0), attack (0 0 0), fow 
OI 6, mp 1119, res 3, start (22 88 0), end (21 89 0), attack (0 0 0), fow 
OI 4, mp 1460, res 1, start (19 89 0), end (18 89 0), attack (0 0 0), fow 
OI 4, mp 1360, res 3, start (18 89 0), end (17 89 0), attack (0 0 0), fow 
OI 45, mp 1660, res 1, start (15 92 0), end (15 91 0), attack (0 0 0), fow 
OI 45, mp 1519, res 1, start (15 91 0), end (16 90 0), attack (0 0 0), fow 
OI 45, mp 1378, res 3, start (16 90 0), end (17 89 0), attack (0 0 0), fow 
OI 6, mp 1019, res 1, start (22 88 0), end (22 89 0), attack (0 0 0), fow 
OI 6, mp 878, res 1, start (22 89 0), end (21 90 0), attack (0 0 0), fow 
OI 6, mp 778, res 1, start (21 90 0), end (20 90 0), attack (0 0 0), fow 
OI 6, mp 637, res 1, start (20 90 0), end (19 89 0), attack (0 0 0), fow 
OI 6, mp 496, res 1, start (19 89 0), end (18 88 0), attack (0 0 0), fow 
OI 6, mp 396, res 1, start (18 88 0), end (17 88 0), attack (0 0 0), fow 
OI 6, mp 255, res 1, start (17 88 0), end (16 87 0), attack (0 0 0), fow 
OI 6, mp 114, res 1, start (16 87 0), end (15 86 0), attack (0 0 0), fow 
We received InfoWindow for not our player...
OI 41, mp 536, res 1, start (70 54 0), end (70 55 0), attack (0 0 0), fow 
OI 41, mp 436, res 1, start (70 55 0), end (70 56 0), attack (0 0 0), fow 
OI 41, mp 336, res 1, start (70 56 0), end (70 57 0), attack (0 0 0), fow 
OI 41, mp 236, res 1, start (70 57 0), end (70 58 0), attack (0 0 0), fow (64 60 0), (65 61 0), (66 62 0), (67 63 0), 
OI 41, mp 0, res 1, start (70 58 0), end (71 59 0), attack (0 0 0), fow (68 64 0), (69 64 0), (70 64 0), (71 64 0), (72 64 0), 
OI 119, mp 1600, res 1, start (21 89 0), end (22 89 0), attack (0 0 0), fow 
OI 119, mp 1459, res 1, start (22 89 0), end (23 88 0), attack (0 0 0), fow 
OI 119, mp 1359, res 1, start (23 88 0), end (24 88 0), attack (0 0 0), fow 
OI 119, mp 1259, res 1, start (24 88 0), end (25 88 0), attack (0 0 0), fow 
OI 119, mp 1118, res 1, start (25 88 0), end (26 87 0), attack (0 0 0), fow 
OI 119, mp 977, res 1, start (26 87 0), end (27 86 0), attack (0 0 0), fow 
OI 119, mp 836, res 1, start (27 86 0), end (28 85 0), attack (0 0 0), fow 
OI 119, mp 695, res 1, start (28 85 0), end (29 84 0), attack (0 0 0), fow 
OI 119, mp 554, res 1, start (29 84 0), end (30 83 0), attack (0 0 0), fow (29 78 0), (30 78 0), (31 78 0), 
We received InfoWindow for not our player...
OI 42, mp 1660, res 1, start (17 89 0), end (17 88 0), attack (0 0 0), fow 
OI 42, mp 1560, res 1, start (17 88 0), end (17 87 0), attack (0 0 0), fow 
OI 42, mp 1460, res 1, start (17 87 0), end (17 86 0), attack (0 0 0), fow 
OI 42, mp 1319, res 1, start (17 86 0), end (16 85 0), attack (0 0 0), fow 
OI 42, mp 1219, res 1, start (16 85 0), end (16 84 0), attack (0 0 0), fow 
OI 42, mp 1119, res 1, start (16 84 0), end (16 83 0), attack (0 0 0), fow 
OI 42, mp 1019, res 1, start (16 83 0), end (16 82 0), attack (0 0 0), fow 
OI 42, mp 878, res 1, start (16 82 0), end (15 81 0), attack (0 0 0), fow 
OI 42, mp 778, res 1, start (15 81 0), end (15 80 0), attack (0 0 0), fow 
OI 42, mp 637, res 1, start (15 80 0), end (14 79 0), attack (0 0 0), fow 
OI 42, mp 537, res 1, start (14 79 0), end (13 79 0), attack (0 0 0), fow 
OI 42, mp 437, res 1, start (13 79 0), end (12 79 0), attack (0 0 0), fow 
We received InfoWindow for not our player...
OI 42, mp 337, res 1, start (12 79 0), end (13 79 0), attack (0 0 0), fow 
OI 42, mp 237, res 1, start (13 79 0), end (14 79 0), attack (0 0 0), fow 
OI 42, mp 0, res 1, start (14 79 0), end (15 80 0), attack (0 0 0), fow 
OI 119, mp 413, res 1, start (30 83 0), end (29 84 0), attack (0 0 0), fow 
OI 119, mp 272, res 1, start (29 84 0), end (28 85 0), attack (0 0 0), fow 
OI 119, mp 131, res 1, start (28 85 0), end (27 86 0), attack (0 0 0), fow 
OI 119, mp 0, res 1, start (27 86 0), end (26 87 0), attack (0 0 0), fow 
OI 6, mp 0, res 1, start (15 86 0), end (16 87 0), attack (0 0 0), fow 
OI 45, mp 1237, res 1, start (16 90 0), end (17 89 0), attack (0 0 0), fow 
OI 45, mp 1137, res 1, start (17 89 0), end (17 88 0), attack (0 0 0), fow 
OI 45, mp 1037, res 1, start (17 88 0), end (17 87 0), attack (0 0 0), fow 
OI 45, mp 896, res 1, start (17 87 0), end (16 86 0), attack (0 0 0), fow 
OI 45, mp 796, res 1, start (16 86 0), end (15 86 0), attack (0 0 0), fow 
We received InfoWindow for not our player...
OI 4, mp 1219, res 1, start (18 89 0), end (17 90 0), attack (0 0 0), fow 
OI 4, mp 1078, res 1, start (17 90 0), end (16 91 0), attack (0 0 0), fow 
OI 4, mp 937, res 1, start (16 91 0), end (15 92 0), attack (0 0 0), fow 
OI 4, mp 837, res 1, start (15 92 0), end (15 93 0), attack (0 0 0), fow 
OI 4, mp 737, res 1, start (15 93 0), end (15 94 0), attack (0 0 0), fow 
OI 4, mp 596, res 1, start (15 94 0), end (16 95 0), attack (0 0 0), fow 
OI 4, mp 496, res 1, start (16 95 0), end (16 96 0), attack (0 0 0), fow 
OI 4, mp 355, res 1, start (16 96 0), end (15 97 0), attack (0 0 0), fow 
OI 4, mp 280, res 1, start (15 97 0), end (14 97 0), attack (0 0 0), fow 
OI 4, mp 205, res 1, start (14 97 0), end (13 97 0), attack (0 0 0), fow 
OI 4, mp 130, res 1, start (13 97 0), end (12 97 0), attack (0 0 0), fow 
OI 4, mp 0, res 1, start (12 97 0), end (11 97 0), attack (0 0 0), fow 
OI 45, mp 696, res 1, start (15 86 0), end (16 86 0), attack (0 0 0), fow 
OI 45, mp 555, res 1, start (16 86 0), end (17 87 0), attack (0 0 0), fow 
OI 45, mp 455, res 1, start (17 87 0), end (17 88 0), attack (0 0 0), fow 
OI 45, mp 355, res 1, start (17 88 0), end (17 89 0), attack (0 0 0), fow 
OI 45, mp 255, res 1, start (17 89 0), end (17 90 0), attack (0 0 0), fow 
OI 45, mp 114, res 1, start (17 90 0), end (16 91 0), attack (0 0 0), fow 
OI 45, mp 0, res 1, start (16 91 0), end (15 92 0), attack (0 0 0), fow 
OI 0, mp 1860, res 1, start (80 29 0), end (80 30 0), attack (0 0 0), fow 
OI 0, mp 1719, res 1, start (80 30 0), end (81 31 0), attack (0 0 0), fow 
OI 0, mp 1619, res 1, start (81 31 0), end (81 32 0), attack (0 0 0), fow 
OI 0, mp 1519, res 1, start (81 32 0), end (81 33 0), attack (0 0 0), fow 
OI 0, mp 1419, res 1, start (81 33 0), end (80 33 0), attack (0 0 0), fow 
OI 0, mp 1860, res 1, start (80 29 0), end (80 30 0), attack (0 0 0), fow 
OI 0, mp 1860, res 1, start (80 29 0), end (80 30 0), attack (0 0 0), fow 
OI 0, mp 1719, res 1, start (80 30 0), end (81 31 0), attack (0 0 0), fow 
OI 0, mp 1719, res 1, start (80 30 0), end (81 31 0), attack (0 0 0), fow 
OI 0, mp 1619, res 1, start (81 31 0), end (81 32 0), attack (0 0 0), fow 
OI 0, mp 1619, res 1, start (81 31 0), end (81 32 0), attack (0 0 0), fow 
OI 0, mp 1519, res 1, start (81 32 0), end (81 33 0), attack (0 0 0), fow 
OI 0, mp 1519, res 1, start (81 32 0), end (81 33 0), attack (0 0 0), fow 
OI 0, mp 1419, res 1, start (81 33 0), end (80 33 0), attack (0 0 0), fow 
OI 0, mp 1419, res 1, start (81 33 0), end (80 33 0), attack (0 0 0), fow 
OI 20, mp 1460, res 1, start (100 92 0), end (101 92 0), attack (0 0 0), fow 
OI 20, mp 1319, res 1, start (101 92 0), end (102 93 0), attack (0 0 0), fow 
OI 20, mp 1219, res 1, start (102 93 0), end (102 94 0), attack (101 95 0), fow 
We received YesNoDialog for not our player...
OI 0, mp 1319, res 1, start (80 33 0), end (79 33 0), attack (0 0 0), fow (73 31 0), (73 32 0), (73 33 0), (73 34 0), (73 35 0), 
OI 0, mp 1178, res 3, start (79 33 0), end (78 32 0), attack (0 0 0), fow 
OI 0, mp 1319, res 1, start (80 33 0), end (79 33 0), attack (0 0 0), fow (73 31 0), (73 32 0), (73 33 0), (73 34 0), (73 35 0), 
OI 0, mp 1319, res 1, start (80 33 0), end (79 33 0), attack (0 0 0), fow (73 31 0), (73 32 0), (73 33 0), (73 34 0), (73 35 0), 
OI 0, mp 1178, res 3, start (79 33 0), end (78 32 0), attack (0 0 0), fow 
OI 0, mp 1178, res 3, start (79 33 0), end (78 32 0), attack (0 0 0), fow 
OI 20, mp 1078, res 3, start (102 94 0), end (101 95 0), attack (0 0 0), fow 
We received InfoWindow for not our player...
OI 0, mp 1037, res 1, start (79 33 0), end (78 34 0), attack (76 35 0), fow (72 32 0), (72 33 0), (72 34 0), (72 35 0), (72 36 0), (73 36 0), (73 37 0), (74 37 0), (74 38 0), 
OI 0, mp 1037, res 1, start (79 33 0), end (78 34 0), attack (76 35 0), fow (72 32 0), (72 33 0), (72 34 0), (72 35 0), (72 36 0), (73 36 0), (73 37 0), (74 37 0), (74 38 0), 
OI 0, mp 1037, res 1, start (79 33 0), end (78 34 0), attack (76 35 0), fow (72 32 0), (72 33 0), (72 34 0), (72 35 0), (72 36 0), (73 36 0), (73 37 0), (74 37 0), (74 38 0), 
OI 20, mp 937, res 1, start (102 94 0), end (103 93 0), attack (0 0 0), fow 
OI 20, mp 796, res 1, start (103 93 0), end (104 92 0), attack (0 0 0), fow 
We received InfoWindow for not our player...
OI 20, mp 696, res 1, start (104 92 0), end (105 92 0), attack (0 0 0), fow 
OI 20, mp 596, res 1, start (105 92 0), end (106 92 0), attack (0 0 0), fow 
OI 20, mp 455, res 1, start (106 92 0), end (107 93 0), attack (0 0 0), fow 
OI 20, mp 355, res 1, start (107 93 0), end (107 94 0), attack (0 0 0), fow 
OI 20, mp 255, res 1, start (107 94 0), end (107 95 0), attack (0 0 0), fow 
OI 20, mp 155, res 1, start (107 95 0), end (107 96 0), attack (0 0 0), fow 
OI 20, mp 0, res 1, start (107 96 0), end (106 96 0), attack (0 0 0), fow 
We received InfoWindow for not our player...
OI 20, mp 300, res 1, start (106 96 0), end (107 96 0), attack (0 0 0), fow 
OI 20, mp 200, res 1, start (107 96 0), end (107 95 0), attack (0 0 0), fow 
OI 20, mp 0, res 1, start (107 95 0), end (106 94 0), attack (0 0 0), fow 
OI 0, mp 937, res 1, start (78 34 0), end (78 35 0), attack (0 0 0), fow (72 37 0), (73 38 0), (74 39 0), (75 40 0), 
OI 0, mp 796, res 3, start (78 35 0), end (77 36 0), attack (0 0 0), fow 
OI 0, mp 937, res 1, start (78 34 0), end (78 35 0), attack (0 0 0), fow (72 37 0), (73 38 0), (74 39 0), (75 40 0), 
OI 0, mp 937, res 1, start (78 34 0), end (78 35 0), attack (0 0 0), fow (72 37 0), (73 38 0), (74 39 0), (75 40 0), 
OI 0, mp 796, res 3, start (78 35 0), end (77 36 0), attack (0 0 0), fow 
OI 0, mp 796, res 3, start (78 35 0), end (77 36 0), attack (0 0 0), fow 
OI 0, mp 696, res 1, start (78 35 0), end (78 34 0), attack (0 0 0), fow 
OI 0, mp 596, res 1, start (78 34 0), end (78 33 0), attack (0 0 0), fow (72 31 0), 
OI 0, mp 455, res 1, start (78 33 0), end (77 32 0), attack (0 0 0), fow (72 29 0), (71 30 0), (72 30 0), (71 31 0), (71 32 0), (71 33 0), (71 34 0), 
OI 0, mp 355, res 1, start (77 32 0), end (76 32 0), attack (0 0 0), fow (72 28 0), (71 29 0), (70 30 0), (70 31 0), (70 32 0), (70 33 0), (70 34 0), (71 35 0), 
OI 0, mp 214, res 1, start (76 32 0), end (75 31 0), attack (0 0 0), fow (72 26 0), (71 27 0), (72 27 0), (70 28 0), (71 28 0), (69 29 0), (70 29 0), (69 30 0), (69 31 0), (69 32 0), (69 33 0), 
OI 0, mp 0, res 1, start (75 31 0), end (74 30 0), attack (0 0 0), fow (71 25 0), (72 25 0), (70 26 0), (71 26 0), (69 27 0), (70 27 0), (68 28 0), (69 28 0), (68 29 0), (68 30 0), (68 31 0), (68 32 0), 
OI 0, mp 696, res 1, start (78 35 0), end (78 34 0), attack (0 0 0), fow 
OI 0, mp 696, res 1, start (78 35 0), end (78 34 0), attack (0 0 0), fow 
OI 0, mp 596, res 1, start (78 34 0), end (78 33 0), attack (0 0 0), fow (72 31 0), 
OI 0, mp 596, res 1, start (78 34 0), end (78 33 0), attack (0 0 0), fow (72 31 0), 
OI 0, mp 455, res 1, start (78 33 0), end (77 32 0), attack (0 0 0), fow (72 29 0), (71 30 0), (72 30 0), (71 31 0), (71 32 0), (71 33 0), (71 34 0), 
OI 0, mp 455, res 1, start (78 33 0), end (77 32 0), attack (0 0 0), fow (72 29 0), (71 30 0), (72 30 0), (71 31 0), (71 32 0), (71 33 0), (71 34 0), 
OI 0, mp 355, res 1, start (77 32 0), end (76 32 0), attack (0 0 0), fow (72 28 0), (71 29 0), (70 30 0), (70 31 0), (70 32 0), (70 33 0), (70 34 0), (71 35 0), 
OI 0, mp 355, res 1, start (77 32 0), end (76 32 0), attack (0 0 0), fow (72 28 0), (71 29 0), (70 30 0), (70 31 0), (70 32 0), (70 33 0), (70 34 0), (71 35 0), 
OI 0, mp 214, res 1, start (76 32 0), end (75 31 0), attack (0 0 0), fow (72 26 0), (71 27 0), (72 27 0), (70 28 0), (71 28 0), (69 29 0), (70 29 0), (69 30 0), (69 31 0), (69 32 0), (69 33 0), 
OI 0, mp 214, res 1, start (76 32 0), end (75 31 0), attack (0 0 0), fow (72 26 0), (71 27 0), (72 27 0), (70 28 0), (71 28 0), (69 29 0), (70 29 0), (69 30 0), (69 31 0), (69 32 0), (69 33 0), 
OI 0, mp 0, res 1, start (75 31 0), end (74 30 0), attack (0 0 0), fow (71 25 0), (72 25 0), (70 26 0), (71 26 0), (69 27 0), (70 27 0), (68 28 0), (69 28 0), (68 29 0), (68 30 0), (68 31 0), (68 32 0), 
OI 0, mp 0, res 1, start (75 31 0), end (74 30 0), attack (0 0 0), fow (71 25 0), (72 25 0), (70 26 0), (71 26 0), (69 27 0), (70 27 0), (68 28 0), (69 28 0), (68 29 0), (68 30 0), (68 31 0), (68 32 0), 
OI 99, mp 1359, res 1, start (33 31 0), end (32 30 0), attack (0 0 0), fow 
OI 99, mp 1218, res 1, start (32 30 0), end (31 29 0), attack (0 0 0), fow 
OI 99, mp 1118, res 1, start (31 29 0), end (30 29 0), attack (0 0 0), fow 
OI 99, mp 1018, res 1, start (30 29 0), end (29 29 0), attack (0 0 0), fow 
OI 99, mp 918, res 1, start (29 29 0), end (28 29 0), attack (0 0 0), fow 
OI 99, mp 777, res 1, start (28 29 0), end (27 28 0), attack (0 0 0), fow 
OI 99, mp 636, res 1, start (27 28 0), end (26 27 0), attack (0 0 0), fow 
OI 99, mp 495, res 1, start (26 27 0), end (25 26 0), attack (0 0 0), fow 
OI 99, mp 395, res 1, start (25 26 0), end (24 26 0), attack (0 0 0), fow 
OI 99, mp 295, res 1, start (24 26 0), end (23 26 0), attack (0 0 0), fow 
OI 99, mp 195, res 1, start (23 26 0), end (22 26 0), attack (0 0 0), fow 
OI 99, mp 0, res 1, start (22 26 0), end (21 26 0), attack (0 0 0), fow 
OI 28, mp 1359, res 1, start (38 19 0), end (37 20 0), attack (0 0 0), fow 
OI 28, mp 1218, res 1, start (37 20 0), end (36 21 0), attack (0 0 0), fow 
OI 28, mp 1077, res 1, start (36 21 0), end (35 22 0), attack (0 0 0), fow 
OI 28, mp 936, res 1, start (35 22 0), end (34 23 0), attack (0 0 0), fow 
OI 28, mp 795, res 1, start (34 23 0), end (33 24 0), attack (0 0 0), fow 
OI 28, mp 695, res 1, start (33 24 0), end (32 24 0), attack (0 0 0), fow 
OI 28, mp 595, res 1, start (32 24 0), end (31 24 0), attack (0 0 0), fow 
OI 28, mp 454, res 1, start (31 24 0), end (30 23 0), attack (0 0 0), fow 
OI 28, mp 379, res 1, start (30 23 0), end (29 23 0), attack (0 0 0), fow 
OI 28, mp 304, res 1, start (29 23 0), end (28 23 0), attack (0 0 0), fow 
OI 28, mp 229, res 1, start (28 23 0), end (27 23 0), attack (0 0 0), fow 
OI 28, mp 154, res 1, start (27 23 0), end (26 23 0), attack (0 0 0), fow 
OI 28, mp 0, res 1, start (26 23 0), end (25 22 0), attack (0 0 0), fow 
OI 15, mp 1359, res 1, start (12 12 0), end (11 13 0), attack (0 0 0), fow 
OI 15, mp 1218, res 1, start (11 13 0), end (10 14 0), attack (0 0 0), fow 
OI 15, mp 1118, res 1, start (10 14 0), end (9 14 0), attack (0 0 0), fow 
OI 15, mp 977, res 1, start (9 14 0), end (8 15 0), attack (0 0 0), fow 
OI 15, mp 836, res 1, start (8 15 0), end (7 16 0), attack (0 0 0), fow 
OI 15, mp 695, res 1, start (7 16 0), end (6 17 0), attack (0 0 0), fow 
OI 15, mp 595, res 1, start (6 17 0), end (6 18 0), attack (0 0 0), fow 
OI 15, mp 454, res 1, start (6 18 0), end (5 19 0), attack (0 0 0), fow 
OI 15, mp 304, res 1, start (5 19 0), end (5 20 0), attack (0 0 0), fow 
OI 15, mp 154, res 1, start (5 20 0), end (5 21 0), attack (0 0 0), fow 
OI 15, mp 0, res 1, start (5 21 0), end (5 22 0), attack (0 0 0), fow 
OI 23, mp 1419, res 1, start (59 24 0), end (58 23 0), attack (0 0 0), fow 
OI 23, mp 1278, res 1, start (58 23 0), end (57 22 0), attack (0 0 0), fow 
OI 23, mp 1178, res 1, start (57 22 0), end (57 21 0), attack (0 0 0), fow 
OI 23, mp 1037, res 1, start (57 21 0), end (56 20 0), attack (0 0 0), fow 
We received YesNoDialog for not our player...
OI 23, mp 896, res 1, start (56 20 0), end (57 21 0), attack (0 0 0), fow 
OI 23, mp 755, res 1, start (57 21 0), end (58 22 0), attack (0 0 0), fow 
OI 23, mp 614, res 1, start (58 22 0), end (59 23 0), attack (0 0 0), fow 
OI 23, mp 473, res 1, start (59 23 0), end (60 24 0), attack (0 0 0), fow 
OI 23, mp 332, res 1, start (60 24 0), end (61 25 0), attack (0 0 0), fow 
OI 23, mp 191, res 1, start (61 25 0), end (62 26 0), attack (0 0 0), fow 
OI 23, mp 0, res 1, start (62 26 0), end (62 27 0), attack (0 0 0), fow 
OI 42, mp 1460, res 1, start (15 80 0), end (15 81 0), attack (0 0 0), fow 
OI 42, mp 1360, res 1, start (15 81 0), end (15 82 0), attack (0 0 0), fow 
OI 42, mp 1260, res 1, start (15 82 0), end (15 83 0), attack (0 0 0), fow 
OI 42, mp 1119, res 1, start (15 83 0), end (16 84 0), attack (0 0 0), fow 
OI 42, mp 1019, res 1, start (16 84 0), end (16 85 0), attack (0 0 0), fow 
OI 42, mp 919, res 1, start (16 85 0), end (16 86 0), attack (0 0 0), fow 
OI 42, mp 778, res 1, start (16 86 0), end (17 87 0), attack (0 0 0), fow 
OI 42, mp 678, res 1, start (17 87 0), end (17 88 0), attack (0 0 0), fow 
OI 42, mp 578, res 1, start (17 88 0), end (17 89 0), attack (0 0 0), fow 
OI 42, mp 437, res 1, start (17 89 0), end (16 90 0), attack (0 0 0), fow 
OI 42, mp 296, res 1, start (16 90 0), end (15 91 0), attack (0 0 0), fow 
OI 42, mp 155, res 1, start (15 91 0), end (14 92 0), attack (0 0 0), fow 
OI 42, mp 0, res 1, start (14 92 0), end (15 93 0), attack (0 0 0), fow 
OI 119, mp 1460, res 1, start (26 87 0), end (25 87 0), attack (0 0 0), fow 
OI 119, mp 1360, res 1, start (25 87 0), end (24 87 0), attack (0 0 0), fow 
OI 119, mp 1219, res 1, start (24 87 0), end (23 88 0), attack (0 0 0), fow 
OI 119, mp 1078, res 1, start (23 88 0), end (22 89 0), attack (0 0 0), fow 
OI 119, mp 937, res 1, start (22 89 0), end (21 90 0), attack (0 0 0), fow 
OI 119, mp 796, res 1, start (21 90 0), end (22 91 0), attack (0 0 0), fow 
OI 119, mp 696, res 1, start (22 91 0), end (23 91 0), attack (0 0 0), fow 
OI 119, mp 596, res 1, start (23 91 0), end (24 91 0), attack (0 0 0), fow 
OI 119, mp 455, res 1, start (24 91 0), end (25 92 0), attack (0 0 0), fow 
OI 119, mp 355, res 1, start (25 92 0), end (26 92 0), attack (0 0 0), fow 
OI 119, mp 255, res 1, start (26 92 0), end (27 92 0), attack (0 0 0), fow 
OI 119, mp 155, res 1, start (27 92 0), end (28 92 0), attack (0 0 0), fow 
OI 119, mp 0, res 1, start (28 92 0), end (29 91 0), attack (0 0 0), fow 
OI 41, mp 1400, res 1, start (71 59 0), end (71 60 0), attack (0 0 0), fow (65 62 0), (75 62 0), (66 63 0), (74 63 0), (67 64 0), (73 64 0), (68 65 0), (69 65 0), (70 65 0), (71 65 0), (72 65 0), 
OI 41, mp 1300, res 1, start (71 60 0), end (71 61 0), attack (0 0 0), fow (65 63 0), (75 63 0), (66 64 0), (74 64 0), (67 65 0), (73 65 0), (68 66 0), (69 66 0), (70 66 0), (71 66 0), (72 66 0), 
OI 41, mp 1200, res 3, start (71 61 0), end (71 62 0), attack (0 0 0), fow 
We received InfoWindow for not our player...
OI 4, mp 1660, res 1, start (11 97 0), end (12 97 0), attack (0 0 0), fow 
OI 4, mp 1585, res 1, start (12 97 0), end (13 97 0), attack (0 0 0), fow 
OI 4, mp 1510, res 1, start (13 97 0), end (14 97 0), attack (0 0 0), fow 
OI 4, mp 1435, res 1, start (14 97 0), end (15 97 0), attack (0 0 0), fow 
OI 4, mp 1360, res 1, start (15 97 0), end (16 97 0), attack (0 0 0), fow 
OI 4, mp 1285, res 1, start (16 97 0), end (17 97 0), attack (0 0 0), fow 
OI 4, mp 1210, res 1, start (17 97 0), end (18 97 0), attack (0 0 0), fow 
OI 4, mp 1135, res 1, start (18 97 0), end (19 97 0), attack (0 0 0), fow 
OI 4, mp 1029, res 1, start (19 97 0), end (20 96 0), attack (0 0 0), fow 
OI 6, mp 1600, res 1, start (16 87 0), end (17 87 0), attack (0 0 0), fow 
OI 6, mp 1459, res 1, start (17 87 0), end (18 88 0), attack (0 0 0), fow 
OI 6, mp 1359, res 1, start (18 88 0), end (19 88 0), attack (0 0 0), fow 
OI 6, mp 1218, res 1, start (19 88 0), end (20 89 0), attack (0 0 0), fow 
OI 6, mp 1077, res 1, start (20 89 0), end (21 90 0), attack (0 0 0), fow 
OI 6, mp 936, res 1, start (21 90 0), end (22 91 0), attack (0 0 0), fow 
OI 6, mp 836, res 1, start (22 91 0), end (23 91 0), attack (0 0 0), fow 
OI 6, mp 736, res 1, start (23 91 0), end (24 91 0), attack (0 0 0), fow 
OI 6, mp 595, res 1, start (24 91 0), end (25 92 0), attack (0 0 0), fow 
OI 6, mp 495, res 1, start (25 92 0), end (26 92 0), attack (0 0 0), fow 
OI 6, mp 395, res 1, start (26 92 0), end (27 92 0), attack (0 0 0), fow 
OI 6, mp 254, res 1, start (27 92 0), end (28 91 0), attack (0 0 0), fow 
OI 6, mp 113, res 1, start (28 91 0), end (29 90 0), attack (0 0 0), fow 
We received YesNoDialog for not our player...
We received InfoWindow for not our player...
OI 6, mp 0, res 1, start (29 90 0), end (30 91 0), attack (0 0 0), fow 
OI 4, mp 923, res 1, start (20 96 0), end (19 97 0), attack (0 0 0), fow 
OI 4, mp 848, res 1, start (19 97 0), end (18 97 0), attack (0 0 0), fow 
OI 4, mp 773, res 1, start (18 97 0), end (17 97 0), attack (0 0 0), fow 
OI 4, mp 632, res 1, start (17 97 0), end (16 96 0), attack (0 0 0), fow 
OI 4, mp 532, res 1, start (16 96 0), end (16 95 0), attack (0 0 0), fow 
OI 4, mp 432, res 1, start (16 95 0), end (16 94 0), attack (0 0 0), fow 
OI 4, mp 291, res 3, start (16 94 0), end (15 93 0), attack (0 0 0), fow 
OI 41, mp 1100, res 1, start (71 61 0), end (70 61 0), attack (0 0 0), fow (64 61 0), (64 62 0), (64 63 0), (65 64 0), (66 65 0), (67 66 0), 
OI 41, mp 1000, res 1, start (70 61 0), end (69 61 0), attack (0 0 0), fow (63 59 0), (63 60 0), (63 61 0), (63 62 0), (63 63 0), (64 64 0), (65 65 0), (66 66 0), 
OI 41, mp 900, res 1, start (69 61 0), end (68 61 0), attack (0 0 0), fow (63 58 0), (62 59 0), (62 60 0), (62 61 0), (62 62 0), (62 63 0), (63 64 0), (64 65 0), (65 66 0), 
OI 41, mp 800, res 1, start (68 61 0), end (67 61 0), attack (0 0 0), fow (63 57 0), (62 58 0), (61 59 0), (61 60 0), (61 61 0), (61 62 0), (61 63 0), (62 64 0), (63 65 0), (64 66 0), 
OI 41, mp 700, res 1, start (67 61 0), end (66 61 0), attack (0 0 0), fow (62 57 0), (61 58 0), (60 63 0), (61 64 0), (62 65 0), (63 66 0), 
We received InfoWindow for not our player...
OI 41, mp 600, res 1, start (66 61 0), end (66 62 0), attack (0 0 0), fow (60 64 0), (61 65 0), (62 66 0), (63 67 0), (64 67 0), (65 67 0), (66 67 0), (67 67 0), 
OI 41, mp 500, res 1, start (66 62 0), end (66 63 0), attack (0 0 0), fow (60 65 0), (61 66 0), (62 67 0), (68 67 0), (63 68 0), (64 68 0), (65 68 0), (66 68 0), (67 68 0), 
OI 41, mp 359, res 1, start (66 63 0), end (65 64 0), attack (0 0 0), fow (59 64 0), (59 65 0), (59 66 0), (60 66 0), (60 67 0), (61 67 0), (61 68 0), (62 68 0), (62 69 0), (63 69 0), (64 69 0), (65 69 0), (66 69 0), 
OI 41, mp 259, res 1, start (65 64 0), end (65 65 0), attack (0 0 0), fow (59 67 0), (69 67 0), (60 68 0), (68 68 0), (61 69 0), (67 69 0), (62 70 0), (63 70 0), (64 70 0), (65 70 0), (66 70 0), 
OI 41, mp 118, res 1, start (65 65 0), end (66 66 0), attack (0 0 0), fow (70 67 0), (69 68 0), (70 68 0), (68 69 0), (69 69 0), (67 70 0), (68 70 0), (63 71 0), (64 71 0), (65 71 0), (66 71 0), (67 71 0), 
OI 41, mp 0, res 1, start (66 66 0), end (67 66 0), attack (0 0 0), fow (71 67 0), (71 68 0), (70 69 0), (69 70 0), (68 71 0), 
OI 4, mp 191, res 1, start (16 94 0), end (16 95 0), attack (0 0 0), fow 
OI 4, mp 0, res 1, start (16 95 0), end (16 96 0), attack (0 0 0), fow 
OI 45, mp 1619, res 1, start (15 92 0), end (16 91 0), attack (0 0 0), fow 
OI 45, mp 1478, res 1, start (16 91 0), end (17 90 0), attack (0 0 0), fow 
OI 45, mp 1337, res 1, start (17 90 0), end (18 89 0), attack (0 0 0), fow 
OI 45, mp 1237, res 1, start (18 89 0), end (19 89 0), attack (0 0 0), fow 
OI 45, mp 1137, res 1, start (19 89 0), end (20 89 0), attack (0 0 0), fow 
OI 45, mp 996, res 1, start (20 89 0), end (21 90 0), attack (0 0 0), fow 
OI 45, mp 855, res 1, start (21 90 0), end (22 91 0), attack (0 0 0), fow 
OI 45, mp 714, res 1, start (22 91 0), end (23 92 0), attack (0 0 0), fow 
OI 45, mp 573, res 1, start (23 92 0), end (24 93 0), attack (0 0 0), fow 
OI 45, mp 432, res 1, start (24 93 0), end (25 94 0), attack (0 0 0), fow 
OI 45, mp 332, res 1, start (25 94 0), end (25 95 0), attack (0 0 0), fow 
OI 45, mp 191, res 1, start (25 95 0), end (24 96 0), attack (0 0 0), fow 
OI 45, mp 0, res 1, start (24 96 0), end (23 97 0), attack (0 0 0), fow 
OI 0, mp 1860, res 1, start (74 30 0), end (73 30 0), attack (0 0 0), fow (70 25 0), (69 26 0), (68 27 0), (67 28 0), (67 29 0), (67 30 0), (67 31 0), (67 32 0), (68 33 0), (69 34 0), (70 35 0), 
OI 0, mp 1760, res 1, start (73 30 0), end (72 30 0), attack (0 0 0), fow (69 25 0), (68 26 0), (67 27 0), (66 28 0), (66 29 0), (66 30 0), (66 31 0), (66 32 0), (67 33 0), (68 34 0), (69 35 0), 
OI 0, mp 1619, res 3, start (72 30 0), end (71 29 0), attack (0 0 0), fow 
OI 0, mp 1860, res 1, start (74 30 0), end (73 30 0), attack (0 0 0), fow (70 25 0), (69 26 0), (68 27 0), (67 28 0), (67 29 0), (67 30 0), (67 31 0), (67 32 0), (68 33 0), (69 34 0), (70 35 0), 
OI 0, mp 1860, res 1, start (74 30 0), end (73 30 0), attack (0 0 0), fow (70 25 0), (69 26 0), (68 27 0), (67 28 0), (67 29 0), (67 30 0), (67 31 0), (67 32 0), (68 33 0), (69 34 0), (70 35 0), 
OI 0, mp 1760, res 1, start (73 30 0), end (72 30 0), attack (0 0 0), fow (69 25 0), (68 26 0), (67 27 0), (66 28 0), (66 29 0), (66 30 0), (66 31 0), (66 32 0), (67 33 0), (68 34 0), (69 35 0), 
OI 0, mp 1760, res 1, start (73 30 0), end (72 30 0), attack (0 0 0), fow (69 25 0), (68 26 0), (67 27 0), (66 28 0), (66 29 0), (66 30 0), (66 31 0), (66 32 0), (67 33 0), (68 34 0), (69 35 0), 
OI 0, mp 1619, res 3, start (72 30 0), end (71 29 0), attack (0 0 0), fow 
OI 0, mp 1619, res 3, start (72 30 0), end (71 29 0), attack (0 0 0), fow 
OI 0, mp 1478, res 1, start (72 30 0), end (73 31 0), attack (0 0 0), fow (70 36 0), (71 36 0), 
OI 0, mp 1337, res 1, start (73 31 0), end (74 32 0), attack (0 0 0), fow (71 37 0), 
OI 0, mp 1196, res 3, start (74 32 0), end (73 33 0), attack (0 0 0), fow 
OI 0, mp 1478, res 1, start (72 30 0), end (73 31 0), attack (0 0 0), fow (70 36 0), (71 36 0), 
OI 0, mp 1478, res 1, start (72 30 0), end (73 31 0), attack (0 0 0), fow (70 36 0), (71 36 0), 
OI 0, mp 1337, res 1, start (73 31 0), end (74 32 0), attack (0 0 0), fow (71 37 0), 
OI 0, mp 1337, res 1, start (73 31 0), end (74 32 0), attack (0 0 0), fow (71 37 0), 
OI 0, mp 1196, res 3, start (74 32 0), end (73 33 0), attack (0 0 0), fow 
OI 0, mp 1196, res 3, start (74 32 0), end (73 33 0), attack (0 0 0), fow 
OI 20, mp 1460, res 1, start (106 94 0), end (105 94 0), attack (0 0 0), fow 
OI 20, mp 1319, res 1, start (105 94 0), end (104 95 0), attack (0 0 0), fow 
OI 20, mp 1178, res 1, start (104 95 0), end (103 96 0), attack (0 0 0), fow 
OI 20, mp 1037, res 1, start (103 96 0), end (102 97 0), attack (0 0 0), fow 
OI 20, mp 937, res 1, start (102 97 0), end (102 98 0), attack (0 0 0), fow 
OI 20, mp 796, res 1, start (102 98 0), end (101 99 0), attack (0 0 0), fow 
OI 20, mp 655, res 1, start (101 99 0), end (100 100 0), attack (0 0 0), fow 
OI 20, mp 555, res 1, start (100 100 0), end (100 101 0), attack (0 0 0), fow 
OI 20, mp 455, res 1, start (100 101 0), end (100 102 0), attack (0 0 0), fow 
OI 20, mp 314, res 1, start (100 102 0), end (99 103 0), attack (0 0 0), fow 
OI 20, mp 214, res 1, start (99 103 0), end (99 104 0), attack (0 0 0), fow 
OI 20, mp 114, res 1, start (99 104 0), end (99 105 0), attack (0 0 0), fow 
OI 20, mp 0, res 1, start (99 105 0), end (99 106 0), attack (0 0 0), fow 
OI 0, mp 1096, res 1, start (74 32 0), end (75 32 0), attack (0 0 0), fow 
OI 0, mp 996, res 1, start (75 32 0), end (76 32 0), attack (0 0 0), fow 
OI 0, mp 896, res 1, start (76 32 0), end (77 32 0), attack (0 0 0), fow 
OI 0, mp 796, res 1, start (77 32 0), end (78 32 0), attack (0 0 0), fow 
OI 0, mp 655, res 1, start (78 32 0), end (79 33 0), attack (0 0 0), fow 
OI 0, mp 514, res 1, start (79 33 0), end (80 34 0), attack (0 0 0), fow 
OI 0, mp 414, res 1, start (80 34 0), end (81 34 0), attack (0 0 0), fow 
OI 0, mp 1096, res 1, start (74 32 0), end (75 32 0), attack (0 0 0), fow 
OI 0, mp 1096, res 1, start (74 32 0), end (75 32 0), attack (0 0 0), fow 
OI 0, mp 273, res 1, start (81 34 0), end (82 35 0), attack (0 0 0), fow 
OI 0, mp 132, res 1, start (82 35 0), end (83 36 0), attack (0 0 0), fow 
OI 0, mp 0, res 1, start (83 36 0), end (84 37 0), attack (82 38 0), fow 
OI 0, mp 996, res 1, start (75 32 0), end (76 32 0), attack (0 0 0), fow 
OI 0, mp 996, res 1, start (75 32 0), end (76 32 0), attack (0 0 0), fow 
OI 0, mp 896, res 1, start (76 32 0), end (77 32 0), attack (0 0 0), fow 
OI 0, mp 896, res 1, start (76 32 0), end (77 32 0), attack (0 0 0), fow 
OI 0, mp 796, res 1, start (77 32 0), end (78 32 0), attack (0 0 0), fow 
OI 0, mp 796, res 1, start (77 32 0), end (78 32 0), attack (0 0 0), fow 
OI 0, mp 655, res 1, start (78 32 0), end (79 33 0), attack (0 0 0), fow 
OI 0, mp 655, res 1, start (78 32 0), end (79 33 0), attack (0 0 0), fow 
OI 0, mp 514, res 1, start (79 33 0), end (80 34 0), attack (0 0 0), fow 
OI 0, mp 514, res 1, start (79 33 0), end (80 34 0), attack (0 0 0), fow 
OI 0, mp 414, res 1, start (80 34 0), end (81 34 0), attack (0 0 0), fow 
OI 0, mp 414, res 1, start (80 34 0), end (81 34 0), attack (0 0 0), fow 
OI 0, mp 273, res 1, start (81 34 0), end (82 35 0), attack (0 0 0), fow 
OI 0, mp 273, res 1, start (81 34 0), end (82 35 0), attack (0 0 0), fow 
OI 0, mp 132, res 1, start (82 35 0), end (83 36 0), attack (0 0 0), fow 
OI 0, mp 132, res 1, start (82 35 0), end (83 36 0), attack (0 0 0), fow 
OI 0, mp 0, res 1, start (83 36 0), end (84 37 0), attack (82 38 0), fow 
OI 0, mp 0, res 1, start (83 36 0), end (84 37 0), attack (82 38 0), fow 
Error: cannot find a hex to attack hex 1 from!
vcmiclient: /var/tmp/portage/games-strategy/vcmi-9999/work/vcmi-9999/client/battle/BattleFieldController.cpp:754: BattleHex BattleFieldController::fromWhichHexAttack(const BattleHex&): Assertion `direction != BattleHex::NONE' failed.
Aborted
```

Video https://rumble.com/v714kce-vcmi-3-battle-of-the-sexes-ai.html

[VCMI_Client_log.txt](https://github.com/user-attachments/files/23291501/VCMI_Client_log.txt)

### PR DESCRIPTION
**Pull request by mrhaandi**
Fixes #6282 (the other issue mentioned there is already fixed).

Also this fixes the situation in which a healing tent considers attacking itself, which crashes for the same reason.
In general, only units with `isMeleeAttacker() == true` consider attacking in melee. This should be faster and more stable.

What happens: 
if the active unit X is surrounded (by fried or foe) and you hover over X, then deciding if `PossiblePlayerBattleAction::ATTACK` sees that X can reach itself and decides that it is attackable.
However, `owner.fieldController->fromWhichHexAttack(targetHex)` cannot determine from which direction X is supposed to attack itself and the `assert(direction != BattleHex::NONE)` is violated.

### CODE REVIEW

**Comment by IvanSavenko** [comment]
But why `isTileAttackable` returns true for unit position? In h3 unit can't attack own position. Perhaps correct fix is to adjust `isTileAttackable` to return false in such cases?

**Comment by mrhaandi** [comment]
The `isTileAttackable` contains `elem == number`, this is true exactly on targeting itself (and thus it returns true).
An alternative fix would be to remove `elem == number`. However, I do not have the insight to know what this change would induce since this function is also used e.g. in `BattleHexArray BattleFieldController::getHighlightedHexesForMovementTarget()`.

Proposing the fix to the particular crash I went for the least intrusive option.

**Comment by IvanSavenko** [comment]
From what I see, `getHighlightedHexesForMovementTarget` also expects hovered hex to be different - since it immediately calls the very same `fromWhichHexAttack`. So changing `isTileAttackable` seems more correct & safe change

**Comment by mrhaandi** [comment]
I tested removing the condition and there is more to the bug itself. The proposed fix unfortunately doesn't cover all cases.
In particular, if a using is two hexes wide, then `elem == number` is is only half true.

**Comment by MichalZr6** [comment]
I might have touched that issue already. Please take a look on:
- #6262

**Comment by mrhaandi** [comment]
> I might have touched that issue already. Please take a look on:
> 
> * [Battle fixes: Sacrifice targeting, First Aid Tent possible actions. GUI: cursor init stall fix #6262](https://github.com/vcmi/vcmi/pull/6262)

I see no mechanics which interact with creature (worst case double wide) attack targeting itself.

**Comment by mrhaandi** [comment]
When I start adding more logic to `BattleFieldController::isTileAttackable` (especially for double wide), I'm basically recreating `BattleFieldController::selectAttackDirection`. A quick fix would be to refactor the availability logic from this method as a check.

**Comment by MichalZr6** [comment]
Targeting tent (when hero had expert first aid) on the tent's turn had too many `PossiblePlayerBattleAction` and attack was picked as it was first in the container. Then `assert(direction != BattleHex::NONE)` triggered. Just saying this for it might give any hint for the fix you are working on. This PR may even bring the fix to the issue I had with tent-case.

**Comment by mrhaandi** [comment]
> Targeting tent (when hero had expert first aid) on the tent's turn had too many `PossiblePlayerBattleAction` and attack was picked as it was first in the container. Then `assert(direction != BattleHex::NONE)` triggered. Just saying this for it might give any hint for the fix you are working on or even bring the fix to the issue I had with tent-case.

Ah, yes logically the issues are related. However, I'm not sure whether I agree with your solution. ATTACK can be considered as `PossiblePlayerBattleAction` (also for the tent) but then discarded with proper checks (as I'm trying with this PR).

I currently believe that for the problem at hand one can split `BattleFieldController::selectAttackDirection` into two functions.
One which proves suggested attack directions (this would subsume `isTileAttackable`) and one which decides the actual direction.

**Comment by MichalZr6** [comment]
I phrased myself badly. Sorry. I edited my previous comment to show what I really meant.

**Comment by mrhaandi** [comment]
To include wide units and the tent, now I simply check `targetStack != activeStack`.
This fixes the original issue (also for wide units) and there is no crash on tent thinking about attacking itself.
While this is good enough to fix issues in practice, `isTileAttackable` is definitely not sound (it is ok, as it is used for early abort only). I would like to consider the underlying logic in a future PR (not this one), so any regression after these fixes is visible.

**Comment by mrhaandi** [comment]
@MichalZr6 in case I missed something, could you check whether the proposed PR fixes the tent issues? I verified that on hovering over the tent with expert first aid no crash happens (as in current `develop`). In such a case `targetStack == activeStack` and `BattleActionsController::actionIsLegal` return `false` for attack.

**Comment by mrhaandi** [comment]
I added `isMeleeAttacker()` to units, which is `false` for
```
		CreatureID::FIRST_AID_TENT,
		CreatureID::CATAPULT,
		CreatureID::BALLISTA,
		CreatureID::AMMO_CART,
		CreatureID::ARROW_TOWERS
```
This way, for these units the possibility is not even considered and some code can be cleaned up.
I do consider the current PR as done.
I will think (in a different PR) about a more robust attack logic in general.

File: lib/battle/Unit.cpp [hunk 1]
```diff
@@ -38,6 +38,22 @@ bool Unit::isTurret() const
...
+	//exclude non melee attackers
+	static const std::set<CreatureID> nonMeleeAttackers{
+		CreatureID::FIRST_AID_TENT,
+		CreatureID::CATAPULT,
+		CreatureID::BALLISTA,
+		CreatureID::AMMO_CART,
+		CreatureID::ARROW_TOWERS
+	};
+	if (vstd::contains(nonMeleeAttackers, creatureId()))
+		return false;
```
Comment (IvanSavenko) [inline lib/battle/Unit.cpp]: "If is war machine or arrow tower"?

Your check does not covers new war machines from mods, like cannon from hota

Comment (mrhaandi) [reply lib/battle/Unit.cpp]: I agree. Do you think a creature bonus `NO_MELEE_ATTACK` should be added for safe extensibility? I looked through the bonuses but besides `SIEGE_WEAPON` (which I don't think is fitting here) there is nothing which can be used here.

Comment (IvanSavenko) [reply lib/battle/Unit.cpp]: Check for siege weapon bonus. Name is not exactly correct, and is used for all war machines, not just for siege-related (catapult). 

Feel free to add ilcheck for it as separate method to unit, we have a lot of checks for war machines, all check for that bonus.

Additional no melee attack bonus - might be an interesting addition for modders to play with, but shouldn't replace siege machine bonus

Comment (mrhaandi) [reply lib/battle/Unit.cpp]: OK, I changed the code to check for `hasBonusOfType(BonusType::SIEGE_WEAPON)`.
I added a comment that mods could require further refinement (e.g. melee war machine, or an effect which prevents melee attacks).
