### PR TITLE
fix high scores screen

### LINKED ISSUE #3111: Crash on high scores screen
**Describe the bug**
Adding more high scores with same player name leads to crash.

**Game logs**

Call stack:
```
 	KernelBase.dll!00007fff5d664ffc()	No info
 	vcruntime140.dll!00007fff2c5d6720()	No info
>	VCMI_lib.dll!std::_Throw_bad_variant_access() Line 418	C++
 	VCMI_lib.dll!std::get(const std::variant<std::monostate,bool,double,std::string,std::vector<JsonNode,std::allocator<JsonNode>>,std::map<std::string,JsonNode,std::less<std::string>,std::allocator<std::pair<std::string const ,JsonNode>>>,__int64> &) Line 1225	C++
 	VCMI_lib.dll!std::get(const std::variant<std::monostate,bool,double,std::string,std::vector<JsonNode,std::allocator<JsonNode>>,std::map<std::string,JsonNode,std::less<std::string>,std::allocator<std::pair<std::string const ,JsonNode>>>,__int64> &) Line 1260	C++
 	VCMI_lib.dll!JsonNode::Integer() Line 342	C++
 	VCMI_client.exe!CHighScoreInputScreen::addEntry::__l2::<lambda>(const JsonNode & left, const JsonNode & right) Line 256	C++
 	VCMI_client.exe!std::sort(const std::_Vector_iterator<std::_Vector_val<std::_Simple_types<JsonNode>>>) Line 8067	C++
 	VCMI_client.exe!boost::range::sort(std::vector<JsonNode,std::allocator<JsonNode>> &) Line 51	C++
 	VCMI_client.exe!CHighScoreInputScreen::addEntry(std::string text) Line 274	C++
 	[Ramka wbudowana] VCMI_client.exe!std::_Func_class<void,std::string>::operator()(std::string) Line 883	C++
 	VCMI_client.exe!CHighScoreInput::okay() Line 383	C++
```

**To Reproduce**
1. Win a game
2. Put your name in the high scores
3. Win another game
4. Put same name in high scores

**Expected behavior**
No crash

**Actual behavior**
`JsonNode::Intege`r throws `bad_variant_access`.

**Did it work earlier?**
 Nope, it's a new feature.

**Screenshots**
Crash occurs before high scores are displayed.

**Version**
1.4.0

### PR DESCRIPTION
**Pull request by Laserlicht**
fixes #3111

@DjWarmonger Can you confirm?

### CODE REVIEW

**Comment by boctavian96** [comment]
Hello @Laserlicht! I've tried this PR and on Mac the behaviour is the same unfortunately. :(

**Comment by Nordsoft91** [comment]
I cannot reproduce on PR build

**Comment by Laserlicht** [comment]
> Hello @Laserlicht! I've tried this PR and on Mac the behaviour is the same unfortunately. :(

Hi @boctavian96

you tried the artifacts? Or did you build it yourself?

**Comment by boctavian96** [comment]
> > Hello @Laserlicht! I've tried this PR and on Mac the behaviour is the same unfortunately. :(
> 
> Hi @boctavian96
> 
> you tried the artifacts? Or did you build it yourself?

Hi! Sorry for the late response. I've build it myself from your PR branch, and I've tested it using the 'vcmiwin' command. 
Let me know if I can help with something :)

**Comment by boctavian96** [comment]
@Laserlicht, I've also attached the stack trace.



> MainGUI (1) Queue : com.apple.main-thread (serial)
#0	0x000000018dea8764 in __pthread_kill ()
#1	0x0000000104d06b84 in pthread_kill ()
#2	0x000000018ddedae8 in abort ()
#3	0x000000018ddece44 in __assert_rtn ()
#4	0x0000000100a5c5c4 in CWindowObject::CWindowObject(int, ResourcePathTempl<(EResType)8> const&) at /Users/octavian/Git/vcmi/client/windows/CWindowObject.cpp:63
#5	0x00000001006d481c in CHighScoreInput::CHighScoreInput(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)>) at /Users/octavian/Git/vcmi/client/mainmenu/CHighScoreScreen.cpp:364
#6	0x00000001006d51e0 in CHighScoreInput::CHighScoreInput(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::function<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)>) at /Users/octavian/Git/vcmi/client/mainmenu/CHighScoreScreen.cpp:365
#7	0x00000001006e4c3c in std::__1::__shared_ptr_emplace<CHighScoreInput, std::__1::allocator<CHighScoreInput> >::__shared_ptr_emplace[abi:v15006]<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, CHighScoreInputScreen::clickPressed(Point const&)::$_7>(std::__1::allocator<CHighScoreInput>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, CHighScoreInputScreen::clickPressed(Point const&)::$_7&&) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__memory/shared_ptr.h:294
#8	0x00000001006e48cc in std::__1::__shared_ptr_emplace<CHighScoreInput, std::__1::allocator<CHighScoreInput> >::__shared_ptr_emplace[abi:v15006]<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, CHighScoreInputScreen::clickPressed(Point const&)::$_7>(std::__1::allocator<CHighScoreInput>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, CHighScoreInputScreen::clickPressed(Point const&)::$_7&&) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__memory/shared_ptr.h:288
#9	0x00000001006e47cc in std::__1::shared_ptr<CHighScoreInput> std::__1::allocate_shared[abi:v15006]<CHighScoreInput, std::__1::allocator<CHighScoreInput>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, CHighScoreInputScreen::clickPressed(Point const&)::$_7, void>(std::__1::allocator<CHighScoreInput> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, CHighScoreInputScreen::clickPressed(Point const&)::$_7&&) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__memory/shared_ptr.h:953
#10	0x00000001006d46a4 in std::__1::shared_ptr<CHighScoreInput> std::__1::make_shared[abi:v15006]<CHighScoreInput, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, CHighScoreInputScreen::clickPressed(Point const&)::$_7, void>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, CHighScoreInputScreen::clickPressed(Point const&)::$_7&&) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__memory/shared_ptr.h:962
#11	0x00000001006d45dc in CHighScoreInputScreen::clickPressed(Point const&) at /Users/octavian/Git/vcmi/client/mainmenu/CHighScoreScreen.cpp:343
#12	0x00000001005963b4 in AEventsReceiver::clickPressed(Point const&, bool) at /Users/octavian/Git/vcmi/client/gui/EventsReceiver.cpp:74
#13	0x0000000100593d54 in EventDispatcher::handleLeftButtonClick(Point const&, int, bool) at /Users/octavian/Git/vcmi/client/gui/EventDispatcher.cpp:216
#14	0x0000000100593bdc in EventDispatcher::dispatchMouseLeftButtonPressed(Point const&, int) at /Users/octavian/Git/vcmi/client/gui/EventDispatcher.cpp:126
#15	0x0000000100583c5c in InputSourceMouse::handleEventMouseButtonDown(SDL_MouseButtonEvent const&) at /Users/octavian/Git/vcmi/client/eventsSDL/InputSourceMouse.cpp:53
#16	0x000000010057e420 in InputHandler::handleCurrentEvent(SDL_Event const&) at /Users/octavian/Git/vcmi/client/eventsSDL/InputHandler.cpp:56
#17	0x000000010057e6b0 in InputHandler::processEvents() at /Users/octavian/Git/vcmi/client/eventsSDL/InputHandler.cpp:89
#18	0x0000000100586534 in CGuiHandler::handleEvents() at /Users/octavian/Git/vcmi/client/gui/CGuiHandler.cpp:92
#19	0x00000001006ed28c in CMainMenu::update() at /Users/octavian/Git/vcmi/client/mainmenu/CMainMenu.cpp:344
#20	0x00000001005867b4 in CGuiHandler::renderFrame() at /Users/octavian/Git/vcmi/client/gui/CGuiHandler.cpp:118
#21	0x0000000100037658 in mainLoop() at /Users/octavian/Git/vcmi/client/CMT.cpp:450
#22	0x0000000100035e3c in main at /Users/octavian/Git/vcmi/client/CMT.cpp:412
#23	0x000000018db87f28 in start ()

**Comment by Laserlicht** [comment]
Ah - I know the problem. It's a debug build, correct?

**Comment by boctavian96** [comment]
> Ah - I know the problem. It's a debug build, correct?

Yes, it's a debug build!

**Comment by Laserlicht** [comment]
Should be fixed and should also work in debug now.

I made the mistake to develop this without debug build. Because of this and I need a workaround for playing video in background some asserts was triggered.

File: client/windows/CWindowObject.cpp [hunk 1]
```diff
@@ -60,7 +61,8 @@ CWindowObject::CWindowObject(int options_, const ImagePath & imageName):
 	options(options_),
 	background(createBg(imageName, options_ & PLAYER_COLORED))
 {
-	assert(parent == nullptr); //Safe to remove, but windows should not have parent
+	if(!(options & NEEDS_ANIMATED_BACKGROUND)) //currently workaround for highscores (currently uses window as normal control, because otherwise videos are not played in background yet)
+		assert(parent == nullptr); //Safe to remove, but windows should not have parent
```
Comment (nullkiller) [inline client/windows/CWindowObject.cpp:65]: Are you sure that in all release configurations assert never evaluates to nothing causing next statement being under if instead? I am not good at at C++ so I assume that in some cases assert can be a macro.

Comment (IvanSavenko) [reply client/windows/CWindowObject.cpp:65]: Code is fine. It will evaluate to an empty expression, but this will not change code flow.

Technically in release build condition is redundant, so
`assert(parent == nullptr || (options & NEEDS_ANIMATED_BACKGROUND));`
might be a better option, but both versions will work as expected.
