### PR TITLE
Battle: Fixing bugs & Implementation of missing features

### LINKED ISSUE #789: animation of Scorpicore’s attack effect is missing
but the effect itself (creature can't move) works as well as proper sound is played

### LINKED ISSUE #1048: some animations play in parallel
examples:
- regen and bad morale
- if 2 or more creatures receive bad morale in a row (i.e. now it's turn of creature1, next is creature2 and both receive bad morale), all bad morale animations play in parallel

actually this can be viewed as "a feature, not a bug" as it speeds up battle a bit

### LINKED ISSUE #1219: Battle-related bugs & missing functionalities
This is full list of known issues related to battle functionality that do not have separate issue. 
For others, see [unresolved battle issues on github](https://github.com/vcmi/vcmi/issues?q=is%3Aopen+label%3Abattle+no%3Aassignee+-label%3Aenhancement+-label%3Astupidai)

**General issues:**
- [ ] some obstacles have incorrect rendering order. obstacles.json has "unknown" field which may have "render this obstacle in background" meaning
- [ ] stack amount boxes positions are not updated AFTER move but only at start of next move
- [ ] Hovering over hero should show hero cursor
- [ ] On hex overlapping with hero image interaction with hero should be prioritized
- [ ] Recheck timings of all battle animations
- [ ] Stack amount boxes flicker a bit between stack animations
- [ ] Stack amount boxes update count & spell effect color before actual hit
- [ ] Destination point of spell projectiles seems to be off (at least - ice bolt)
- [ ] Hero animation for obstacle-creating spells plays only after obstacles are placed

**Spell-specific issues:**
- [ ] "Clone": position of created clone is different from H3
- [ ] "Sacrifice": wrong visual effect on sacrificed creature
- [ ] "Sacrifice": animation on resurrected creature should play after effect on sacrificed
- [ ] "Chain lighting": effect should be chained for 2-5th stacks. Probably using same effect as Mage/Evil Eye rays
- [ ] "Remove obstacle": no fade-out effect for removed object
- [ ] "Demon summon": stack animation should be paused for the duration of fade-in animation
- [ ] "Landmine": Visual explosion of mines is missing

**Ability-specific issues:**
- [ ] Lich Death Cloud (and likely Magog Fireball): hit animation on creatures plays BEFORE cloud animation. 
- [ ] Spell resistance (dwarves): effect should only play on primary target. Secondary targets on successful resist take no damage, but play no animations at all - no hit animation, no resistance sound, no resistance visual effect (NOTE: perhaps this can be considered bug in H3? Having Dwarves miraculously survive unharmed after Armageddon looks weird)
- [ ] Spell resistance (dwarves): If primary target resisted the spell, then spell animations should be skipped completely - no sound, no projectile, no hit effects). Hero's casting animation still plays though.

**Potential enhancements**
- [ ] Add better hex highlighting - use custom images for movement path, enemy movement area, spell target area, creature movement destination.
- [ ] Highlight all targeted creatures during dragon breath/all-around attacks

**MANTIS: Missing functionality (UI)**
- [ ] 0002205: Creatures info can not be changed in battle options
- [ ] 0002205: auto-combat rules can not be changed in battle options
- [ ] 0001565: Autobattle should be cancelable by mouse click
- [ ] 0002869: There is no warning if surrendering hero will trigger scenario loss
- [ ] 0000697: Hero info mini-card should appear when hovering over hero
- [ ] 0001408: Missing hotkey: T should open creature window of a hoveres stack
- [ ] 0001408: Missing hotkey: F5 should toggle displayed info on creature card popup
- [ ] 0001408: Missing hotkey: F6: should toggle hex grid
- [ ] 0001408: Missing hotkey: F7: should toggle mouse shadow display
- [ ] 0001408: Missing hotkey: F8: should toggle movement shadow display
- [ ] 0001408: Missing hotkey: S: during tactics phase, should start combat
- [ ] 0001285: On starting combat, if hero has tactics there should be popup "hero with superior tactics may arrange his armies"
- [ ] 0001285: Right-clicking "Next creature" button should show "Phase wait" message
- [ ] 0001285: Right-clicking "Start Combat " button should show "End Tactics Phase" message

**MANTIS: Missing functionality (mechanics)**
- [ ] 0002572: War machines should affect surrender cost
- [ ] 0002676: Zombies should cast Disease after attack with 20% chance
- [ ] 0002676: Bone/Ghost Dragon should have ability "-1 to enemy morale"
- [ ] 0002786: Heroes fighting at the sea should fight on ship-to-ship battle with custom obstacles
- [ ] 0002848: Elementals don't deal 100% higher damage to the elementals of opposing element (i.e. Fire and Water).
- [ ] 0002916: Magic Elementals should only deal 50% damage to all units resistant to 5th level spells
- [ ] 0002915: Psychic Elementals should deal 50% damage to all units resistant to mind spells, including Undead and Non-living creatures (BUT NOT GARGOYLES!). 

**MANTIS: Known bugs (UI):**
- [ ] 0002322: CBattleInterface destructor should wait "activeStack" thread to finish. 
- [ ] 0002392: Starting combat while holding left mouse button may lead to automatic movement of a stack
- [ ] 0000651: When right-clicking a creature, mouse cursor should change to pointer
- [ ] 0000694: Hoverting over corner of spell book shows "Next Page" tooltip even on last page
- [ ] 0002162: Hotseat: popup message "Spell will affect no one" don't appear for 2nd player
- [ ] 0002290: Spells like Disguise / Visions affect color of stack amount boxes
- [ ] 0002240: Actual damage for ranged units is higher than upper damage limit in combat log hint.
- [ ] 0002744: Bloodlust doesn't update the Attack value of the affected creatures 

**MANTIS: Known bugs (mechanics):**
- [ ] 0002893: Elixir of Life should affect Pit Lord's Demon Summoning
- [ ] 0002894: Adela's Bless boosts only max damage, but should affect min damage as well
- [ ] 0002373: Troops lost by retreat & surrender should not be used for necromancy skill
- [ ] 0002770: Killing Dendroid Soldier should remove entangle from affected stacks
- [ ] 0002896: Heroes with specialties connected with stat-altering spells don't do anything.(SPECIAL_PECULIAR_ENCHANT)
- [ ] 0002947: Fights inside mines should always use obstacles from underground terrain
- [ ] 0002971: Current Health doesn't update with Maximum Health if it's lowered e.g. with Poison ability
- [ ] 0003199: Magic elemental should have immunity against Thunderbold (from Thunderbirds)
- [ ] 0001616: It is possible to receive morale after defeating last enemy stack
- [ ] 0002451: Drawbridge stucks in locked state after first creature passes through it during tactics phase
- [ ] 0003165: Creatures like Archangels can cast their spell on self when in auto-combat, which should be impossible
- [ ] 0002807: Pit lord's summoning demons ability should be blocked if 0 creatures can be raised
- [ ] 0003132: creatures affected by "paralyse" and "stoneGaze" spells, should retaliate upon being attacked.

**MANTIS: Unconfirmed bugs:**
- [ ] 0002787: Magic Resistance animation is missing
- [ ] 0002787: Magic Resistance works incorrectly with Chain Lighting
- [ ] 0002614: Ancient Behemoths under Bless spell deal different amount of damage in H3 & vcmi
- [ ] 0002733: Check targeting of area-of-effect spells of Faerie Dragons
- [ ] 0003106: The firewall should hit double-wide units only once when moving through it
- [ ] 0001791: Orb of vulnerability mechanics in vcmi is different from H3
- [ ] 0003052: Adventure map is not deactivated during battles initiated by AI
- [ ] 0000684: Curse spell decreases damage to 1
- [ ] 0001065: Catapult target selection areas are different from H3
- [ ] 0002925: Blind - unit receives turn, but can't do anything

**MANTIS: Enhancements:**
- [ ] 0000950: Allow shooters to move and attack enemy units in close combat 
- [ ] 0000949: Show expected damage, kills and potential counter-attack when mouse is over enemy unit stack
- [ ] 0002417: Add better formula for merging garrison & visitor armies during siege

### PR DESCRIPTION
**Pull request by IvanSavenko**
Attempt to fix remaining bugs & functionalities involving battles.

**Partially fixes #1219. More specifically:** 
- [x] spell animation should wait for hero spellcasting animation before playing
- [x] Earthquake spell should not select already destroyed sections
- [x] During enemy turn game should use "default" cursor
- [x] During enemy turn hex highlighting should be off
- [x] Phoenix "Rebirth" animation plays sound immediately on hit, long before visual effect
- [x] Master Genie spellcasting: sounds plays immediately, long before visual effect
- [x] Power Lich, Magogs: ranged attack plays attack effect (cloud) only after hit animation on target is over
- [x] Creatures with breath attacks, e.g. Dragons, should use different animation when attacking two units
- [x] All summoning spells have no fade-in effect for summoned creature
- [x] All damaging spells should have hit animation starting alongside with hit effect
- [x] All obstacle-creating spells: UI is not locked during landmines placement
- [x] All spell-created obstacles should have configurable appear sound
- [x] "Resurrection", "Raise Dead", "Sacrifice", "Rebirth": no reverse death animation when played on dead stack
- [x] "Resurrection", "Raise Dead", "Sacrifice", "Rebirth": reverse death animation should play at the same time as effect
- [x] "Bloodlust": effect missing
- [x] "Petrification": effect missing
- [x] "Fire Shield": effect played on attacker instead of defender (at least in case of counter-attack on Ifrite)
- [x] "Fire shield": cast animation is extremely fast in vcmi
- [x] "Teleport": should have fade-out -> fade in effect instead of normal movement animation

**Fixes multiple previously reported issues:**

- #1042 
- #960 
- #831
- #809 
- #789 
- #1045 
- #1048 
- #1051 
- #1139 
- #862
- #1331
- #1332
- #1299 
- #1307 
- #1378 
- #1304 

**Fixes multiple issues reported on Mantis (although some of these are duplicates)**

- 0002807 - Pit lord's summoning demons ability lacks visuals and sounds + GUI problems
- 0002508 - fire shields in efreet works even if you're using burning
- 0002809 - Cursor for spell-like creature abilities and for casting spell should be animated.
- 0003108 - Frost Ring range doesn't work
- 0000935 - Casting Teleport on flying creature makes it fly slowly to destination
- 0002806 - Teleportation spell lacking visuals
- 0000439 - Large units unnecesarily turn around during attack.
- 0003111 - Death stare's sound effect
- 0002859 - animation with resurrection vampire lord
- 0002558 - Being in the attack unfold the left to the right and scroll
- 0001068 - Incorrect animation order for retaliating Units - First hit animation is sown, then the turn and retaliate animation
- 0002834 - Disappearing flag
- 0002784 - Tower: creatures clip into the town walls on siege
- 0003125 - Palisade covering other elements of the battleground
- 0001059 - Heroes during battle no longer have flags
- 0002525 - Battle: if stack located near to the hero right-click displays the statistics of the hero
- 0003206 - Bugged "Start Walking" animation
- 0003073 - Casting and spell effect animations are played simultaneously instead of consecutively.
- 0002975 - Cyclops Kings don't use their 2-hex attack animation
- 0002808 - Cloning spell bugs and lacking visuals representation + stupid AI
- 0002746 - Incorrect visuals of the grid shadow near Moat hexes.
- 0002549 - One of Necropolis moat graphics is shifted outside moat.
- 0002531 - Implosion spell - unit should get hit and play damage animation when spell animation starts, not when it ends
- 0002452 - VCMI can't display 2hex-attack from def files.
- 0002244 - Game prints error when enemy steps on quicksand
- 0001318 - Multiple spell animations are shown simultaneously instead of consecutively
- 0000093 - Wrong/Missing spell animations

### CODE REVIEW

**Comment by IvanSavenko** [comment]
Marking this as ready for review.
I'll likely push a few more commits, to fix some minor remaining bugs but nothing major.
Conflicts with develop and CI will be fixed a bit later, once beta is merged into develop.

Updated PR description to reflect changes in branch (damn, that's a lot)

File: client/CMT.cpp [hunk 1]
```diff
@@ -468,10 +468,9 @@ int main(int argc, char * argv[])
 	if(!settings["session"]["headless"].Bool())
 	{
 		pomtime.getDiff();
-		CCS->curh = new CCursorHandler();
-		graphics = new Graphics(); // should be before curh->init()
+		graphics = new Graphics(); // should be before curh
 
-		CCS->curh->initCursor();
```
Comment (Nordsoft91) [inline client/CMT.cpp:474]: initCursor is not needed anymore?

File: client/CPlayerInterface.cpp [hunk 2]
```diff
@@ -954,24 +952,25 @@ void CPlayerInterface::battleStacksAttacked(const std::vector<BattleStackAttacke
...
+		info.defender       = defender;
+		info.attacker       = attacker;
+		info.damageDealt    = elem.damageAmount;
+		info.amountKilled   = elem.killedAmount;
+		info.spellEffect    = SpellID::NONE;
+		info.indirectAttack = ranged;
+		info.killed         = elem.killed();
+		info.rebirth        = elem.willRebirth();
+		info.cloneKilled    = elem.cloneKilled();
+		info.fireShield    = elem.fireShield();
```
Comment (Nordsoft91) [inline client/CPlayerInterface.cpp:968]: Not aligned :)

File: client/widgets/AdventureMapClasses.h [hunk 3]
```diff
@@ -11,6 +11,7 @@
 
 #include "ObjectLists.h"
 #include "../../lib/FunctionList.h"
+#include "../../lib/int3.h"
```
Comment (Nordsoft91) [inline client/widgets/AdventureMapClasses.h:14]: Excessive?

File: lib/NetPacks.h [hunk 4]
```diff
@@ -1620,7 +1621,6 @@ struct BattleStackAttacked
 		h & flags;
 		h & killedAmount;
 		h & damageAmount;
-		h & effect;
```
Comment (Nordsoft91) [inline lib/NetPacks.h:1623]: For 1.2 serialization is not broken yet. Can be fixed easily
if(version < xxx)
{
  int stub;
  h & stub;
}

File: lib/NetPacks.h [hunk 5]
```diff
@@ -1545,6 +1545,7 @@ struct BattleStackMoved : public CPackForClient
 		h & stack;
 		h & tilesToMove;
 		h & distance;
+		h & teleporting;
```
Comment (Nordsoft91) [inline lib/NetPacks.h:1548]: Please, consider making backward compatibility

**Review by Nordsoft91 — COMMENTED** [review]
Previewed 20%

File: client/CMT.cpp (hunk 1 above)
Comment (IvanSavenko) [reply client/CMT.cpp:474]: No, code from that method moved to constructor

File: lib/NetPacks.h (hunk 4 above)
Comment (IvanSavenko) [reply lib/NetPacks.h:1623]: There were somewhat large changes for netpacks, so no. This case may be fixable, but others probably won't be. 
So multiplayer compatibility IS broken. Save compatibility is doable, will recheck

File: lib/NetPacks.h (hunk 5 above)
Comment (IvanSavenko) [reply lib/NetPacks.h:1548]: Marking as resolved.
Unfortunately don't see a way to add compatibility for all *netpacks*, so multiplayer between 1.1 & 1.2 will be broken.
Save compatibility with 1.1 should be fixed.

Comment (Nordsoft91) [reply lib/NetPacks.h:1548]: as offtop, we should introduce separate version for net packs

**Comment by kambala-decapitator** [comment]
using this branch I can load neither a save from develop nor from 1.1 release.

- develop: [save](https://github.com/vcmi/vcmi/files/10313095/Archive.tar.gz) (from #1307), error: **Failed to load game: ios_base::clear: unspecified iostream_category error**
- 1.1: [save](https://github.com/vcmi/vcmi/files/10300661/Archive.tar.gz) (from #1301), error: **Failed to load game: Cannot find type descriptor for type 9StartInfo. Was it registered?**

**Comment by IvanSavenko** [comment]
@kambala-decapitator 
Serialization fixed. Haven't tested 1.1 save but develop saves can be loaded here

**Comment by kambala-decapitator** [comment]
with **No Battle Music** mod on, I get stuck in the Tactics phase - first creature is never selected and I can't select manually with mouse. UI thread isn't stuck as all animations keep working.

Screenshot 2022-12-30 at 11 09 22

On game quit there's a crash: [crash.txt](https://github.com/vcmi/vcmi/files/10323586/crash.txt). Maybe just the crashed thread's trace would be sufficient:

```
Thread 8 Crashed:: CClient::commenceTacticPhaseForInt
0   vcmiclient                    	       0x1072765bc CClient::commenceTacticPhaseForInt(std::__1::shared_ptr<CBattleGameInterface>) + 140
1   vcmiclient                    	       0x1072eb342 void boost::_bi::list2<boost::_bi::value<CClient*>, boost::_bi::value<std::__1::shared_ptr<CBattleGameInterface> > >::operator()<boost::_mfi::mf1<void, CClient, std::__1::shared_ptr<CBattleGameInterface> >, boost::_bi::list0>(boost::_bi::type<void>, boost::_mfi::mf1<void, CClient, std::__1::shared_ptr<CBattleGameInterface> >&, boost::_bi::list0&, int) + 82
2   vcmiclient                    	       0x1072eb2e4 boost::detail::thread_data<boost::_bi::bind_t<void, boost::_mfi::mf1<void, CClient, std::__1::shared_ptr<CBattleGameInterface> >, boost::_bi::list2<boost::_bi::value<CClient*>, boost::_bi::value<std::__1::shared_ptr<CBattleGameInterface> > > > >::run() + 36
3   libboost_thread.dylib         	       0x109810c42 boost::(anonymous namespace)::thread_proxy(void*) + 130
4   libsystem_pthread.dylib       	    0x7ff81aa5d4e1 _pthread_start + 125
5   libsystem_pthread.dylib       	    0x7ff81aa58f6b thread_start + 15
```

**Comment by kambala-decapitator** [comment]
in the exact same battle attempt to shoot with Storm/Ice Elementals fails.

client log:

```
TRACE network [0x70000a809000] - Send battle action to server: {BattleAction: side '1', stackNumber '8', actionType 'Wait', actionSubtype '-1', target {}}
TRACE network [0x70000a809000] - Sending a request "10MakeAction". It'll have an ID=16.
TRACE network [0x70000a809000] - Sending a pack of type 10MakeAction
TRACE network [0x70000a703000] - Received CPack of type 11StartAction
TRACE global [0x70000a703000] - CBattleConsole message: The Serpent Flies pause, and wait for a better time to act.
TRACE network [0x70000a703000] - 	Made first apply on cl: 11StartAction
TRACE network [0x70000a703000] - 	Applied on gs: 11StartAction
TRACE network [0x70000a703000] - 	Made second apply on cl: 11StartAction
TRACE network [0x70000a703000] - Received CPack of type 9EndAction
TRACE network [0x70000a703000] - 	Made first apply on cl: 9EndAction
TRACE network [0x70000a703000] - 	Applied on gs: 9EndAction
TRACE network [0x70000a703000] - 	Made second apply on cl: 9EndAction
TRACE network [0x70000a703000] - Received CPack of type 14PackageApplied
TRACE network [0x70000a703000] - 	Made first apply on cl: 14PackageApplied
TRACE network [0x70000a703000] - 	Applied on gs: 14PackageApplied
TRACE network [0x70000a703000] - 	Made second apply on cl: 14PackageApplied
TRACE network [0x70000a703000] - Received CPack of type 20BattleSetActiveStack
TRACE network [0x70000a703000] - 	Made first apply on cl: 20BattleSetActiveStack
TRACE network [0x70000a703000] - 	Applied on gs: 20BattleSetActiveStack
TRACE network [0x70000a703000] - 	Made second apply on cl: 20BattleSetActiveStack
TRACE global [0x70000a786000] - Awaiting command for red battle stack [2]: 26 of Storm Elementals from slot 0 of armyobj=5917
TRACE global [0x11019d600] - Setting command for red battle stack [2]: 26 of Storm Elementals from slot 0 of armyobj=5917
TRACE global [0x70000a786000] - Giving command for red battle stack [2]: 26 of Storm Elementals from slot 0 of armyobj=5917
TRACE network [0x70000a786000] - Send battle action to server: {BattleAction: side '0', stackNumber '2', actionType 'Shoot', actionSubtype '-1', target {{BattleHex: x '15', y '2', hex '49'},}}
TRACE network [0x70000a786000] - Sending a request "10MakeAction". It'll have an ID=17.
TRACE network [0x70000a786000] - Sending a pack of type 10MakeAction
TRACE network [0x70000a703000] - Received CPack of type 13SystemMessage
TRACE network [0x70000a703000] - 	Made first apply on cl: 13SystemMessage
TRACE network [0x70000a703000] - 	Applied on gs: 13SystemMessage
ERROR network [0x70000a703000] - System message: Server encountered a problem: Cannot shoot!
TRACE network [0x70000a703000] - 	Made second apply on cl: 13SystemMessage
TRACE network [0x70000a703000] - Received CPack of type 14PackageApplied
TRACE network [0x70000a703000] - 	Made first apply on cl: 14PackageApplied
TRACE network [0x70000a703000] - 	Applied on gs: 14PackageApplied
```

server log:

```
TRACE global [0x70000b6e1000] - Activating unnamed battle stack [8]: 27 of Serpent Flies from slot 1 of armyobj=1493
TRACE network [0x70000b6e1000] - 	Sending to all clients: 20BattleSetActiveStack
TRACE network [0x70000b6e1000] - Sending a pack of type 20BattleSetActiveStack
TRACE network [0x70000b6e1000] - 	Applied on gs: 20BattleSetActiveStack
TRACE network [0x70000b65e000] - Received CPack of type 10MakeAction
TRACE global [0x70000b65e000] - Making action: {BattleAction: side '1', stackNumber '8', actionType 'Wait', actionSubtype '-1', target {}}
TRACE network [0x70000b65e000] - 	Sending to all clients: 11StartAction
TRACE network [0x70000b65e000] - Sending a pack of type 11StartAction
TRACE network [0x70000b65e000] - 	Applied on gs: 11StartAction
TRACE network [0x70000b65e000] - 	Sending to all clients: 9EndAction
TRACE network [0x70000b65e000] - Sending a pack of type 9EndAction
TRACE network [0x70000b65e000] - 	Applied on gs: 9EndAction
TRACE global [0x70000b65e000] - Message 10MakeAction successfully applied!
TRACE network [0x70000b65e000] - Sending a pack of type 14PackageApplied
TRACE global [0x70000b6e1000] - Activating red battle stack [2]: 26 of Storm Elementals from slot 0 of armyobj=5917
TRACE network [0x70000b6e1000] - 	Sending to all clients: 20BattleSetActiveStack
TRACE network [0x70000b6e1000] - Sending a pack of type 20BattleSetActiveStack
TRACE network [0x70000b6e1000] - 	Applied on gs: 20BattleSetActiveStack
TRACE network [0x70000b65e000] - Received CPack of type 10MakeAction
TRACE global [0x70000b65e000] - Making action: {BattleAction: side '0', stackNumber '2', actionType 'Shoot', actionSubtype '-1', target {{BattleHex: x '15', y '2', hex '49'},}}
TRACE network [0x70000b65e000] - 	Sending to all clients: 13SystemMessage
TRACE network [0x70000b65e000] - Sending a pack of type 13SystemMessage
ERROR global [0x70000b65e000] - Cannot shoot!
TRACE global [0x70000b65e000] - Message 10MakeAction successfully applied!
TRACE network [0x70000b65e000] - Sending a pack of type 14PackageApplied
TRACE global [0x70000b6e1000] - Activating red battle stack [2]: 26 of Storm Elementals from slot 0 of armyobj=5917
TRACE network [0x70000b6e1000] - 	Sending to all clients: 20BattleSetActiveStack
TRACE network [0x70000b6e1000] - Sending a pack of type 20BattleSetActiveStack
TRACE network [0x70000b6e1000] - 	Applied on gs: 20BattleSetActiveStack
TRACE network [0x70000b65e000] - Received CPack of type 10MakeAction
TRACE global [0x70000b65e000] - Making action: {BattleAction: side '0', stackNumber '2', actionType 'Shoot', actionSubtype '-1', target {{BattleHex: x '15', y '2', hex '49'},}}
TRACE network [0x70000b65e000] - 	Sending to all clients: 13SystemMessage
TRACE network [0x70000b65e000] - Sending a pack of type 13SystemMessage
ERROR global [0x70000b65e000] - Cannot shoot!
TRACE global [0x70000b65e000] - Message 10MakeAction successfully applied!
TRACE network [0x70000b65e000] - Sending a pack of type 14PackageApplied
TRACE global [0x70000b6e1000] - Activating red battle stack [2]: 26 of Storm Elementals from slot 0 of armyobj=5917
TRACE network [0x70000b6e1000] - 	Sending to all clients: 20BattleSetActiveStack
TRACE network [0x70000b6e1000] - Sending a pack of type 20BattleSetActiveStack
TRACE network [0x70000b6e1000] - 	Applied on gs: 20BattleSetActiveStack
TRACE network [0x70000b65e000] - Received CPack of type 10MakeAction
TRACE global [0x70000b65e000] - Making action: {BattleAction: side '0', stackNumber '2', actionType 'Wait', actionSubtype '-1', target {{BattleHex: x '-1', y '0', hex '-1'},}}
TRACE network [0x70000b65e000] - 	Sending to all clients: 11StartAction
TRACE network [0x70000b65e000] - Sending a pack of type 11StartAction
TRACE network [0x70000b65e000] - 	Applied on gs: 11StartAction
TRACE network [0x70000b65e000] - 	Sending to all clients: 9EndAction
TRACE network [0x70000b65e000] - Sending a pack of type 9EndAction
TRACE network [0x70000b65e000] - 	Applied on gs: 9EndAction
TRACE global [0x70000b65e000] - Message 10MakeAction successfully applied!
TRACE network [0x70000b65e000] - Sending a pack of type 14PackageApplied
TRACE global [0x70000b6e1000] - Activating red battle stack [3]: 34 of Pixies from slot 1 of armyobj=5917
```

After a few more moves I see that something's seriously broken: all creatures deal 0-1 damage, strange spells appear out of nowhere... Can it be related to loading save from develop?

Full logs: [Archive.tar.gz](https://github.com/vcmi/vcmi/files/10323630/Archive.tar.gz)

Also crash on quitting game from the battle directly:

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [1954]

VM Region Info: 0 is not in any region.  Bytes before following region: 4450996224
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      1094cd000-10ac79000    [ 23.7M] r-x/r-x SM=COW  ...OS/vcmiclient

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   vcmiclient                    	       0x1097b51ce CPlayerInterface::~CPlayerInterface() + 62
1   vcmiclient                    	       0x10951a1cb BattleInterface::~BattleInterface() + 1323
2   vcmiclient                    	       0x1097b48b1 std::__1::shared_ptr<BattleInterface>::~shared_ptr() + 49
3   libsystem_c.dylib             	    0x7ff81a955de4 __cxa_finalize_ranges + 409
4   libsystem_c.dylib             	    0x7ff81a955bfe exit + 35
5   vcmiclient                    	       0x10978dbca quitApplication() + 1162
6   vcmiclient                    	       0x10979b195 handleQuit(bool)::$_8::operator()() const + 21
7   vcmiclient                    	       0x10979b179 decltype(static_cast<handleQuit(bool)::$_8&>(fp)()) std::__1::__invoke<handleQuit(bool)::$_8&>(handleQuit(bool)::$_8&) + 9
8   vcmiclient                    	       0x10979b169 void std::__1::__invoke_void_return_wrapper<void, true>::__call<handleQuit(bool)::$_8&>(handleQuit(bool)::$_8&) + 9
9   vcmiclient                    	       0x10979b159 std::__1::__function::__alloc_func<handleQuit(bool)::$_8, std::__1::allocator<handleQuit(bool)::$_8>, void ()>::operator()() + 9
10  vcmiclient                    	       0x10979b119 std::__1::__function::__func<handleQuit(bool)::$_8, std::__1::allocator<handleQuit(bool)::$_8>, void ()>::operator()() + 9
11  vcmiclient                    	       0x10950ab18 void CFunctionList<void ()>::operator()<>() const + 72
12  vcmiclient                    	       0x10950ab18 void CFunctionList<void ()>::operator()<>() const + 72
13  vcmiclient                    	       0x10958b329 CButton::onButtonClicked() + 537
14  vcmiclient                    	       0x109559def CGuiHandler::handleCurrentEvent() + 1935
15  vcmiclient                    	       0x1095595d2 CGuiHandler::handleEvents() + 354
16  vcmiclient                    	       0x1097c506a CPlayerInterface::update() + 666
17  vcmiclient                    	       0x10955b3c8 CGuiHandler::renderFrame() + 168
18  vcmiclient                    	       0x109783284 main + 20740
19  dyld                          	       0x11012252e start + 462
```

**Comment by IvanSavenko** [comment]
No battle music - should have been solved in this commit: https://github.com/vcmi/vcmi/pull/1229/commits/da7766e90b5c9caf170c75d096f9d297ea4a842f
Will recheck

Crash on quitting game - will recheck

Rest could be serialization-related.

**Comment by kambala-decapitator** [comment]
> No battle music - should have been solved in this commit: [da7766e](https://github.com/vcmi/vcmi/commit/da7766e90b5c9caf170c75d096f9d297ea4a842f)

I used the latest CI artifact, it should have the commit as far as I see

**Comment by kambala-decapitator** [comment]
in this branch I started hearing broken sound periodically similarly to #1074 , but I'm on macOS. Don't think it's present in develop (and definitely not in 1.1).

**Comment by IvanSavenko** [comment]
> in this branch I started hearing broken sound periodically similarly to #1074 , but I'm on macOS. Don't think it's present in develop (and definitely not in 1.1).

When exactly? Which sound are broken? Is this broken *sound* or *music*?

Also, reproduced bugs you've mentioned in previous comment, fix incoming.

**Comment by IvanSavenko** [comment]
Strictly speaking, #1074 was not something Linux-specific, it is just that some Linux distros prefer to use latest libraries. If you were to upgrade SDL to one of affected versions, you're likely to get broken sound too.

**Comment by kambala-decapitator** [comment]
> After a few more moves I see that something's seriously broken: all creatures deal 0-1 damage, strange spells appear out of nowhere...

doesn't happen in new game

> When exactly? Which sound are broken? Is this broken sound or music?

sorry, can't say for sure, as I don't know what is music and what is sound in the game. random sounds (or music :) ). For instance, when you start/load the game - during the intro/"new day" sound. I play with music volume set to 0.

**Comment by kambala-decapitator** [comment]
> If you were to upgrade SDL to one of affected versions, you're likely to get broken sound too.

never experienced that on macOS, unlikely that it suddenly started happening. SDL versions in 1.1 are the same as in develop.

**Comment by kambala-decapitator** [comment]
one more observation: units number after being hit changes _before_ the hit animation (noticed when my creature was shot). Not sure if it's the same in 1.1 though, never really payed attention.

**Comment by kambala-decapitator** [comment]
after opening spell book and closing it, hovering enemy creature no longer shows potential damage. Battle log stays on "cast spell" message. Further battle log messages don't appear - it just stays on "cast spell".

**Comment by kambala-decapitator** [comment]
> Which sound are broken?

one more example: sound of map reveal from Redwood Observatory.

**Comment by IvanSavenko** [comment]
Sound issues - unable to reproduce, can't think of something that could have affected it, especially outside of battle

Stack amount boxes - known issue, will rework these boxes in next PR

Spell book - will investigate

And pushing fixes...

**Comment by kambala-decapitator** [comment]
> Sound issues - unable to reproduce, can't think of something that could have affected it, especially outside of battle

sorry, false alarm, happens in develop and 1.1 as well. Although subjectively in this branch they're louder.

SDL used is 2.24.1, needs update to get rid of the issue.

**Comment by IvanSavenko** [comment]
Spellbook bug - fixed, status bar updates correctly now
However there is no damage estimation - same is true for 1.1 branch and possibly - H3 (haven't checked that part)

**Comment by kambala-decapitator** [comment]
> same is true for 1.1 branch and possibly - H3 (haven't checked that part)

no, in 1.1 estimation works. in oh3 it's unavailable indeed, only in hd mod (or just hota, don't remember).

**Comment by IvanSavenko** [comment]
Are you sure?
Just checked vcmi/master again (which should match 1.1)
Don't see anything for spell damage estimation in code. Only "Cast <spell> on <creature>" message. Which is what I see in game.
Only attacks by creatures have damage estimation.

**Comment by kambala-decapitator** [comment]
Sorry for inaccurate description, I was referring to creature damage.

But note that I didn't say that I selected a spell after opening spell book ;)

**Comment by dydzio0614** [comment]
H3 has damage estimation when you toggle on creature stats mini window that is unimplemented in VCMI

**Comment by IvanSavenko** [comment]
> H3 has damage estimation when you toggle on creature stats mini window in battle settings - that is unimplemented in VCMI My opinion is that we should show unconditionally amount of damage, amount of killed and if creature will retaliate

Will keep that in mind, but so far my goals for battle console/status bar were as simple as "don't break it". As long as it is working as before - this PR is good to go. 
There is simply too much stuff in battles that needs to be fixed/implemented.

**Comment by kambala-decapitator** [comment]
> amount of killed

FYI there's a separate issue #857

**Comment by dydzio0614** [comment]
Reported by tester: cloned unit doesn't have blue color (so fat clone tested on archangel, with expert water magic)

**Comment by IvanSavenko** [comment]
Issues discovered during streaming session:

- [ ] Clone blue tint died
- [ ] "Q" hotkey breaks BattleWindow UI
- [ ] All for One, Monster stack to north-east - obstacle behind creature stack
- [ ] Firewall - crash
- [ ] Fire shield does 0 damage (attacked 1 pixie - should not activate)
- [ ] Movement animation restarts on each tile? (CENTAUR AT HIGH SPEED !!!)
- [ ] Selection highlight stays during teleport
- [ ] Hero animation plays only after mines placement
- [ ] Remove mouse-hover animation on petrified creature (blue border should remain)
- [ ] Recheck Destroy Undead spell, non-expert, Paladin from Tides of War mod
- [ ] Archdevil appears for 1 frame during teleport
- [ ] Visual artifacts during Efreeti movement startup
- [ ] Recheck Titans & mages ranged attack effect animation
- [ ] weakness spell has rust dragon breath animation effect. Should be C17SPW0.def
- [ ] Phoenix has broken border selection highlight
- [ ] Quick sands: animation too fast
- [ ] Quick sands: should appear below movement shadow?

**Comment by dydzio0614** [comment]
Seems you changed ISpellMechanics::rangeInHexes and BattleSpellMechanics::rangeInHexes - could you also change `MOCK_CONST_METHOD2(rangeInHexes, std::vector<BattleHex>(BattleHex, bool *));` to `MOCK_CONST_METHOD1(rangeInHexes, std::vector<BattleHex>(BattleHex));` in test/mock/mock_spells_Mechanics.h

**Comment by dydzio0614** [comment]
2 more things to recheck for this or another PR:
1. remove obstacle spell
2. lich creature cloud sound

**Comment by IvanSavenko** [comment]
> 2 more things to recheck for this or another PR:
> 
>     1. remove obstacle spell
> 
>     2. lich creature cloud sound

1. Known, listed in #1219 
2. Details? I remember talks about that sound on stream, but couldn't figure out details

**Comment by dydzio0614** [comment]
IIRC only the projectile sound impact played, but the cloud sound did not? Would need to recheck myself :P

**Comment by IvanSavenko** [comment]
Got it, thanks.
Magogs with their fireball likely to have same issue then.

**Review by dydzio0614 — APPROVED** [review]
Firewall crash is fixed and some playtesting showed battles working generally well so I think it's fine to merge this. Hopefully there are not too many potentially useful code features that got removed while simplifying code.

File: client/battle/BattleStacksController.cpp [hunk 6]
```diff
@@ -850,7 +850,7 @@ void BattleStacksController::updateHoveredStacks()
 			continue;
 
 		stackAnimation[stack->ID]->setBorderColor(AnimationControls::getBlueBorder());
-		if (stackAnimation[stack->ID]->framesInGroup(ECreatureAnimType::MOUSEON) > 0 && stack->alive())
+		if (stackAnimation[stack->ID]->framesInGroup(ECreatureAnimType::MOUSEON) > 0 && stack->alive() && !stack->isFrozen())
```
[the remark this answers is not in the document]
Comment (IvanSavenko) [reply client/battle/BattleStacksController.cpp:855]: I'd rather call what you're describing as a bug in H3

**Comment by IvanSavenko** [comment]
Fixed most of bugs discovered during stream. Remaining ones:
"Q" hotkey breaks BattleWindow UI - will look into it later, maybe even tomorrow.

Hero animation plays only after mines placement - probably postponed till next PR, 

All for One, Monster stack to north-east - obstacle in front of creature stack - unable to reproduce, I think I need exact same set of mods, will try to reproduce one more time, while using "Tides of War" mod or what's its name.

@dydzio0614 If you wish you can ask streamer for another run. Both to discover anything else I may have missed & to show him results of his bughunting.

**Comment by dydzio0614** [comment]
What about paladins from tides of war? Anyway, he might do another run but it won't happen very soon I guess

**Comment by IvanSavenko** [comment]
> What was wrong with paladins ability from tides of war? 

Paladins had Destroy Undead, which is "massive" spell - one that hits every applicable creature on the battlefield.
For some reason, there were a bunch of "workarounds" in code, related to massive spells cast by creatures. I removed one of the earlier, when fixing Ice Ring targeting. And that may have broken this ability.
After removing all such workarounds Paladins ability worked fine... so fixed I guess?

>Anyway, he might do another run but it won't happen very soon I guess

Understood. Well, thanks for the test anyway :)

**Review by dydzio0614 — CHANGES_REQUESTED** [review]
BTW I just haveone thing in mind that change my position about merging until I learn more: You increased framerate to 60 - this will cause bugs in another game areas, for example adventure map counting frames for animations IIRC.

PS. Did some stream re-watch and found that there was complaint about disruption ray spell (the 2nd level missile spell that decreases defense) - about spell sound being played at wrong moment. My personal impression is that the projectile for that spell might be too slow as well, but will need to check myself in your branch to give more comment about this.

**Comment by IvanSavenko** [comment]
>You increased framerate to 60 - this will cause bugs in another game areas, for example adventure map counting frames for animations IIRC

I won't call it "bug", and I don't expect this change to cause any major issues, but yeah, there will be 20% speedup in hero movement, adventure map animations & (I think) animation playback speed for town buildings.
48 fps (or any other than 15/30/60/120) leads to graphical artifact, can't remember its proper name, but it was one of the causes for that Centaur movement glitch.
This is because your monitor renders 60 frames each second even if game generates 48, leading to situation when same frame will be sent to screen twice, resulting in uneven movements/animations.

Town buildings can be rechecked and converted to time-based animation easily at any point due to small & simple code.
Adventure map would have likely needed major changes anyway if I were to move forward with hardware acceleration/SDL abstraction task.

So for now (as of this PR) I am keeping it as it, and revisit later if necessary. 

I'd even say that town/map may actually look smoother than before because game framerate matches monitor refresh rate.

>PS. On a side note: did some stream re-watch and found that there was complaint about disruption ray spell (the 2nd level missile spell that decreases defense) - about spell sound being played at wrong moment. My personal impression is that the projectile for that spell might be too slow as well, but will need to check myself in your branch to give more comment about this.

Again, I don't bother much with animation speed right now, and I mean both "how quickly things move across screen" and "how quickly animations switch to next frame".
This can be tweaked at any point later by anyone else (including me). For now I am focusing on complex bugs that require good understanding of vcmi code.

As for timing - that thing sounds very wrong in H3 as well. Basically, they have single sound that includes both projectile sound and hit sound. Even in H3 sound will be out of sync on slow & fast animation speed.

**Comment by dydzio0614** [comment]
New bug: battle queue order now shows only if you right-click hero, unit, defense/surrender etc. button or other thing that triggers something on right click :/

**Comment by dydzio0614** [comment]
+1 bug compared to develop - battle console: typing triggers hotkeys (A for autoattack at least) + pressing enter doesn't refresh its content until somethng is hovered etc.

**Comment by kambala-decapitator** [comment]
experienced the following in 1.1 release: one of enemy units didn't display its possible move range, I think it's the only time I noticed it. The unit wasn't under Blind or similar effect.

https://user-images.githubusercontent.com/1557784/210745041-f8bc2ce8-256c-4929-bba5-c9aa15a8427d.mov

**Comment by IvanSavenko** [comment]
@dydzio0614 both bugs are now fixed, will push a bit later today.
@kambala-decapitator unable to reproduce so far.

**Review by dydzio0614 — APPROVED** [review]
Looks OK now

**Comment by IvanSavenko** [comment]
And sorry, @dydzio0614 , I was wrong and all projectiles including spell-based were still using speed based on frame count.
Only projectile image animation was time-based.
Fixed now.

**Comment by kambala-decapitator** [comment]
I'd test the latest state over the next few days

File: client/battle/CreatureAnimation.cpp [hunk 7]
```diff
@@ -115,12 +115,12 @@ float AnimationControls::getCreatureAnimationSpeed(const CCreature * creature, c
 
 float AnimationControls::getProjectileSpeed()
 {
-	return static_cast<float>(settings["battle"]["animationSpeed"].Float() * 100);
```
Comment (dydzio0614) [inline client/battle/CreatureAnimation.cpp:113]: multiplier of projectile speed compared to multiplier of catapult speed has different ratio now, is it intended?

File: client/battle/CreatureAnimation.cpp [hunk 8]
```diff
@@ -115,12 +115,12 @@ float AnimationControls::getCreatureAnimationSpeed(const CCreature * creature, c
 
 float AnimationControls::getProjectileSpeed()
 {
-	return static_cast<float>(settings["battle"]["animationSpeed"].Float() * 100);
+	return static_cast<float>(settings["battle"]["animationSpeed"].Float() * 4000);
```
Comment (dydzio0614) [inline client/battle/CreatureAnimation.cpp:118]: multiplier of projectile speed compared to multiplier of catapult speed has different ratio now, is it intended?

**Comment by dydzio0614** [comment]
BTW just information: more things than initially expected by me are affected by framerate change - that includes main menu animation speed, map scrolling speed, and some more stuff I don't remember right now

File: client/battle/CreatureAnimation.cpp (hunk 8 above)
Comment (IvanSavenko) [reply client/battle/CreatureAnimation.cpp:118]: Hmm... Not deliberate - I picked sensible values for both projectile types, without taking into account previous ratio.
I doubt that either old or new values match H3 settings, so don't think that there is any *need* to maintain same ratio. 
Proper solution would be to actually compare these values with H3, but same can be said about pretty much any number in this class.

**Comment by IvanSavenko** [comment]
> that includes main menu animation speed, 

Can switch it to 60 fps, looks like H3 videos were recorded at 15 fps, which is 1/4 of 60.
Proper fix would be to toggle it to time-based, using decoded timings from video stream.

> map scrolling speed, 

Should be done alongside preparation to HW render, I'd like to add smooth scrolling anyway, at least for touchscreen, where 1 tile per move is simply too much of a change.

> and some more stuff I don't remember right now

Feel free to create issues for those, either one per "stuff" or main issue with task per "stuff".
In fact, I am leaning to creating one myself and rechecking everything H3 has animated

**Comment by kambala-decapitator** [comment]
observed the following: when a spell is resisted, sound of the spell is played instead of "magic resistance" sound. Dunno how it's in the 1.1 release.

**Comment by IvanSavenko** [comment]
"Resisted", as in Dwarf ability, correct?

**Comment by kambala-decapitator** [comment]
> "Resisted", as in Dwarf ability, correct?

yes

**Comment by kambala-decapitator** [comment]
not 100% sure, but it seemed to me that in 1.1 Liche doesn't hit adjacent creatures. Haven't tested in this branch yet.

**Comment by IvanSavenko** [comment]
> not 100% sure, but it seemed to me that in 1.1 Liche doesn't hit adjacent creatures. Haven't tested in this branch yet.

Lich attack does hit adjacent on this branch (and extremely likely to be case in 1.1)
Haven't checked damage calculations.
However hit animation on creatures plays BEFORE cloud animation. Added to list.

**Comment by kambala-decapitator** [comment]
@IvanSavenko please check #1304, just reproduced it in your branch as well

**Comment by kambala-decapitator** [comment]
can't say if it's the same in 1.1 or not

Screen Shot 2023-01-08 at 10 50 05

maybe related to #940? (I see it's about hota, but who knows)

**Comment by IvanSavenko** [comment]
Steps to reproduce please. Map/save & full list of mods

**Comment by kambala-decapitator** [comment]
Native Fortress terrain (swamp?), mods - nothing special, see https://github.com/vcmi/vcmi/issues/1304#issuecomment-1374506034

Random map, will check if I still have the save from this battle later.

BTW another issue, don't remember seeing it in 1.1: my Dragon Fly was petrified by Basilisk (Greater, if it matters), then the Basilisk hit the Fly thus removing the effect. However, the gray visual overlay stayed on the Fly until the end of battle. Can post SS later.

**Comment by IvanSavenko** [comment]
Wasn't able to load that save - some save compatibility issues.
What I need is:
- map (or save)
- location of battle
- exact list of mods
Battlefield obstacles are not completely random - they are bound to map tile, so these bugs should be reproducible

**Comment by IvanSavenko** [comment]
> BTW another issue, don't remember seeing it in 1.1: my Dragon Fly was petrified by Basilisk (Greater, if it matters), then the Basilisk hit the Fly thus removing the effect
Will look into it.
Definitely wasn't in 1.1 because 1.1 does not have petrification effect

**Comment by kambala-decapitator** [comment]
sorry, no save any more :( will be looking for the same obstacle to reproduce.

list of mods:

Screen Shot 2023-01-07 at 17 48 36

petrification SS (Fly's turn):

Screen Shot 2023-01-08 at 14 21 52

**Comment by kambala-decapitator** [comment]
one more example of obstacle issue, this time with save: [Archive.tar.gz](https://github.com/vcmi/vcmi/files/10371488/Archive.tar.gz) select second hero and attack the nearby Walking Dead

Screenshot 2023-01-09 at 11 09 16

**Comment by kambala-decapitator** [comment]
long messages in log don't look nice:

Screenshot 2023-01-09 at 12 23 55
Screenshot 2023-01-09 at 12 24 08

**Comment by kambala-decapitator** [comment]
petrify overlay is fixed, but now there's another issue with petrify: it's possible to command creature under effect (although the creature does nothing in such case)


https://user-images.githubusercontent.com/1557784/211283900-403668d0-73af-448b-845f-49fddc3165ab.mov

**Comment by IvanSavenko** [comment]
> one more example of obstacle issue, this time with save

Thanks. Will try to reproduce.

> long messages in log don't look nice:

Hmm... What H3 does here? Split message into multiple lines I suppose? 
VCMI 1.1 will simply ignore such lines, which is also a bad solution.

> petrify overlay is fixed, but now there's another issue with petrify: it's possible to command creature under effect (although the creature does nothing in such case)

I guess Mantis 0002925 is now confirmed. So old bug (blind & petrify are basically the same spell internally).

**Comment by IvanSavenko** [comment]
Obstacles placement:
Bug reproduced. After trying to figure out what went wrong I found out that vcmi/beta (and presumably, 1.1) also draw obstacles incorrectly, but in a different way.
vcmi/beta: obstacles on sacred lands(?) which should be rendered on TOP of the units are actually drawn below them. (can be easily reproduced on Arrogance - attack guardians of Tree of Knowledge to north-west)
vcmi/develop: (as well as this PR) some obstacles. e.g one that was discoveres by you should be rendered BELOW units, but actually drawn on TOP of them

Will move into a separate issue, don't see trivial fix right now, so merging this PR without changes to obstacles.

**Comment by kambala-decapitator** [comment]
in the new build the long poison message looks good, but now new issue arose: texts "move X here" / "attack X (Y-Z damage)" no longer appear in the battle log area :(


https://user-images.githubusercontent.com/1557784/211363299-98483772-3a63-4d26-8fb0-41161b4daf30.mov

**Comment by IvanSavenko** [comment]
Battle log is fixed.

@kambala-decapitator what do you think about merging this one? 
If you wish to playtest these changes further I can wait, but I don't expect any major problems from merge + it will allow me to start working on next parts. Any playtesting can still be done in develop branch.

**Comment by kambala-decapitator** [comment]
@IvanSavenko yeah, let's do it
