### PR TITLE
date time format

### LINKED ISSUE #3311: Same date & time of all autosave games
**Describe the bug**
If you want to load an autosave game, all of them have the same date & time so it is not possible to find out which is the latest one.

**Game logs**
Sorry, no logs, I am on Android.

**To Reproduce**
1. Play game, several rounds
2. Try to load an autosave game
3. All of them have the same date & time

**Expected behavior**
At least time of the saved games should be different.

**Actual behavior**
All the saved games have the same time (and dates).

**Did it work earlier?**
Yes, it worked okay before 1.4 version.

**Screenshots**
No screenshot.

**Version**
 - OS: Android
 - Version: 1.4.0 & 1.4.1

**Additional context**
Nothing.

### PR DESCRIPTION
**Pull request by Laserlicht**
fixes #3311

Datetime format for each language. Since there is no solution to get correct system format on each platform in c++.

### CODE REVIEW

File: lib/Languages.h [hunk 1]
```diff
@@ -79,27 +82,27 @@ inline const auto & getLanguageList()
...
+		{ "russian",     "Russian",     "Русский",    "CP1251", "ru", "%F %T", EPluralForms::UK_3, true },
+		{ "spanish",     "Spanish",     "Español",    "CP1252", "es", "%d/%m/%Y %T", EPluralForms::EN_2, true },
+		{ "swedish",     "Swedish",     "Svenska",    "CP1252", "sv", "%F %T", EPluralForms::EN_2, true },
+		{ "turkish",     "Turkish",     "Türkçe",     "CP1254", "tr", "%d.%m.%Y %T", EPluralForms::EN_2, true },
+		{ "ukrainian",   "Ukrainian",   "Українська", "CP1251", "uk", "%d.%m.%Y %T", EPluralForms::UK_3, true },
+		{ "vietnamese",  "Vietnamese",  "Tiếng Việt", "UTF-8",  "vi", "%d/%m/%Y %T", EPluralForms::VI_1, true }, // Fan translation uses special encoding
+
+		{ "other_cp1250", "Other (East European)",   "", "CP1250", "", "", EPluralForms::NONE, false },
+		{ "other_cp1251", "Other (Cyrillic Script)", "", "CP1251", "", "", EPluralForms::NONE, false },
+		{ "other_cp1252", "Other (West European)",   "", "CP1252", "", "", EPluralForms::NONE, false }
```
Comment (kambala-decapitator) [inline lib/Languages.h:105]: where did you get these formats from? Russian and Ukrainian having different formats makes no sense

Comment (Laserlicht) [reply lib/Languages.h:105]: https://en.wikipedia.org/wiki/Date_format_by_country (but sometimes there are multiple).

Feel free to make code suggestions for better formats if you know the usual formats. But we should use numeric only I think.

Comment (kambala-decapitator) [reply lib/Languages.h:105]: in that list (as well as to my knowledge) both use `dd.mm.yyyy`, so not sure why you picked different formats for those 2 languages

File: include/vstd/DateUtils.h [hunk 2]
```diff
@@ -5,7 +5,7 @@ VCMI_LIB_NAMESPACE_BEGIN
 namespace vstd
 {
 
-	DLL_LINKAGE std::string getFormattedDateTime(std::time_t dt);
+	DLL_LINKAGE std::string getFormattedDateTime(std::time_t dt, std::string format = "");
```
Comment (kambala-decapitator) [inline include/vstd/DateUtils.h:8]: what's the use case of declaring default value and then copy-pasting code to read current format from settings? Either put that expression right here as default value (if possible) or create wrapper that passes it automatically (as I understand, that value can't be fetched inside a vstd function)

Comment (Laserlicht) [reply include/vstd/DateUtils.h:8]: It's not used yet. Could also remove default value if it's better?

I don't want to use settings in vstd. That doesn't make sense for a "std" file, I think.

File: lib/vstd/DateUtils.cpp [hunk 3]
```diff
@@ -1,33 +1,29 @@
...
 		{
-			// locale not be available - keep default / global
+			try
+			{
+				s.imbue(std::locale(""));
+			}
+			catch(const std::runtime_error & e)
+			{
+				// locale not be available - keep default / global
+			}
```
Comment (IvanSavenko) [inline lib/vstd/DateUtils.cpp:22]:
```suggestion
```
Can be removed since we no longer try to use system locale

File: include/vstd/DateUtils.h (hunk 2 above)
Comment (kambala-decapitator) [reply include/vstd/DateUtils.h]: main point is to prevent copy-paste of reading from settings. You can create wrapper function inside the project (that is, not in vstd)

File: lib/vstd/DateUtils.cpp [hunk 4]
```diff
@@ -1,33 +1,29 @@
...
-#endif
-
 		std::tm tm = *std::localtime(&dt);
 		std::stringstream s;
-		try
-		{
-			s.imbue(std::locale(""));
-		}
-		catch(const std::runtime_error & e)
+		if(format.empty())
```
Comment (IvanSavenko) [inline lib/vstd/DateUtils.cpp:13]: Perhaps we should always explicitly specify format in caller code and remove this condition?

File: lib/vstd/DateUtils.cpp (hunk 3 above)
Comment (kambala-decapitator) [reply lib/vstd/DateUtils.cpp:22]: this code path is still used for `other_cp125*` languages

File: include/vstd/DateUtils.h (hunk 2 above)
Comment (IvanSavenko) [reply include/vstd/DateUtils.h]: Move to general text handler then?
Or to related TextOperations namespace?

File: lib/vstd/DateUtils.cpp (hunk 3 above)
Comment (IvanSavenko) [reply lib/vstd/DateUtils.cpp:22]: other_* languages can't be selected here - those can only be selected for H3 encoding. Not for languages.

File: include/vstd/DateUtils.h (hunk 2 above)
Comment (Laserlicht) [reply include/vstd/DateUtils.h]: Yes, I just didn't think it was necessary at the moment, as it is currently only used three times (settings are already used two times). I also wouldn't know where such a wrapper would fit in well.

File: lib/vstd/DateUtils.cpp (hunk 3 above)
Comment (Laserlicht) [reply lib/vstd/DateUtils.cpp:22]: Yes its an fallback. We could also remove and fallback to international format.

File: include/vstd/DateUtils.h (hunk 2 above)
Comment (kambala-decapitator) [reply include/vstd/DateUtils.h]: well, 3 > 1 :)

I also don't know, try following Ivan's advice

Comment (IvanSavenko) [reply include/vstd/DateUtils.h]: I suggest either TextOperations or general text handler class.
Even if there are "just" 3 usages, all 3 are rather hard to read due to extremely long statements.

So moving those into a dedicated method makes sense

File: lib/vstd/DateUtils.cpp (hunk 4 above)
Comment (kambala-decapitator) [reply lib/vstd/DateUtils.cpp:13]: considering that other_ languages will never get here, I agree with removing the condition

**Review by kambala-decapitator — APPROVED** [review]

**Review by IvanSavenko — APPROVED** [review]
