### PR TITLE
optimize skip video keys

### LINKED ISSUE #5528: Keyboard Volume roller incorrectly skips intro videos
**Describe the bug**
Keyboard Volume roller incorrectly skips intro videos.
It correctly does not skip campaign start/intermission videos.. But also no keyboard keys can skip them either, but  a left mouse click does.

**To Reproduce**
Use any keyboard with a volume roller/wheel/knob/button, spin/press it during intro video during startup, or post startup upon starting any chronicles campaign, it will play an intro video that also gets skipped like this.

**Expected behavior**
Really just dedicated keys should skip videos to prevent accidental skips (like my volumes too low i cant hear this and up the volume... ugh its gone). I'd guess its coded to ANY key, which can cause odd functions like this to trigger the skip. (and possibly bugs with other peripherals with unusual scan codes)
Suggested keys: Esc, Spacebar
And the behavior should be identical between intro video and campaign video.

**Actual behavior**
Strangely the campaign videos behave different than the intro videos. They are not skipped with volume wheel. 

**Did it work earlier?**
In the original game, this bug also exists. Tho worse as the volume wheel also skips campaign videos in the original game.

**Version**
- OS: Windows 11
- Version: 1.6.7

### PR DESCRIPTION
**Pull request by Laserlicht**
Campaign videos and main menu videos can skipped with ESC and ENTER now (mouse click still working).

Fixes #5528

### CODE REVIEW

File: client/mainmenu/CPrologEpilogVideo.cpp [hunk 1]
```diff
@@ -102,3 +103,14 @@ void CPrologEpilogVideo::clickPressed(const Point & cursorPosition)
...
 }
+
+void CPrologEpilogVideo::clickPressed(const Point & cursorPosition)
+{
+	exit();
+}
+
+void CPrologEpilogVideo::keyPressed(EShortcut key)
+{
+	if(key == EShortcut::GLOBAL_ACCEPT || key == EShortcut::GLOBAL_CANCEL)
```
Comment (IvanSavenko) [inline client/mainmenu/CPrologEpilogVideo.cpp:114]: There is already key that is bound to both Enter and Escape.
Accept / Cancel are for Yes/No dialogs and similar.
```suggestion
	if(key == EShortcut::GLOBAL_RETURN)
```
