### PR TITLE
fix campaign highscores

### LINKED ISSUE #4180: Campaign score should be the sum of each level
While finish the campaign, only one level score will be shown on High Score menu.

For example, from campaign Hack and Slash, I can get 2000 score for campaign in OH3, but only 483 in VCMI.

**Version**
 - OS: Windows, Android
 - Version: 1.5.3

### PR DESCRIPTION
**Pull request by Laserlicht**
fixes #4180

### CODE REVIEW

**Comment by Laserlicht** [comment]
@IvanSavenko Can you look over it? I do not really understand, when "Forward declaration" works and when not.
It's also compiler specific. It compiles locally but not in CI especially with android compiler.

**Comment by IvanSavenko** [comment]
> @IvanSavenko Can you look over it? I do not really understand, when "Forward declaration" works and when not. 

- Function parameter - forward declaration is enough
- Direct member of a class/struct (not pointer / reference) - requires include
- Pointer/reference member - forward declaration
- Various containers - this one is rather compiler-specific, so easier to use include
- shared_ptr - forward declaration
- unique_ptr - forward declaration works, but requires instantiation of `= default`-ed destructor in cpp

So in your case - you should be able to use forward-declaration in CServerHandler, but needs direct include for `std::vector<HighScoreParameter>` in CampaignState

**Comment by Laserlicht** [comment]
> So in your case - you should be able to use forward-declaration in CServerHandler, but needs direct include for `std::vector<HighScoreParameter>` in CampaignState

Yes. Was my first test like this. Compiles under Linux.

But Android has an problem: `arithmetic on a pointer to an incomplete type 'HighScoreParameter'`

I don't know, how to fix.

**Comment by Laserlicht** [comment]
`error: reference to 'HighScoreParameter' is ambiguous` - a nightmare. :D

**Comment by IvanSavenko** [comment]
Library declaration must be wrapped in macro:
```
VCMI_LIB_NAMESPACE_BEGIN
struct HighScoreParameter;
VCMI_LIB_NAMESPACE_END
```

File: lib/gameState/HighScore.h [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+
+class DLL_LINKAGE HighScoreParameter
+{
+public:
+	int difficulty;
+	int day;
+	int townAmount;
+	bool usedCheat;
+	bool hasGrail;
+	bool allDefeated;
```
Comment (IvanSavenko) [inline lib/gameState/HighScore.h:22]:
```suggestion
	bool allEnemiesDefeated;
```

File: lib/gameState/HighScore.h [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+VCMI_LIB_NAMESPACE_BEGIN
+
+class DLL_LINKAGE HighScoreParameter
+{
+public:
+	int difficulty;
+	int day;
+	int townAmount;
+	bool usedCheat;
+	bool hasGrail;
```
Comment (IvanSavenko) [inline lib/gameState/HighScore.h:21]: Just in case - can you double-check that this flag works? There was report somewhere that it was broken (unconfirmed)

Comment (Laserlicht) [reply lib/gameState/HighScore.h:21]: Checked following:
- no grail
- grail in hero inventar
- grail in hero inventar + hero in town
- grail as building in town

For the three last you will get the correct 25 points. Seems correct. Cannot replicate the reported error.

Just as reference, report was:

> Now for my question: the last game I played was a random map generated with a Spider template. Free for all, me and 7 npc:s.
> First time the game ended I did not dig the grail and got some amount of points. Then I decided to try and find the grail from the map so I loaded an autosave, dug around and found it pretty fast and ended the game. The score, however, did not go up as I think it should have gone. Instead, I lost 3 points from the final score which is due to the couple of days of digging.
