### PR TITLE
PlayerConnectionID rework: struct wrapper; Fix hotseat and placing players in lobby

### LINKED ISSUE #5986: Lobby doesn't work properly
**Describe the bug**
Lobby doesn't work properly and counts 2 players as one.

**Game logs**
No need

**To Reproduce**
1. Enter lobby
2. Host a game
3. Enter the room from another device
4. See issue

**Expected behavior**
2 players being in room

**Actual behavior**
Lobby counts two players as 1.

**Did it work earlier?**
I think it did.

**Screenshots**
No need, I assume.

**Version**

- OS: Windows
- Version: develop

### LINKED ISSUE #6069: Hot seat never allows more players
In 1.7 develop when launching Hot seat with 2 players is always launched as single player. Second player is not listed there.

Image

Image

And when hit back button game crash.

Image

### PR DESCRIPTION
**Pull request by MichalZr6**
This PR aims to:

- fix #6069 
- fix #5986 

This one maybe:
- #6045

### CODE REVIEW

**Comment by GeorgeK1ng** [comment]
Hot Seat seems to work now!

File: lib/serializer/PlayerConnectionID.h [hunk 1]
```diff
@@ -11,11 +11,48 @@
 
 VCMI_LIB_NAMESPACE_BEGIN
 
-enum class PlayerConnectionID : int8_t
+struct DLL_LINKAGE PlayerConnectionID
```
Comment (IvanSavenko) [inline lib/serializer/PlayerConnectionID.h]: Why not reuse existing Identifier class? Check for example classes like PrimarySkillID or SpellShoolID

File: server/CVCMIServer.cpp [hunk 2]
```diff
@@ -419,18 +419,19 @@ void CVCMIServer::clientConnected(std::shared_ptr<GameConnection> c, std::vector
 		si->mode = mode;
 	}
 
-	logNetwork->info("Connection with client %d established. UUID: %s", static_cast<int>(c->connectionID), c->uuid);
+	auto connID = static_cast<int>(c->connectionID);
```
Comment (IvanSavenko) [inline server/CVCMIServer.cpp:422]: Again - identifier classes have explicit getNum method for such cases.

File: lib/serializer/PlayerConnectionID.h (hunk 1 above)
Comment (MichalZr6) [reply lib/serializer/PlayerConnectionID.h]: Sure, didn't think of that.

File: server/CVCMIServer.cpp (hunk 2 above)
Comment (MichalZr6) [reply server/CVCMIServer.cpp:422]: I didn't touch `GameConnectionID` just used that `connID` as static_cast was done in multiple places there.
Should it be also made as struct instead of enum ?
Ok... just checked. It should: `c->connectionID = vstd::next(currentClientId, 1);`

Comment (IvanSavenko) [reply server/CVCMIServer.cpp:422]: If connectionID is enum - then code is ok. 
If connectionID is your new class -then switch to Identifier and use getNum(). Ideally - directly in logging call, without creating local.

IMO converting enum's or Identifiers to integers is necessary evil, so better to keep scope of this "evil" as small as possible

Comment (MichalZr6) [reply server/CVCMIServer.cpp:422]: This struct wrapper is unnecessary. Thought incrementing enum after defined fields is the bug. It is not. The fix is trivial will commit a bit later.
