### PR TITLE
Artifact assembly fix

### LINKED ISSUE #840: client bugs when assembling artefact set
Basically a duplicate of https://bugs.vcmi.eu/view.php?id=3039

https://user-images.githubusercontent.com/1557784/188576663-34b9d7cd-c799-4214-b4fe-9c80d2f4794d.mov

As clearly seen from the video, when you try to assemble a set (AotD in this case), something gets wrong with mouse cursor: the real cursor and the in-game one no longer have the same coordinates, which results in inability to click with the in-game cursor, and the behavior persists after dismissing the dialog.

Also, after clicking OK, the replaced artefact (Targ of Ogre) doesn't appear in the bag immediately, you have to click somewhere first.

Save game: [Archive.tar.gz](https://github.com/vcmi/vcmi/files/9494429/Archive.tar.gz), hero Daneel (Forge + new terrains).

### PR DESCRIPTION
**Pull request by IvanSavenko**
Fixes #840 - Correctly update drag-and-drop cursor if window with artifacts gets deactivated due to pop-up dialog
Fixes artefact-related assertion failures
Fixes Exchange Window not getting updated on assembly/deassembly of an artifact

### CODE REVIEW

File: client/widgets/CArtifactHolder.cpp [hunk 1]
```diff
@@ -254,6 +254,22 @@ void CHeroArtPlace::clickRight(tribool down, bool previousState)
...
+}
+
+void CArtifactsOfHero::deactivate()
+{
+	if (commonInfo->src.AOH == this && commonInfo->src.art)
+		CCS->curh->dragAndDropCursor(nullptr);
+
+	CIntObject::deactivate();
+}
+
```
Comment (Nordsoft91) [inline client/widgets/CArtifactHolder.cpp:272]: Could you please move those methods closer to other CArtifactsOfHero methods? Currently they are in the middle of CHerOArtPlace definitions

File: lib/CArtHandler.cpp [hunk 2]
```diff
@@ -1062,7 +1060,9 @@ void CCombinedArtifactInstance::createConstituents()
 
 void CCombinedArtifactInstance::addAsConstituent(CArtifactInstance *art, ArtifactPosition slot)
 {
-	assert(vstd::contains(*artType->constituents, art->artType.get()));
+	assert(vstd::contains_if(*artType->constituents, [=](const CArtifact * constituent){
```
Comment (Nordsoft91) [inline lib/CArtHandler.cpp:1063]:
```suggestion
	assert(artType && art && art->artType);
	assert(vstd::contains_if(*artType->constituents, [art](const CArtifact * constituent){
```
