### PR TITLE
Chronicles support

### LINKED ISSUE #2258: Chronicles campaigns
**Describe your proposal**
VCMI should allow to load the official chronicles campaigns. Currently, these cause VCMI to crash.

**Additional context**
Someone was able to convert these campaigns to Heroes III V6-format (Chronicles uses V7). https://heroes3wog.net/all-heroes-chronicles-campaigns-chapters-for-heroes-3-complete-with-hd-mod/
These files can be loaded without problems.

You can use a HEX-Editor to see the differences.

But we should able to load the original GOG-Versions of the H3C's, instead of the "hacked" ones.

### PR DESCRIPTION
**Pull request by Laserlicht**
Creates mod from gog installer in launcher (add file).

Allowing to add to VCMI without replacing any internal used resources.

New features are usable for custom campaigns too:
- Intro video with rim
- custom loading screen

Fixes #2258

Accessible under custom campaigns:
grafik

### Todo

- [x] override portraits in scenario
- [x] show intro video before starting campaign
- [x] extend `campaignOverrides.json` with all chronicles (and adjust coordinates)
- [x] process async in launcher

### Info

https://github.com/vcmi-mods/h3-themes should be extended with chronicles backgrounds. No native support (we are missing many buttons here).

No support for ISO/CD/... files yet...

### CODE REVIEW

**Comment by Laserlicht** [comment]
https://github.com/user-attachments/assets/273882da-37c5-4514-9864-9d0b9d509728

**Comment by Laserlicht** [comment]
Ready :)

File: client/lobby/CBonusSelection.cpp [hunk 1]
```diff
@@ -58,6 +59,39 @@
...
+
+	addUsedEvents(LCLICK | KEYBOARD);
+
+	pos = center(Rect(0, 0, 800, 600));
+
+	videoPlayer = std::make_shared<VideoWidgetOnce>(Point(80, 186), video, true, [this](){ exit(); });
+	setBackground(rim);
+
+	audioVol = CCS->musich->getVolume();
+	CCS->musich->setVolume(0);
```
Comment (IvanSavenko) [inline client/lobby/CBonusSelection.cpp:75]: Why not stop it instead? I think campaign screen will always play own music anyway

File: client/lobby/CBonusSelection.cpp [hunk 2]
```diff
@@ -93,7 +127,7 @@ CBonusSelection::CBonusSelection()
 	labelCampaignDescription = std::make_shared<CLabel>(481, 63, FONT_SMALL, ETextAlignment::TOPLEFT, Colors::YELLOW, CGI->generaltexth->allTexts[38]);
 	campaignDescription = std::make_shared<CTextBox>(getCampaign()->getDescriptionTranslated(), Rect(480, 86, 286, 117), 1);
 
-	mapName = std::make_shared<CLabel>(481, 219, FONT_BIG, ETextAlignment::TOPLEFT, Colors::YELLOW, CSH->mi->getNameTranslated(), 285);
+	mapName = std::make_shared<CLabel>(481, 219, FONT_BIG, ETextAlignment::TOPLEFT, Colors::YELLOW, CSH->mi->getNameTranslated(), CSH->getState() == EClientState::GAMEPLAY ? 225 : 285); //if video button active theres fewer space
```
Comment (IvanSavenko) [inline client/lobby/CBonusSelection.cpp:130]:
```suggestion
	bool videoButtonActive = CSH->getState() == EClientState::GAMEPLAY;
	int availableSpace = videoButtonActive ? 225 : 285;
	mapName = std::make_shared<CLabel>(481, 219, FONT_BIG, ETextAlignment::TOPLEFT, Colors::YELLOW, CSH->mi->getNameTranslated(), availableSpace );
```

File: config/heroes/portraits.json [hunk 3]
```diff
@@ -202,5 +202,179 @@
 		],
 		"skills" : [],
 		"specialty" : {}
+	},
+	"portraitTarnumBarbarian" :
+	{
+		"class" : "barbarian",
+		"special" : false,
```
Comment (IvanSavenko) [inline config/heroes/portraits.json:209]: Same for others
```suggestion
		"special" : true,
```

File: config/gameConfig.json [hunk 4]
```diff
@@ -271,6 +271,19 @@
 					"portraitYoungYog" : 162
 				}
 			},
+			"chronicles" : { 
+				"supported" : true,
+				"iconIndex" : 2,
```
Comment (IvanSavenko) [inline config/gameConfig.json:276]: No icon for this format?

File: lib/filesystem/CArchiveLoader.h [hunk 5]
```diff
@@ -63,12 +63,13 @@ class DLL_LINKAGE CArchiveLoader : public ISimpleResourceLoader
 	std::unique_ptr<CInputStream> load(const ResourcePath & resourceName) const override;
 	bool existsResource(const ResourcePath & resourceName) const override;
 	std::string getMountPoint() const override;
+	std::unordered_map<ResourcePath, ArchiveEntry> getEntries() const;
```
Comment (IvanSavenko) [inline lib/filesystem/CArchiveLoader.h:66]:
```suggestion
	const std::unordered_map<ResourcePath, ArchiveEntry> & getEntries() const;
```

File: lib/campaign/CampaignState.cpp [hunk 6]
```diff
@@ -455,6 +477,42 @@ std::set<CampaignScenarioID> Campaign::allScenarios() const
 	return result;
 }
 
+void Campaign::overrideCampaign(bool scenario)
```
Comment (IvanSavenko) [inline lib/campaign/CampaignState.cpp:480]: Perhaps split into two methods - override scenario & override campaign? Instead of bool parameter. Most of code is inside `if` block and `overrideCampaign(false)` is not exactly clear as to what it does

File: lib/campaign/CampaignHandler.cpp [hunk 7]
```diff
@@ -392,7 +397,8 @@ void CampaignHandler::readHeaderFromMemory( CampaignHeader & ret, CBinaryReader
 {
 	ret.version = static_cast<CampaignVersion>(reader.readUInt32());
 	ui8 campId = reader.readUInt8() - 1;//change range of it from [1, 20] to [0, 19]
-	ret.loadLegacyData(campId);
+	if(ret.version != CampaignVersion::Chr)
+		ret.loadLegacyData(campId);
```
Comment (IvanSavenko) [inline lib/campaign/CampaignHandler.cpp:401]: Why chronicles need separate handling here?

Comment (Laserlicht) [reply lib/campaign/CampaignHandler.cpp:401]: Because Chronicles uses own campId Logic (same ID's as main game)

File: config/gameConfig.json (hunk 4 above)
Comment (Laserlicht) [reply config/gameConfig.json:276]: There are basically separate icons. But a different for each chronicle. So our current logic don't work yet.

And there shouldn't be maps with this format out there. Because of that the only way to see this icon is on loading/saving screen. Showing SoD icon is ok for now, I think.

File: launcher/modManager/chroniclesextractor.cpp [hunk 8]
```diff
@@ -0,0 +1,276 @@
...
+		::extract_options o;
+		o.extract = true;
+
+		// standard settings
+		o.gog_galaxy = true;
+		o.codepage = 0U;
+		o.output_dir = tempDir.path().toStdString();
+		o.extract_temp = true;
+		o.extract_unknown = true;
+		o.filenames.set_expand(true);
```
Comment (IvanSavenko) [inline launcher/modManager/chroniclesextractor.cpp:95]: Copy-pasted from first install? Perhaps move into a shared method / class instead?

File: launcher/modManager/chroniclesextractor.cpp [hunk 9]
```diff
@@ -0,0 +1,276 @@
...
+{
+	QDir dir(pathToQString(VCMIDirs::get().userDataPath() / "Mods" / "chronicles" / "Mods" / ("chronicles_" + std::to_string(no))));
+	dir.removeRecursively();
+	dir.mkpath(".");
+
+	QJsonObject mod
+	{
+		{ "modType", "Expansion" },
+		{ "name", "Heroes Chronicles - " + QString::number(no) },
+		{ "description", "Heroes Chronicles - " + QString::number(no) },
```
Comment (IvanSavenko) [inline launcher/modManager/chroniclesextractor.cpp:168]: Perhaps use chronicle name, e.g. "World Tree" instead? Might be too long for mod name, but not a problem for description

Comment (IvanSavenko) [inline launcher/modManager/chroniclesextractor.cpp:168]: Perhaps enable Qt translations for name & description?

File: launcher/modManager/chroniclesextractor.cpp [hunk 10]
```diff
@@ -0,0 +1,276 @@
...
+#include "cli/extract.hpp"
+#include "setup/version.hpp"
+#endif
+
+ChroniclesExtractor::ChroniclesExtractor(QWidget *p, std::function<void(float percent)> cb) :
+	parent(p), cb(cb)
+{
+}
+
+bool ChroniclesExtractor::handleTempDir(bool create)
```
Comment (IvanSavenko) [inline launcher/modManager/chroniclesextractor.cpp:27]: Split into createTempDir / removeTempDir methods

File: launcher/modManager/chroniclesextractor.cpp (hunk 9 above)
Comment (IvanSavenko) [reply launcher/modManager/chroniclesextractor.cpp:168]: Oh, or remove "Heroes Chronicles" part and name them directly, e.g. "World Tree" - this is submod so it will be visible only inside of "Heroes Chronicles" submod.
No need for 8 submods with almost identical name

File: launcher/modManager/chroniclesextractor.cpp [hunk 11]
```diff
@@ -0,0 +1,276 @@
...
+	extract(tmpDir, outDirVideo, "xVideo.vid");
+	extract(tmpDir, outDirSounds, "xSound.snd");
+
+	tmpDir.cdUp();
+	if(tmpDir.entryList({"maps"}, QDir::Filter::Dirs).size())
+	{
+		QDir tmpDirMaps = tmpDir.filePath(tmpDir.entryList({"maps"}, QDir::Filter::Dirs).front());
+		for(const auto & entry : tmpDirMaps.entryList())
+			QFile(tmpDirMaps.filePath(entry)).copy(outDirData.filePath(entry));
+	}
```
[the remark this answers is not in the document]
Comment (Laserlicht) [reply launcher/modManager/chroniclesextractor.cpp:234]: Some special case... Only one of the 8 chronicles have the campaign in maps folder instead of lod file...

Can add a comment

File: launcher/modManager/chroniclesextractor.cpp [hunk 12]
```diff
@@ -0,0 +1,276 @@
...
+    jsonFile.write(QJsonDocument(mod).toJson());
+}
+
+void ChroniclesExtractor::createChronicleMod(int no)
+{
+	QDir dir(pathToQString(VCMIDirs::get().userDataPath() / "Mods" / "chronicles" / "Mods" / ("chronicles_" + std::to_string(no))));
+	dir.removeRecursively();
+	dir.mkpath(".");
+
+	QJsonObject mod
```
[the remark this answers is not in the document]
Comment (Laserlicht) [reply launcher/modManager/chroniclesextractor.cpp:164]: Chronicles in gog are only available in english.

File: launcher/modManager/chroniclesextractor.cpp (hunk 9 above)
Comment (Laserlicht) [reply launcher/modManager/chroniclesextractor.cpp:168]: Not sure. As they generated once.

Comment (IvanSavenko) [reply launcher/modManager/chroniclesextractor.cpp:168]: Should work as long as strings are translated at the time of import

File: launcher/modManager/chroniclesextractor.cpp (hunk 12 above)
[the remark this answers is not in the document]
Comment (Laserlicht) [reply launcher/modManager/chroniclesextractor.cpp:164]: Should be added later. If we support iso or installs.

Until then translations only via mod.

**Comment by Laserlicht** [comment]
@IvanSavenko Something left to do here before merging?

I may need some code from this PR for another PR I think. 🙂
