### PR TITLE
View Earth/Air crash fix

### LINKED ISSUE #1440: View Air/Earth spells crash server
Save from the latest develop: [Archive.tar.gz](https://github.com/vcmi/vcmi/files/10425101/Archive.tar.gz) First hero has these spells.

Never tried these spells before, can't say about 1.1 / 1.0.

macOS doesn't generate crash log, also server log doesn't have any info about this. Client log has this:

```
[2023-Jan-16 13:45:35.817104] TRACE network - Sending a request "12CastAdvSpell". It'll have an ID=4758.
[2023-Jan-16 13:45:35.817122] TRACE network - Sending a pack of type 12CastAdvSpell
[2023-Jan-16 13:45:35.817672] TRACE network - Received CPack of type 15AdvmapSpellCast
[2023-Jan-16 13:45:35.822022] TRACE network - 	Made first apply on cl: 15AdvmapSpellCast
[2023-Jan-16 13:45:35.822038] TRACE network - 	Applied on gs: 15AdvmapSpellCast
[2023-Jan-16 13:45:35.833787] ERROR network - Error: server failed to close correctly or crashed!
[2023-Jan-16 13:45:35.833827] ERROR network - Check /Users/kambala/Library/Logs/vcmi/server_log.txt for more info
[2023-Jan-16 13:45:35.882406] TRACE network - 	Made second apply on cl: 15AdvmapSpellCast
[2023-Jan-16 13:45:35.882564] ERROR network - Lost connection to server, ending listening thread!
[2023-Jan-16 13:45:35.882584] ERROR network - read_some: End of file [asio.misc:2]
[2023-Jan-16 13:45:35.883401] INFO network - Ending current game!
[2023-Jan-16 13:45:35.888769] INFO global - Removed GUI.
```

### PR DESCRIPTION
**Pull request by IvanSavenko**
Fixes #1440

### CODE REVIEW

File: client/CMusicHandler.cpp [hunk 1]
```diff
@@ -369,6 +369,7 @@ void CMusicHandler::release()
 		boost::mutex::scoped_lock guard(mutex);
 
 		Mix_HookMusicFinished(nullptr);
+		current->stop();
```
Comment (DjWarmonger) [inline client/CMusicHandler.cpp:372]: Is this a part of this PR?
