### PR TITLE
Less noise when switching languages in launcher

### LINKED ISSUE #4277: `Failed to load translation` messages for some translations
**Describe the bug**
When one select some translations in the launcher, the error message `Failed to install translator` is printed to the terminal.

**Game logs**
[VCMI_Launcher_log.txt](https://github.com/user-attachments/files/16240929/VCMI_Launcher_log.txt)

**To Reproduce**
1. Start `vcmilauncher`
2. Select all the languages under Settings > General > VCMI Language one after the other

**Expected behavior**
No error messages

**Actual behavior**
I've changed loadTranslation() to print the file name:

```c++
void MainWindow::loadTranslation()
{
#ifdef ENABLE_QT_TRANSLATIONS
	const std::string translationFile = settings["general"]["language"].String() + ".qm";
	logGlobal->info("Loading translation '%s'", translationFile);

	QString translatorFilename = QString{":/translation/%1"}.arg(translationFile.c_str());
	if (!translator.load(translatorFilename))
	{
		logGlobal->error("Failed to load translation %s", translatorFilename.toStdString());
		return;
	}

	if (!qApp->installTranslator(&translator))
		logGlobal->error("Failed to install translator %s", translatorFilename.toStdString());
#endif
}
```

```
      ~/Technik/Development/vcmi/build/bin  ./vcmilauncher                                                                                            ✔ 
Loading translation 'english.qm'
Failed to install translator :/translation/english.qm
File <unknown> is not a valid JSON file!
At line 33, position 1 warning: Comma expected!

Loading translation 'czech.qm'
Loading translation 'chinese.qm'
Loading translation 'english.qm'
Failed to install translator :/translation/english.qm
Loading translation 'finnish.qm'
Failed to load translation :/translation/finnish.qm
Loading translation 'french.qm'
Loading translation 'german.qm'
Loading translation 'hungarian.qm'
Failed to load translation :/translation/hungarian.qm
Loading translation 'italian.qm'
Failed to load translation :/translation/italian.qm
Loading translation 'korean.qm'
Failed to load translation :/translation/korean.qm
Loading translation 'polish.qm'
Loading translation 'portuguese.qm'
Loading translation 'russian.qm'
Loading translation 'spanish.qm'
Loading translation 'swedish.qm'
Failed to load translation :/translation/swedish.qm
Loading translation 'turkish.qm'
Failed to load translation :/translation/turkish.qm
Loading translation 'ukrainian.qm'
Loading translation 'vietnamese.qm'
```

**Did it work earlier?**
Unknown

**Screenshots**
na

**Version**
 - OS: openSUSE Tumbleweed 20240712
 - Version: develop (6f5710e809fae28720aa6d2b04f9fa0173224cda)

**Additional context**
na

### PR DESCRIPTION
**Pull request by Alexander-Wilms**
* Check if .qm file exists
* Don't call installTranslator() for English

Fixes #4277

### CODE REVIEW

File: launcher/mainwindow_moc.cpp [hunk 1]
```diff
@@ -236,16 +236,32 @@ void MainWindow::on_aboutButton_clicked()
...
+	if (!translator.load(translationFileResourcePath))
 	{
-		logGlobal->error("Failed to load translation");
+		logGlobal->error("Failed to load translation file %s", translationFileResourcePath.toStdString());
+		return;
+	}
+
+	if(translationFile == "english.qm")
+	{
+		// translator doesn't need to be installed for English
```
Comment (IvanSavenko) [inline launcher/mainwindow_moc.cpp:258]: Won't this result in translation not changing to English if I were to switch from language that has translation to English?

File: launcher/mainwindow_moc.cpp [hunk 2]
```diff
@@ -236,16 +236,32 @@ void MainWindow::on_aboutButton_clicked()
...
-	logGlobal->info("Loading translation '%s'", translationFile);
+	const std::string translationFile = settings["general"]["language"].String()+ ".qm";
+	QString translationFileResourcePath = QString{":/translation/%1"}.arg(translationFile.c_str());
 
-	if (!translator.load(QString{":/translation/%1"}.arg(translationFile.c_str())))
+	logGlobal->info("Loading translation %s", translationFile);
+
+	if(!QFile::exists(translationFileResourcePath))
+	{
+		logGlobal->warn("Translation file %s does not exist", translationFileResourcePath.toStdString());
```
Comment (IvanSavenko) [inline launcher/mainwindow_moc.cpp:246]: Probably no need to show this in console
```suggestion
		logGlobal->debug("Translation file %s does not exist", translationFileResourcePath.toStdString());
```

File: launcher/mainwindow_moc.cpp (hunk 1 above)
Comment (Alexander-Wilms) [reply launcher/mainwindow_moc.cpp:258]: No, the translation does switch back to English when selects the following sequence:

English -> German -> English

It does not work if I put the check before `translator.load`
