### PR TITLE
fix castle quick combat

### LINKED ISSUE #3608: Quick combat issue
Using a quick combat while defending the town, if lose in quick battle and reject the result, even win the battle by manual, the town will still become AI’s. 

In 1.50 development build. I think @Laserlicht need to know this because he made the quick combat function.

### PR DESCRIPTION
**Pull request by Laserlicht**
Should fix #3608

@by003 Please test it

### CODE REVIEW

**Comment by by003** [comment]
Is it fixed in develop build?

**Comment by Laserlicht** [comment]
No, it's not merged yet.

You have to download it here: https://github.com/vcmi/vcmi/actions/runs/8087791352

File: server/queries/BattleQueries.cpp [hunk 1]
```diff
@@ -104,6 +98,12 @@ void CBattleDialogQuery::onRemoval(PlayerColor color)
 	}
 	else
 	{
+		auto hero = bi->getSideHero(BattleSide::ATTACKER);
+		auto visitingObj = bi->getDefendedTown() ? bi->getDefendedTown() : gh->getVisitingObject(hero);
```
Comment (IvanSavenko) [inline server/queries/BattleQueries.cpp:102]: Why do we need actually "visiting object" instead of defender army? `bi->getSideArmy` I think?

File: server/queries/BattleQueries.cpp [hunk 2]
```diff
@@ -104,6 +98,12 @@ void CBattleDialogQuery::onRemoval(PlayerColor color)
...
+		
 		gh->battles->endBattleConfirm(bi->getBattleID());
+		
+		if(visitingObj)
+			visitingObj->battleFinished(hero, *result);
```
Comment (IvanSavenko) [inline server/queries/BattleQueries.cpp:107]: How will the game call `battleFinished` in case of AI-initiated battles? 

From what I see, `CBattleDialogQuery` is only created for AI-vs-human battles. And not created in AI-vs-AI or human-vs-human battles

Comment (Laserlicht) [reply server/queries/BattleQueries.cpp]: Yes, you're right. Changed it... new way only for AI vs human.

**Comment by by003** [comment]
Can you merge it into develop?

**Comment by by003** [comment]
There is a confusion in the version I have downloaded. If you reckon the bug is fixed, juest merge it into develop and I can make a thorough testing.

**Comment by Laserlicht** [comment]
> Can you merge it into develop?

From my side okay.
@IvanSavenko also ok from your side?
