### PR TITLE
server-side fixes to battle events

### LINKED ISSUE #826: Vampire's "drain life" animation is played before the attack
In the original, as well as from logical POV, life drain is done after attack

### LINKED ISSUE #861: damage from Fire Shield isn't written to the battle log

### PR DESCRIPTION
**Pull request by kambala-decapitator**
- fixes #826
- fixes #861
- fixes "creatures perished" battle log entry

normal merge please

### CODE REVIEW

**Comment by nullkiller** [comment]
Ok. Will do regular merge here!

File: server/CGameHandler.cpp [hunk 1]
```diff
@@ -1208,25 +1233,12 @@ void CGameHandler::applyBattleEffects(BattleAttack & bat, BattleLogMessage & blm
 		CStack::prepareAttacked(bsa, getRandomGenerator(), bai.defender->acquireState()); //calculate casualties
 	}
 
+	int64_t drainedLife = 0;
 	auto addLifeDrain = [&](int64_t & toHeal, EHealLevel level, EHealPower power)
```
Comment (Nordsoft91) [inline server/CGameHandler.cpp:1237]: Lambda looks a bit overhead since it's too lines (first call already checks toHeal)

File: server/CGameHandler.h [hunk 2]
```diff
@@ -126,7 +126,7 @@ class CGameHandler : public IGameCallback, public CBattleInfoCallback, public En
 
 	void makeAttack(const CStack * attacker, const CStack * defender, int distance, BattleHex targetHex, bool first, bool ranged, bool counter);
 
-	void applyBattleEffects(BattleAttack & bat, BattleLogMessage & blm, std::shared_ptr<battle::CUnitState> attackerState, FireShieldInfo & fireShield, const CStack * def, int distance, bool secondary); //damage, drain life & fire shield
+	int64_t applyBattleEffects(BattleAttack & bat, BattleLogMessage & blm, std::shared_ptr<battle::CUnitState> attackerState, FireShieldInfo & fireShield, const CStack * def, int distance, bool secondary); //damage, drain life & fire shield, returns amount of drained life
```
Comment (Nordsoft91) [inline server/CGameHandler.h:129]: it's completely misleading that applyBattleEffects returns drained life

Comment (Nordsoft91) [reply server/CGameHandler.h:129]:
```suggestion
	//damage, drain life & fire shield, returns amount of drained life
	int64_t applyBattleEffects(BattleAttack & bat, BattleLogMessage & blm, std::shared_ptr<battle::CUnitState> attackerState, FireShieldInfo & fireShield, const CStack * def, int distance, bool secondary);

```

**Review by Nordsoft91 — APPROVED** [review]

**Review by Nordsoft91 — APPROVED** [review]
