### PR TITLE
Using attack sprite

### LINKED ISSUE #2534: Monsters on Adv.Map don't use attack sprite from AVWattak.def
**Describe the bug**
When attacking monsters on an adventure map, it should use attack sprite from AVWattak.def. Instead it still remains in it's idle position

**Version**
 - OS: Windows
 - Version: 1.3, problably

OH behavior:
wa

vcmi behavior:
was

### LINKED ISSUE #4547: Pictures as frames from def files stopped showing.
**Describe the bug**
Functionality of using def frames as pictures stopped working.

**Game logs**

**To Reproduce**
`"icons" :
 {
 "village" : 
{
"normal" :
{
"large":  "newfaction/itpt.def:14",
"small" : "newfaction/ITPA.def:16"
}, 
"built" : 
{
"large" : "newfaction/itpt.def:15",
"small" : "newfaction/ITPA.def:17"
} 
},
"fort": 
{
"normal" :
{
"large":  "newfaction/itpt.def:14",
"small" : "newfaction/ITPA.def:16"
}, 
"built" : 
{
"large":  "newfaction/itpt.def:15",
"small" : "newfaction/ITPA.def:17"
} 
}
 }`

**Expected behavior**
Frames will be taken from def file and shown in-game

**Actual behavior**
Frames are not taken from def file and not shown in-game

**Did it work earlier?**
In Beta it works

**Screenshots**

**Version**
VCMI-branch-develop-39e5ba3

**Additional context**

### PR DESCRIPTION
**Pull request by Laserlicht**
Fixes #2534

Also reintroduce functionality: fixes #4547

### CODE REVIEW

**Comment by Laserlicht** [comment]
> I hope these fields will be voluntary and not neccesary?

Yes. If not used: It's like before without this attack-frame.

File: client/mapView/MapRenderer.cpp [hunk 1]
```diff
@@ -465,6 +465,20 @@ std::shared_ptr<IImage> MapRendererObjects::getImage(IMapRendererContext & conte
...
+	{
+		const auto * creature = dynamic_cast<const CArmedInstance *>(obj);
+		auto const & creatureType = LIBRARY->creh->objects[creature->appearance->subid];
+		auto dir = std::vector<int>({1, 2, 7, 8});
+		ImagePath imgPath = std::count(dir.begin(), dir.end(), attackerPos) ? creatureType->mapAttackFromRight : creatureType->mapAttackFromLeft;
+		if(!imgPath.empty())
+		{
+			auto img = ENGINE->renderHandler().loadImage(imgPath, EImageBlitMode::SIMPLE);
+			return img;
+		}
```
Comment (IvanSavenko) [inline client/mapView/MapRenderer.cpp]: This would load image on every frame, which might be rather slow.
Image probably needs to be stored in `MapRendererObjects` class

File: client/mapView/IMapRendererContext.h [hunk 2]
```diff
@@ -56,6 +56,9 @@ class IMapRendererContext
 	/// returns true if specified object is the currently active hero
 	virtual bool isActiveHero(const CGObjectInstance* obj) const = 0;
 
+	/// returns direction of attacker if specified object is a monster and currently attacked
+	virtual int monsterAttacked(const CGObjectInstance * obj) const = 0;
```
Comment (IvanSavenko) [inline client/mapView/IMapRendererContext.h]: "monster attacked" implies boolean yes/no, but this is not the case here

```suggestion
	/// Returns moveDir of hero that attacked this wandering monster, or -1 on failure
	int attackedMonsterDirection(const CGObjectInstance * wanderingMonster) const = 0;
```

File: config/schemas/creature.json [hunk 3]
```diff
@@ -153,6 +153,16 @@
...
+				"mapAttackFromLeft" : {
+					"type" : "string",
+					"description" : "Adventure map creature image when attacked from left",
+					"format" : "imageFile"
+				},
+				"mapAttackFromRight" : {
+					"type" : "string",
+					"description" : "Adventure map creature image when attacked from right",
+					"format" : "imageFile"
+				},
```
Comment (IvanSavenko) [inline config/schemas/creature.json:165]: Also needs to be in docs
