### PR TITLE
Voice for campaigns

### LINKED ISSUE #1992: Campaign prolog voice output
**Describe the bug**
Currently the voice output for the campaign prolog isn't played.

**To Reproduce**
Start Campaign

**Expected behavior**
In OH3: There is a voice output next to the video.

**Actual behavior**
No voice

### PR DESCRIPTION
**Pull request by Laserlicht**
fixes #1992

### CODE REVIEW

File: lib/campaign/CampaignHandler.cpp [hunk 1]
```diff
@@ -403,8 +404,13 @@ CampaignScenario CampaignHandler::readScenarioFromMemory( CBinaryReader & reader
 		ret.hasPrologEpilog = reader.readUInt8();
 		if(ret.hasPrologEpilog)
 		{
-			ret.prologVideo = CampaignHandler::prologVideoName(reader.readUInt8());
+			std::string originalCampaigns[] = { "DATA/GOOD1", "DATA/EVIL1", "DATA/GOOD2", "DATA/NEUTRAL1", "DATA/EVIL2", "DATA/GOOD3", "DATA/SECRET1", "DATA/AB", "DATA/BLOOD", "DATA/SLAYER", "DATA/FESTIVAL", "DATA/FIRE", "DATA/FOOL", "DATA/GEM", "DATA/GELU", "DATA/CRAG", "DATA/SANDRO", "DATA/YOG", "DATA/FINAL", "DATA/SECRET" };
+			bool isOriginalCampaign = std::find(std::begin(originalCampaigns), std::end(originalCampaigns), header.getFilename()) != std::end(originalCampaigns);
```
Comment (IvanSavenko) [inline lib/campaign/CampaignHandler.cpp:408]: I think we can assume that all campaigns in "DATA" directory are H3 campaigns instead of such list

File: client/CMusicHandler.h [hunk 2]
```diff
@@ -60,6 +60,7 @@ class CSoundHandler: public CAudioBase
 
 	std::map<AudioPath, int> ambientChannels;
 	std::map<int, int> channelVolumes;
+	std::map<int, bool> channelPlaying;
```
Comment (IvanSavenko) [inline client/CMusicHandler.h:63]: This approach won't work.
SDL can (and will) reuse sound channel ID's.

It works in your case (since no other sounds play) but if somebody attempts to reuse this method he might run into issues.

Instead you should set callback and close window when callback arrives.
See `BattleInterface::playIntroSoundAndUnlockInterface` for example

File: client/mainmenu/CPrologEpilogVideo.cpp [hunk 3]
```diff
@@ -29,8 +29,7 @@ CPrologEpilogVideo::CPrologEpilogVideo(CampaignScenarioPrologEpilog _spe, std::f
 
 	CCS->videoh->open(spe.prologVideo);
 	CCS->musich->playMusic(spe.prologMusic, true, true);
-	// MPTODO: Custom campaign crashing on this?
-//	voiceSoundHandle = CCS->soundh->playSound(CCampaignHandler::prologVoiceName(spe.prologVideo));
+	voiceSoundHandle = CCS->soundh->playSound(spe.prologVoice);
```
Comment (IvanSavenko) [inline client/mainmenu/CPrologEpilogVideo.cpp:32]: Will this work with custom campaigns? No "failed to play sound" errors in console or something like that?

File: lib/campaign/CampaignHandler.cpp (hunk 1 above)
Comment (Laserlicht) [reply lib/campaign/CampaignHandler.cpp:408]: What will happen if a mod place a H3C in data instead of maps folder?

**Review by IvanSavenko — APPROVED** [review]

File: lib/campaign/CampaignHandler.cpp [hunk 4]
```diff
@@ -168,6 +168,7 @@ CampaignScenario CampaignHandler::readScenarioFromJson(JsonNode & reader)
 		{
 			ret.prologVideo = VideoPath::fromJson(identifier["video"]);
 			ret.prologMusic = AudioPath::fromJson(identifier["music"]);
+			ret.prologVoice = AudioPath::fromJson(identifier["voice"]);
```
Comment (Nordsoft91) [inline lib/campaign/CampaignHandler.cpp:171]: Please update documentation:

https://github.com/vcmi/vcmi/wiki/VCMI-Campaign-format#prologepilog

Comment (Laserlicht) [reply lib/campaign/CampaignHandler.cpp:171]: Done :)
