### PR TITLE
Toolbar action names

### LINKED ISSUE #1454: toolbar actions don't have names
editor version from develop, macOS Intel.

to reproduce: right click the toolbar.

Screenshot 2023-01-17 at 12 14 32

### PR DESCRIPTION
**Pull request by rilian-la-te**
Fixes #1454.

Also updates Russian translation.

### CODE REVIEW

File: mapeditor/translation/english.ts [hunk 1]
```diff
@@ -302,45 +322,161 @@
...
+        <translation type="unfinished"></translation>
+    </message>
+    <message>
+        <location filename="../mapsettings.cpp" line="165"/>
+        <source>Have creatures</source>
+        <translation type="unfinished"></translation>
+    </message>
+    <message>
+        <location filename="../mapsettings.cpp" line="166"/>
+        <source>Have resources</source>
```
Comment (kambala-decapitator) [inline mapeditor/translation/english.ts:432]:
```suggestion
        <source>Accumulate resources</source>
```

File: mapeditor/translation/english.ts [hunk 2]
```diff
@@ -302,45 +322,161 @@
...
+        <translation type="unfinished"></translation>
+    </message>
+    <message>
+        <location filename="../mapsettings.cpp" line="167"/>
+        <source>Have building</source>
```
Comment (kambala-decapitator) [inline mapeditor/translation/english.ts:437]:
```suggestion
        <source>Construct building</source>
```

File: mapeditor/translation/english.ts [hunk 3]
```diff
@@ -302,45 +322,161 @@
...
+        <translation type="unfinished"></translation>
+    </message>
+    <message>
+        <location filename="../mapsettings.cpp" line="168"/>
+        <source>Capture city</source>
```
Comment (kambala-decapitator) [inline mapeditor/translation/english.ts:442]:
```suggestion
        <source>Capture town</source>
```

File: mapeditor/translation/english.ts [hunk 4]
```diff
@@ -302,45 +322,161 @@
...
+        <translation type="unfinished"></translation>
+    </message>
+    <message>
+        <location filename="../mapsettings.cpp" line="169"/>
+        <source>Beat hero</source>
```
Comment (kambala-decapitator) [inline mapeditor/translation/english.ts:447]:
```suggestion
        <source>Defeat hero</source>
```

**Review by kambala-decapitator — APPROVED** [review]
looks good besides some strings

File: mapeditor/translation/english.ts [hunk 5]
```diff
@@ -302,45 +322,161 @@
...
         <translation type="unfinished"></translation>
     </message>
+    <message>
+        <location filename="../mapsettings.cpp" line="163"/>
+        <source>No special victory</source>
+        <translation type="unfinished"></translation>
+    </message>
+    <message>
+        <location filename="../mapsettings.cpp" line="164"/>
+        <source>Have artifact</source>
```
[the remark this answers is not in the document]
Comment (rilian-la-te) [reply mapeditor/translation/english.ts:422]: @kambala-decapitator It should be changed in code, not in translation. I can commit this, but what is the point to have different translation in file and code?

[the remark this answers is not in the document]
Comment (kambala-decapitator) [reply mapeditor/translation/english.ts:422]: oh yes, you're absolutely right, forgot about that :) Please adjust if not a big deal for you (otherwise can got to another PR).

File: mapeditor/translation/english.ts (hunk 4 above)
Comment (rilian-la-te) [reply mapeditor/translation/english.ts]: done all

File: mapeditor/translation/english.ts (hunk 3 above)
Comment (rilian-la-te) [reply mapeditor/translation/english.ts]: done all

File: mapeditor/translation/english.ts (hunk 2 above)
Comment (rilian-la-te) [reply mapeditor/translation/english.ts]: done all

File: mapeditor/translation/english.ts (hunk 1 above)
Comment (rilian-la-te) [reply mapeditor/translation/english.ts]: done all

File: mapeditor/translation/english.ts [hunk 6]
```diff
@@ -302,45 +322,161 @@
...
+        <translation type="unfinished"></translation>
+    </message>
+    <message>
+        <location filename="../mapsettings.cpp" line="165"/>
+        <source>Have creatures</source>
```
[the remark this answers is not in the document]
Comment (rilian-la-te) [reply mapeditor/translation/english.ts]: done all

File: mapeditor/translation/english.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (rilian-la-te) [reply mapeditor/translation/english.ts]: done all

File: mapeditor/translation/english.ts [hunk 7]
```diff
@@ -302,45 +322,161 @@
...
+        <translation type="unfinished"></translation>
+    </message>
+    <message>
+        <location filename="../mapsettings.ui" line="186"/>
+        <source>Loss</source>
+        <translation type="unfinished"></translation>
+    </message>
+    <message>
+        <location filename="../mapsettings.ui" line="195"/>
+        <source>7 days without castle</source>
```
[the remark this answers is not in the document]
Comment (rilian-la-te) [reply mapeditor/translation/english.ts]: done all

**Review by kambala-decapitator — APPROVED** [review]
