### PR TITLE
campaign improvements

### LINKED ISSUE #1565: After campaign has been completed player is kicked to main menu
**Describe the bug**
After capturing the 7th tower in Griffin Cliff mission, I get the small text dialog that I won, but then am thrown out into the main menu (load game submenu)

**Game logs**
[mission-complete-vcmi-logs.zip](https://github.com/vcmi/vcmi/files/10704479/mission-complete-vcmi-logs.zip)

**To Reproduce**
1. Start any H3 (non-custom) campaign
2. Complete campaign, e.g. via instant-win cheat.

**Expected behavior**
Game returns to campaign selection screen. Completed campaign is marked with greek checkmark

**Actual behavior**
Game returns to main menu

**Did it work earlier?**
No

**Version**
 - OS: macOS
 - Version: 1.1.1 release

**Additional context**
- originally reported in https://forum.vcmi.eu/t/victory-in-a-campaign-mission-exits-into-main-menu/

### LINKED ISSUE #1959: Only first campaign mission should be unlocked by default
**Describe the bug**
Usually you have to pass the first mission to open another, but all are available immediately.

**Screenshots**

2036_Campaign

Mantis: https://bugs.vcmi.eu/view.php?id=2036

### PR DESCRIPTION
**Pull request by Laserlicht**
- After a completed campaign you get back to the campaign overview now.
- Campaign completed icon appears now
- Campaigns must now be unlocked (Thanks @dydzio0614 )

fixes #1959 
fixes #1565

### CODE REVIEW

**Comment by Laserlicht** [comment]
@IvanSavenko If you find time - can you review? I'm currently testing highscore screen. But I need the persistent storage merged to complete. :)

File: client/CServerHandler.cpp [hunk 1]
```diff
@@ -683,12 +683,24 @@ void CServerHandler::startCampaignScenario(std::shared_ptr<CampaignState> cs)
 		auto & epilogue = ourCampaign->scenario(*ourCampaign->lastScenario()).epilog;
 		auto finisher = [=]()
 		{
+			if(ourCampaign->campaignSet != "")
+			{
+				Settings entry = persistent.write["campaign"][ourCampaign->campaignSet][ourCampaign->getFilename()]["completed"];
```
Comment (IvanSavenko) [inline client/CServerHandler.cpp:688]: Perhaps simply
```suggestion
				Settings entry = persistent.write["completedCampaigns"][ourCampaign->getFilename()];
```
?
Don't expect more data in here other than completion status.

High scores AFAIK are not campaign/map based but global, across all maps, so should probably go into separate top-level config entry.

File: client/mainmenu/CCampaignScreen.cpp [hunk 2]
```diff
@@ -101,11 +102,24 @@ CCampaignScreen::CCampaignButton::CCampaignButton(const JsonNode & config)
...
+	if(persistent["campaign"][campaignSet][header->getFilename()]["completed"].Bool())
+		status = CCampaignScreen::COMPLETED;
+
+	for(const JsonNode & node : parentConfig[campaignSet]["items"].Vector())
+	{
+		for(const JsonNode & requirement : config["requires"].Vector())
+		{
+			if(node["id"].Integer() == requirement.Integer())
+				if(!persistent["campaign"][campaignSet][node["file"].String()]["completed"].Bool())
+					status = CCampaignScreen::DISABLED;
```
Comment (IvanSavenko) [inline client/mainmenu/CCampaignScreen.cpp:119]: Perhaps add some option to override this and have all campaigns unlocked without completion? E.g. `persistent["unlockAllCampaigns"].Bool()`

File: config/campaignSets.json [hunk 3]
```diff
@@ -5,13 +5,13 @@
...
-			{ "x":43,  "y":245, "file":"DATA/GOOD2.H3C",    "image":"CAMPGD2S", "video":"CGOOD2",   "open": true },
-			{ "x":313, "y":244, "file":"DATA/NEUTRAL1.H3C",  "image":"CAMPNEUS", "video":"CNEUTRAL", "open": true },
-			{ "x":586, "y":246, "file":"DATA/EVIL2.H3C",    "image":"CAMPEV2S", "video":"CEVIL2",   "open": true },
-			{ "x":34,  "y":417, "file":"DATA/GOOD3.H3C",    "image":"CAMPGD3S", "video":"CGOOD3",   "open": true },
-			{ "x":404, "y":414, "file":"DATA/SECRET1.H3C",   "image":"CAMPSCTS", "video":"CSECRET",  "open": true }
+			{ "id": 1, "x":90,  "y":72,  "file":"DATA/GOOD1",    "image":"CAMPGD1S", "video":"CGOOD1",   "requires": []        },
+			{ "id": 2, "x":539, "y":72,  "file":"DATA/EVIL1",    "image":"CAMPEV1S", "video":"CEVIL1",   "requires": []        },
+			{ "id": 3, "x":43,  "y":245, "file":"DATA/GOOD2",    "image":"CAMPGD2S", "video":"CGOOD2",   "requires": [1, 2, 4] },
+			{ "id": 4, "x":313, "y":244, "file":"DATA/NEUTRAL1", "image":"CAMPNEUS", "video":"CNEUTRAL", "requires": []        },
+			{ "id": 5, "x":586, "y":246, "file":"DATA/EVIL2",    "image":"CAMPEV2S", "video":"CEVIL2",   "requires": [1, 2, 4] },
```
Comment (IvanSavenko) [inline config/campaignSets.json:12]: Perhaps use filenames for requirements instead of integers? e.g. "DATA/GOOD1"?

File: lib/CConfigHandler.cpp [hunk 4]
```diff
@@ -17,6 +17,7 @@
 VCMI_LIB_NAMESPACE_BEGIN
 
 SettingsStorage settings;
+SettingsStorage persistent;
```
Comment (IvanSavenko) [inline lib/CConfigHandler.cpp:20]: Perhaps more complete name? Especially since this is global variable.
```suggestion
SettingsStorage persistentStorage;
```

```suggestion
SettingsStorage persistentSettings;
```

File: lib/CConfigHandler.cpp [hunk 5]
```diff
@@ -53,18 +54,26 @@ SettingsStorage::SettingsStorage():
 {
 }
 
-void SettingsStorage::init()
+void SettingsStorage::init(bool p)
```
Comment (IvanSavenko) [inline lib/CConfigHandler.cpp:57]: Perhaps provide filenames explicitly by caller? And perform validation only if scemaFilename is not empty?
```suggestion
void SettingsStorage::init(const std::string & dataFilename, const std::string & schemaFilename)

```

File: lib/campaign/CampaignState.h [hunk 6]
```diff
@@ -293,6 +293,8 @@ class DLL_LINKAGE CampaignState : public Campaign
 	static JsonNode crossoverSerialize(CGHeroInstance * hero);
 	static CGHeroInstance * crossoverDeserialize(const JsonNode & node, CMap * map);
 
+	std::string campaignSet = "";
```
Comment (IvanSavenko) [inline lib/campaign/CampaignState.h:296]: Non-trivial classes don't need zero-init.
```suggestion
	std::string campaignSet;
```

File: config/campaignSets.json (hunk 3 above)
Comment (Laserlicht) [reply config/campaignSets.json:12]: I like the current approach much more. For me it's cleaner.

**Comment by Laserlicht** [comment]
@IvanSavenko Thanks :)

**Comment by Laserlicht** [comment]
@IvanSavenko Any other points?
Got a draft for the high scores. Would like to create a draft PR for it, which needs the persistent storage. :)

File: client/CServerHandler.cpp [hunk 7]
```diff
@@ -683,12 +683,24 @@ void CServerHandler::startCampaignScenario(std::shared_ptr<CampaignState> cs)
...
+			if(ourCampaign->campaignSet != "")
+			{
+				Settings entry = persistentStorage.write["completedCampaigns"][ourCampaign->getFilename()];
+				entry->Bool() = true;
+			}
+
 			if(!ourCampaign->isCampaignFinished())
 			{
 				GH.windows().pushWindow(CMM);
 				GH.windows().pushWindow(CMM->menu);
```
Comment (Nordsoft91) [inline client/CServerHandler.cpp:695]: Can be moved out of if/else conditions since executed always

File: config/campaignSets.json
Comment (Nordsoft91) [inline config/campaignSets.json:1]: do we have any mod overriding this file?

File: lib/CConfigHandler.cpp [hunk 8]
```diff
@@ -53,18 +54,24 @@ SettingsStorage::SettingsStorage():
...
 	JsonUtils::assembleFromFiles(confName.getOriginalName()).swap(config);
 
 	// Probably new install. Create config file to save settings to
 	if (!CResourceHandler::get("local")->existsResource(confName))
-		CResourceHandler::get("local")->createResource("config/settings.json");
+		CResourceHandler::get("local")->createResource(dataFilename);
 
-	JsonUtils::maximize(config, "vcmi:settings");
-	JsonUtils::validate(config, "vcmi:settings", "settings");
+	if(schema != "")
```
Comment (Nordsoft91) [inline lib/CConfigHandler.cpp:70]:
```suggestion
	if(!schema.empty())
```

File: lib/CConfigHandler.cpp [hunk 9]
```diff
@@ -74,9 +81,10 @@ void SettingsStorage::invalidateNode(const std::vector<std::string> &changedPath
 
 	JsonNode savedConf = config;
 	savedConf.Struct().erase("session");
-	JsonUtils::minimize(savedConf, "vcmi:settings");
+	if(schema != "")
```
Comment (Nordsoft91) [inline lib/CConfigHandler.cpp:84]:
```suggestion
	if(!schema.empty())
```

File: lib/VCMI_Lib.cpp [hunk 10]
```diff
@@ -52,7 +52,8 @@ DLL_LINKAGE void preinitDLL(CConsoleHandler * Console, bool onlyEssential, bool
 	console = Console;
 	VLC = new LibClasses();
 	VLC->loadFilesystem(extractArchives);
-	settings.init();
+	settings.init("config/settings.json", "vcmi:settings");
+	persistentStorage.init("config/persistentStorage.json", "");
```
Comment (Nordsoft91) [inline lib/VCMI_Lib.cpp:56]: what the purpose for that? is it user data? If so, maybe consider another name?

File: config/campaignSets.json
Comment (Laserlicht) [reply config/campaignSets.json:1]: search doesn't find anything... https://github.com/search?q=org%3Avcmi-mods+campaignSets.json&type=code

File: lib/VCMI_Lib.cpp (hunk 10 above)
Comment (Laserlicht) [reply lib/VCMI_Lib.cpp:56]: I think it's okay.

It's a generic data storage for persistent things (campaign results, highscores, etc...). Does not necessarily have to be userdata.
