### PR TITLE
fix creature reward message

### LINKED ISSUE #7117: AdvEvent.txt message 34 expects more parameters than it is currently supplied
**Describe the bug**
`core.advevent.34` ("Having defeated the %s, you discover %s.") is only supplied the string for the guards (first %s) and is missing the string for the rewards (second %s).

**Game logs**
Nothing logged.

**To Reproduce**

1. Make a map with a Dragon Fly Hive (uses `"message" : 34`)
2. Defeat the Dragon Flies
3. Read the reward message

**Screenshots**

Image

**Expected behavior**
Having defeated the Dragon Flies, you discover Wyverns.

**Actual behavior**
Having defeated the Dragon Flies, you discover .

**Did it work earlier?**
Don't think so

**Version**

- OS: Win7 64-bit
- Version: VCMI-branch-beta-93846ab

### PR DESCRIPTION
**Pull request by Laserlicht**
Fixes #7117

### CODE REVIEW

File: lib/rewardable/Info.cpp [hunk 1]
```diff
@@ -356,6 +362,9 @@ void Rewardable::Info::replaceTextPlaceholders(MetaString & target, const Variab
 		for (const auto & secondary : info.reward.secondary )
 			target.replaceName(secondary.first);
 
+		for (const auto & creature : info.reward.creatures )
+			target.replaceNamePlural(creature.getId());
```
Comment (IvanSavenko) [inline lib/rewardable/Info.cpp]: replaceName has overload that accepts creature+amount and will auto switch between singular and plural versions
