### PR TITLE
[Mapeditor] H3c, h3m converters and Campaign Editor fixes

### LINKED ISSUE #6704: h3m and h3c converter crashes editor
**Describe the bug**
It's impossible to convert any h3m and h3c files into vcmi ones.

**To Reproduce**
Try to convert any campaigns (for example from here)
https://github.com/vcmi-mods/campaings-pack/tree/vcmi-1.7/campaings-pack/Mods/sod-campaigns-pack/content/maps/sod-campaigns-pack

**Expected behavior**
After choosing name, conventer should convert maps/campaign

**Actual behavior**
Conventer does nothing during h3m conversion and produce 0 bites file during h3c conversion.

**Did it work earlier?**
Most likely for 1.6.8

**Version**

- OS: Windows
- Version: latest betas

### PR DESCRIPTION
**Pull request by MichalZr6**
- Fix crashes when converting h3m or h3c files. Also fixes #6704 
- Fix Campaign Editor to use `EditorCallback` correctly

### CODE REVIEW

File: mapeditor/campaigneditor/campaigneditor.cpp [hunk 1]
```diff
@@ -405,7 +406,8 @@ std::unique_ptr<CMap> CampaignEditor::tryToOpenMap(QWidget* parent, std::shared_
 {
 	try
 	{
-		auto map = state->getMap(scenario, nullptr);
+		static std::unique_ptr<EditorCallback> cb = std::make_unique<EditorCallback>(nullptr);
```
Comment (Laserlicht) [inline mapeditor/campaigneditor/campaigneditor.cpp]: `ScenarioProperties` also needs this change twice. `cb` should added in constructor.
- line 28 - constructor
- line 135

Comment (MichalZr6) [reply mapeditor/campaigneditor/campaigneditor.cpp]: Done. But check case when you create via New button -> immediately save -> reopen.

Comment (Laserlicht) [reply mapeditor/campaigneditor/campaigneditor.cpp]: Done: #6789
