### PR TITLE
[1.7.4] Remove bonuses with "UNTILL_BEING_ATTACKED" bonus after counterattack.

### LINKED ISSUE #6739: Blind attack reduction on advanced level has the wrong value
**Describe the bug**
Advanced Blind states: Blinds a creature so that it cannot move and causes it to counterattack at one-quarter of its normal attack strength.
However, it merely reduces enemy's attack power by 25%.

**Game logs**
[core_spells.blind.json](https://github.com/user-attachments/files/24655876/core_spells.blind.json)

**To Reproduce**

1. Have a hero with Advanced Fire Magic and Blind
2. Check the retaliation damage
3. Cast Blind on Enemy
4. Check the retaliation damage again
5. See that it only reduces it by a quarter instead of to a quarter

**Expected behavior**
Advanced Blind should reduce enemy's retaliation by 75%.

**Actual behavior**
Advanced Blind only reduces enemy's retaliation by 25%.

**Did it work earlier?**
No idea, sorry.

**Version**

- OS: Windows x64
- Version: VCMI 1.7.2 beta (build: VCMI-branch-beta-5a9631e)

### PR DESCRIPTION
**Pull request by Opuszek**
I reworked this pr from scratch. I've misunderstood how a duration was supposed to work because I looked at comments instead of md files :P.
It resolves #6739, as well as problems with petrification and paralyze not allowing counterattack (medusa&basilisk and scorpicore special abilities).

It is a little complex, so taking pr apart step by step:

Problem #1: UNTIL_ATTACK duration is bugged.
According to documentation bonuses with this duration are supposed to be removed after all attacks and counterattacks are performed. Instead of that, they are removed after each attack or counterattack.
The solution was to move the removal of this bonus to BattleActionProcessor after attacks/counterattack sequence.
Problem #2: Blind spell counterattack damage reduction does not work.
It has duration UNTILL_BEING_ATTACKED (so until taking any form of damage), so naturally it does not work, since attack provoking this counterattack removes the bonus. 
NO_RETALIATION bonus of blind spell also should not have worked, but it was hardcoded as an exception.
The solution was to use the fixed UNTIL_ATTACK bonus instead. Also, removing the hardcoded exception.
Removal of the hardcoded exception also fixed retaliation bug for petrification and paralyze effects.
But it caused
Problem #3 indirect damage does not remove blind/petrification/paralyze bonuses.
I tried different ways to solve this, but I settled on adding new duration UNTIL_TAKING_INDIRECT_DAMAGE. Now it looks like this:

UNTIL_TAKING_INDIRECT_DAMAGE removes a bonus immediately after:

Hero Spell damage
Creature spell damage
Indirect melee damage (dragon)
Indirect range damage (lich)
Fire shield
Moat damage

Minefield spell could not be tested (it is currently bugged).

UNTIL_ATTACK removes a bonus from both attacker and defender after full attacks/counterattack sequence for:
Meele creature direct attack
Range creature direct attack
Tower attack
Ballista attack

UNTIL_ATTACK bonuses added during this attacks/counterattack sequence are not removed. (like damage reduction bonus added by paralyze effect of scorpione)

UNTIL_BEING_ATTACKED removes a bonus immediately after any damage is taken.

So, for example:

"GeneralAttackReduction" effect of blind spell has both  UNTIL_TAKING_INDIRECT_DAMAGE and UNTIL_ATTACK durations, since it is removed either by taking indirect damage (like hero spell) or going through full attack/contrattack sequence (since it is supposed to be active during a/c sequence it cannot have UNTIL_BEING_ATTACKED duration).
"Not active" effect of blind spell has UNTIL_BEING_ATTACKED duration, since bonuses needs to be removed immediately after taking any damage (in a/c case so unit can retaliate).
"No retaliate" effect on the expert blind spell has "UNTIL_ATTACK" and " UNTIL_TAKING_INDIRECT_DAMAGE" duration, since it is supposed to work during next a/c sequence. 
"No retaliate" effect on petrification ability has "UNTIL_BEING_ATTACKED" duration, since it is supposed to take effect only on the very same a/c sequence that applies this effect. During next a/c sequence this effect will be removed when the unit will be damaged and it will be able to counterattack normally.

I still need to add the new duration to documentation and make some additional checks for other bonuses.

### CODE REVIEW

File: server/battles/BattleActionProcessor.h [hunk 1]
```diff
@@ -46,13 +46,21 @@ class BattleActionProcessor : boost::noncopyable
...
+	};
+
 	using FireShieldInfo = std::vector<std::pair<const CStack *, int64_t>>;
 
 	BattleProcessor * owner;
 	CGameHandler * gameHandler;
 
 	MovementResult moveStack(const CBattleInfoCallback & battle, int stack, BattleHex dest); //returned value - travelled distance
-	void makeAttack(const CBattleInfoCallback & battle, const CStack * attacker, const CStack * defender, int distance, const BattleHex & targetHex, bool first, bool ranged, bool counter);
+	void makeAttack(const CBattleInfoCallback & battle, const CStack * attacker, const CStack * defender, const BattleHex & targetHex, AttackInfo attack);
```
Comment (C3pa) [inline server/battles/BattleActionProcessor.h]: Can you make the attack argument a const reference?

Comment (Opuszek) [reply server/battles/BattleActionProcessor.h]: Done.

**Comment by Karyoplasma** [comment]
You could fix Blind with this as well. config/spells/timed.json and add this in blind:
```
			"advanced":{
				"power" : 75
			},
```

**Comment by IvanSavenko** [comment]
Used for Stone Gaze and in bunch of mods:
https://github.com/search?q=org%3Avcmi-mods+UNTIL_BEING_ATTACKED&type=code

This change won't break this logic?

File: lib/gameState/GameStatePackVisitor.cpp [hunk 2]
```diff
@@ -1654,6 +1652,25 @@ void BattleStatePackVisitor::visitStacksInjured(StacksInjured & pack)
...
+	});
+
+	for (auto * stack : stacksInjuredBySpell)
+	{
+		BonusList bonuses = *stack->getBonuses(Bonus::UntilBeingAttacked);
+		std::vector<Bonus> buffer;
+		for (const auto & bonus : bonuses)
+			buffer.push_back(*bonus);
+		battleState.removeUnitBonus(stack->unitId(), buffer);
+	}
```
Comment (IvanSavenko) [inline lib/gameState/GameStatePackVisitor.cpp]: Why we can't simply iterate over `pack.stacks`?
E.g.
```
for (const auto injuryInfo : pack.stacks)
{
    stack = battleState.getStackById(injuryInfo.stackAttacked);
    stack->getBonuses(Bonus::UntilBeingAttacked);
	for (const auto & bonus : bonuses)
		buffer.push_back(*bonus);
	battleState.removeUnitBonus(stack->unitId(), buffer);
}
```

OR even better:
```
for (const auto injuryInfo : pack.stacks)
{
    stack = battleState.getStackById(injuryInfo.stackAttacked);
    stack->removeUnitBonus(Bonus::UntilBeingAttacked);
}
```

File: server/battles/BattleActionProcessor.h [hunk 3]
```diff
@@ -46,13 +46,21 @@ class BattleActionProcessor : boost::noncopyable
 		bool invalidRequest;
 	};
 
+	struct AttackInfo
+	{
+		int distance;
+		bool first;
+		bool ranged;
+		bool counter;
```
Comment (IvanSavenko) [inline server/battles/BattleActionProcessor.h]: To be safe
```suggestion
		int distance = 0;
		bool first = false;
		bool ranged = false;
		bool counter = false;
```

**Comment by Opuszek** [comment]
> Used for Stone Gaze and in bunch of mods: https://github.com/search?q=org%3Avcmi-mods+UNTIL_BEING_ATTACKED&type=code
> 
> This change won't break this logic?

I had to rework it completely. Now it actually fixes Stone Gaze and Paralyze (before they were bugged).
The problem turned out to be UNTIL_ATTACK duration not working as it was advertised in documentation.
I will check the rest of bonuses using it, but as for the mods it is hard to tell. They may very well be mods using it as it currently is, but I don't know what we can do with it.
Maybe leaving UNTIL_ATTACK as it is (only fixing the description in documentation) and adding a separate bonus that behaves as UNTIL_ATTACK is supposed to behave?

File: lib/gameState/GameStatePackVisitor.cpp (hunk 2 above)
Comment (Opuszek) [reply lib/gameState/GameStatePackVisitor.cpp]: The code mentioned has been removed.

File: server/battles/BattleActionProcessor.h (hunk 3 above)
Comment (Opuszek) [reply server/battles/BattleActionProcessor.h]: The code mentioned has been removed.

**Comment by Opuszek** [comment]
@IvanSavenko it is ready to review.
I changed the documentation for UNTIL_ATTACK and added a new duration that behaves as UNTIL_ATTACK was supposed to behave to not break any mods.
I also fixed Frenzy. On current beta branch for a unit with multiple attacks (like crusaders) frenzy applies only to the first attack, when it should work for all of them (tested on OG).

**Comment by Opuszek** [comment]
Edit: I updated the version of gcc on my pc to the one used by gcc-latest-release and rebased feature branch on beta, but I still cannot replicate the test failure. Anybody knows what may've caused it?

**Comment by IvanSavenko** [comment]
> Edit: I updated the version of gcc on my pc to the one used by gcc-latest-release and rebased feature branch on beta, but I still cannot replicate the test failure. Anybody knows what may've caused it?

This test seems to be failing randomly, like 5%-10% of runs. Not a regression from your PR

**Comment by Opuszek** [comment]
Edit: I removed fix for frenzy spell. It turns out in OG frenzy always ends at the start of second turn of affected unit (not after attack). I don't think it is behavior that can be imitated with current durations and since I found that the fix brings its own problems with itself I don't want to touch it for now.

File: launcher/lib/innoextract
Comment (IvanSavenko) [inline launcher/lib/innoextract:1]: Unintended?

Comment (Opuszek) [reply launcher/lib/innoextract:1]: Yep.
Fixed.

**Review by IvanSavenko — APPROVED** [review]
Looks OK, but let's merge after 1.7.3, in case if there is some edge case that is not handled correctly.
